### ISSUE TITLE
Kustutamisel õppevara raporteeritutest ära

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#100]
**Arendusvajadus:**
Musta bännerit õppevara päises võib olla ainult 1  - praegu tekib neid teatud juhtudel mitu
, nt kui raporteeritud õppevara kustutatakse, peab ta kustuma ära 'raporteeritute' nimekirjast.

Aineeksperdi ja admini töövoo nupud, mis praegu on kolme täpi all peidus peavad olema näha sellel mustal ribal paremale joondatud ikoonidena:
- raporteeritud õppevara korrasolevaks märkimiseks ikoon 'done' (kõige parempoolne ikoon)
- raporteeritud õppevara kustutamiseks ikoon 'delete'
- kustutatud õppevara taastamisks ikoon 'undo' või 'restore_page'

**Tulem:**
- [x] Kui materjal on kustutatud, siis materjal peab ära kaduma töölaualt ebasobivate ja katkiste nimekirjast.

- [x] Kui materjal on kustutatud, siis on üks must bänner, millel on kirjas, et materjal on kustutaud ja nupp "Taasta".

- [x] Kui materjal on katkine, siis on üks must banner ja nupp "Märgi katkine sisu korras olevaks","Kustuta".

- [x] Kui materjal on ebasobiv, siis on üks must banner ja nupp "Märgi sisu sobivaks", "Kustuta".

- [x] Kui materjal on katkine ja ebasobiv, siis on üks must banner ja kaks nuppu: "Kustuta" ja "Märgi sisu sobivaks".

**Comment by KatarinaNeff** [comment]
kailia	[2:18 PM]  
Kas nii: Kui materjal on katkine ja ebasobiv, siis on üks must banner ja kaks nuppu "Kustuta" ja  "märgi raporteeritud õppevara korrasolevaks"?

martlaus	[2:18 PM]  
kaili, 1 nupp teeb kahte asja, jah

erkki	[2:19 PM]  
võib ka teha kolme asja, nt raporteeritud ebasobiv sisu, võtmesõna ja katkine link
