### ISSUE TITLE
Korrastada layout xl

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#101]
#102 raames jäi lahendamata viga
- [ ] Materialboxi pildi kuvasuhe 1.50 mitte 1.38:1

**Comment by KailiAll** [comment]
Soov: valgel päisel sinine kinnitamise "linnuke" peab olema peatüki dropdownile lähemal, kuna suurel ekraanil on see liiga kaugel.

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
