### ISSUE TITLE
Materjali valimisel kogumikku lisamise päis

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#103]
**Arendusvajadus:**
Praegu muutub materjali valimisel vaid FAB sisu ja päise värv, mis on raskesti märgatav. Vaja on kasutajale paremini ette näidata, mida ta valitud materjalidega saab ette võtta (luua neist uus kogumik, lisada need olemasolevasse). Uurida Inbox käitumist ja sobivusel pakkuda lahendus sarnase valge päise abil, millel on näha valitud materjalide arv, edasise flow nupud ja tagasiminek valiku tühistamiseks
**Tulem:**
Kogumikke luua ja seega materjale saab valida ainult sisseloginud kasutaja.
- [x] Materjali valimisel märkeruuduga tekib portaali päise kohale või asemele uus päis kogumikku lisamiseks.
- [x] Kogumikku lisamise päisel kuvatakse, mitu materjali on valitud. 
- [x] Kogumikku lisamise päisel kuvatakse, valikmenüüd kogumiku valimiseks, kui kasutaja polnud konkreetse kogumiku muutmise režiimis. Kui muudab kindlat kogumikku, siis seda ei kuvata.
- [x] Kogumikku lisamise päisel kuvatakse, peatüki valikmenüüd.
- [x] Kogumikku lisamise päisel kuvatakse Katkesta nuppu, mis tühistab materjalide valikud.
- [x] Kogumikku lisamise päisel kuvatakse Lisa nuppu, mis lisab valitud materjalid kogumiku peatükki, kui kogumik ja peatükk on valitud.

**Comment by kokakoola** [comment]
Päis katab olemasoleva päise, tuleb ülalt peale. Aga miks mitte lilla kui lilla on meil nagunii juba tegevusvärv - me ju muudame praegu kogumikku, lisame sinna materjale, st ehk oleks põhjendatud sama värvi kasutamine?

![screen shot 2016-11-25 at 11 05 47](https://cloud.githubusercontent.com/assets/672595/20619859/5a841670-b2ff-11e6-98ff-d9bcfa81bf5f.png)

**Comment by aivo0** [comment]
@kokakoola @erkkijakobson Mare pildist see task ei hõlma kaartidele joonistatud märkeruudu ümber tegemist. Ja otsingu tulemuste tekstilist kokkuvõtet.

**Comment by aivo0** [comment]
Kolm täiendussoovi Mare joonisele:
1. Vaskul ääres on Tagasi nupp (nagu Inbox-s) 
![image](https://cloud.githubusercontent.com/assets/8111493/20878419/7f983038-bad7-11e6-8eb0-5ca2f97d125c.png)
2. "Valitud: 2" võik solla joondatud alates materjalide kaartide algusest.
3. See päis võiks olla alati valge, olenemata, kas kasutaja on kogumiku muutmise režiimis või lihtsalt sooritas otsingu ja märkis materjali.
