### ISSUE TITLE
Vasakmenüüs haridustasemetes vahetavad taksonid ise enda järjekorda

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#107]
**Arendusvajadus:**
Nelja haridustaseme all avanevad taksonid (valdkonnad/ained jt) hüplevad järjestuses: nt üks hetk on Keskhariduse all esimene valdkond Matemaatika, hetk hiljem on seal Kehaline kasvatus, ei tohi selliselt kasutajat segadusse ajada vaid püsima alati samas (tähestiku)järjekorras.

**Tulem:**
- [ ] Taksonid avanevad tähestikulises järjestuses.

**Comment by KailiAll** [comment]
Tegemist ei ole veaga, kuna eelnevalt ei ole olnud sellist nõuet, et need peavad olema tähestiku järjekorras.

**Comment by KailiAll** [comment]
#https://github.com/hariduspilv/koolikott/issues/116
