### ISSUE TITLE
Õpiväljundite rakendamine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#11]
**Vajadus**
Õpiväljundid, mis on listitud riiklikes õppekavades, on ka e-Koolikotis.
**Tulem**
- [ ] võimaldada õppematerjali ja kogumiku metaandmetes määrata taksonitele vastavaid õpiväljundeid.
- [ ] õpiväljundeid kuvatakse materjali ja kogumiku detailvaates
- [ ] detailotsingus on võimaldatud õpiväljundite põhine otsing
- [ ] väljundite sidumine õppekavaga peab toimima ka teenusena välisele süsteemile, liidese spec wikisse

**Comment by aivo0** [comment]
Töösse võtmiseks on vaja metaandmestikku. 
Marelt on vajalik välja kuvamise disain.

**Comment by kokakoola** [comment]
@erkkijakobson @aivo0 Palun nimetada vähemalt üks Õpiväljund (tekstinäiteks)

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati tõsta see töö e-Koolikoti Confluence'i analüüsi backlogi.
