### ISSUE TITLE
Taksonoomia muutumisel kuvatakse vasakmenüüs kasutajale vana versiooni

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#112]
Leida lahendus, kuidas peale igat LIVEt ei tekiks kasutajal olukorda, kus talle kuvatakse andmebaasi tabeleid.

![ekoolikott](https://cloud.githubusercontent.com/assets/19947450/20097400/e3ad81c6-a5b6-11e6-88cb-c39de70741e6.JPG)

**Comment by martlausNG** [comment]
Tegemist ei ole kuidagi andmebaasi tabelitega. Caps lockis tekst, mida nähakse on translation key. Kas probleem esineb ainult siis, kui serverile teha restart ning pärast refreshi on korras?

**Comment by erkkijakobson** [comment]
lehel käinud sirvik vs inkognito
![image](https://cloud.githubusercontent.com/assets/16906555/20338341/1c18445a-abdf-11e6-801d-5c37c29dde9c.png)

**Comment by erkkijakobson** [comment]
viga tekib sirvikute Local Storage asukohta esmakordsel lehe külastusel talletuvast reducedTaxon väärtusest, mille muutumisel rakendus sellest sirvikule teada ei anna

**Comment by martlausNG** [comment]
Teise issue all on juba reducedtaxon testkeskkonnas välja võetud, seega peaks olema juba lahendatud.

**Comment by aivo0** [comment]
Klient raporteerib, et viga ikka veel Lives: https://files.jotform.com/jufs/aivo0/63323576991364/356152008131727377/pilt.png?md5=GZGJmGeE7zOHlzIhnVoUEQ&expires=1480344435
