### ISSUE TITLE
Täpse otsingu avamisel ei näe kasutaja avanenud otsingut

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#113]
**Eeltingimus:** -

**Vea olukorra tekitamine**
1. keri suvalises vaates lehe võrra alla
2. vajuta  'täpse otsingu' nupul

**Tulemus**
kasutaja ei näe täpse otsingu kasti

**Oodatud tulemus**
kasutaja näeb täpse otsingu kasti

**Lisainfo:** -

**Tulemus:**
- [ ] Kui kasutaja on infinity srcolliga liikunud lehe alla ja avab täpse otsingu, siis kasutaja näeb avanenud otsingut.

**Comment by KailiAll** [comment]
tegemist ei ole veaga.

**Comment by KailiAll** [comment]
Põhjus, miks tegemist ei ole veaga.
Varem polnud seal infinite scrolli ja kui advanced search avada, siis sa olid alati peaaegu lehe kõige üleval. Nüüd sa võid olla väga kaugel lehe ülemisest otsast. See osa muutus infinite scroliga ja seda polnud varem tellitud.

**Comment by erkkijakobson** [comment]
Tegemist on tehnoloogilise selgitusega, millest kasutajal abi ei ole - tema jaoks nupp ei tööta ja see on viga, mitte featuur

**Comment by KailiAll** [comment]
Sellisel juhul on see arenduse jaoks featuur ja kasutaja jaoks viga.
