### ISSUE TITLE
Kogumiku loomisel peab ainevaldkonna alt olema võimalik valida mitut õppeainet

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#114]
**Arendusvajadus:**
Lisa kogumiku põhiandmed-> Haridus->Valdkond/ Ainevaldkond alt peab olema võimalik valida mitut õppeainet korraga.

**Tulem:**
Lahendus sama, mis materjali lisamisel modaalil.
- [x] Haridus->Valdkond/ Ainevaldkond alt saab valida mitut õppeainet korraga.

**Comment by aivo0** [comment]
Sama komponent, mis materjali puhul.

**Comment by martlausNG** [comment]
Sama komponent, mis materjali lisamisel tuleb kogumikku, st pluss nupp.
