### ISSUE TITLE
Kogumike visuaalne eristamine privaatsuse järgi

### ISSUE THREAD

**Issue by aivo0** [hariduspilv/koolikott#115]
**Arendusvajadus:**
Kõigi sisseloginud kasutajate jaoks on lingiga jagatud ja privaatsed kogumikud avalikest kogumikest visuaalselt eristatavad, et kasutajad saaksid kiiresti aru, kas nende enda kogumik või neile nähtav kogumik on privaatne, lingiga jagatud või kõigile nähtav. 
See lihtsustab modereerivate kasutajate tööd, kes võivad lingiga jagatud kogumikke teisiti modereerida. See lihtsustab admin kasutajate tööd, kes saavad kiiresti eristada kogumikke, mis on privaatsed. Ning see annab kindlustunnet kogumike loojatele, et nende kogumik on privaatne või ainult teatud inimestele (lingiga) jagatud.
Visuaalne eristus võiks tõenäoliselt olla ikoon kogumiku kaardi allosas, nagu Youtube's:
![image](https://cloud.githubusercontent.com/assets/8111493/20347743/082c2462-ac0b-11e6-9345-ca2a05b1be43.png). Kogumiku detailvaate muutmise vaates on nähtavus juba paremal ülaosas nähtav ja sarnaseid ikoone tuleks kasutada ka kogumike kaartidel.
Ikoone on näha nii kogumike kaartidel kui ka detailvaates.
**Tulem:**
- [x] Kõik kasutajad näevad "Minu kogumikud" vaates oma privaatsete kogumike kaartidel sellele vastavat ikooni. Ikoonile hiirega liikudes kuvatakse teksti "Privaatne".
- [x] Kõik kasutajad näevad "Minu kogumikud" vaates oma lingiga jagatud kogumike kaartidel sellele vastavat ikooni. Ikoonile hiirega liikudes kuvatakse teksti "Jagatud ainult lingiga".
- [x] Kõik kasutajad näevad kõikides otsingutes oma privaatsete kogumike kaartidel vastavat ikooni. Ikoonile hiirega liikudes kuvatakse teksti "Privaatne". 
- [x] Admin rolliga kasutajad näevad kõikides otsingutes oma privaatsete kogumike ja teiste  privaatsete kogumike kaartidel vastavat ikooni. Ikoonile hiirega liikudes kuvatakse teksti "Privaatne".
- [x] Kõik kasutajad näevad kõikides otsingutes oma lingiga jagatud kogumike kaartidel vastavat ikooni. Ikoonile hiirega liikudes kuvatakse teksti "Jagatud ainult lingiga".
- [x] Admin ja moderaatori rolliga kasutajad näevad kõikides otsingutes oma lingiga jagatud kogumike kaartidel vastavat ikooni. Ikoonile hiirega liikudes kuvatakse teksti "Jagatud ainult lingiga".
- [x] Privaatsuse ikoone on näha kogumiku detailvaates.

- [x] Visuaalne eristatus vastavalt https://paper.dropbox.com/doc/Andmetpide-ikoonid-sntoTc2mEjfB2kTIhXtKZ overlay peale asetatud kinnisel või lahtisel luku ikoonil (avalik kogumik seda ei oma)

**Comment by kokakoola** [comment]
Hetkel tehtud lingiga jagamine keti ikooniga. Seda on lihtne soovi korral muuta, aga meile endile tundub tänane ikoon kohane.
