### ISSUE TITLE
Taksonid vaskamenüüs

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#116]
Praegune joondus pikemate taksonite jaoks ebamõistlik ja sunnib nad mitmele reale, pakkuda lahendus paremaks paigutuseks

**Comment by kokakoola** [comment]
@erkkijakobson 
Ettpanek:
1. Esimese tasandi takson, see ikooniga, läheb aktiveerimisel boldiks (ehk kui on lahti)
2. Temale järgnev on trepitud nulli nagu Erkki soovis
3. Sealt järgnevad trepitakse md-paddingu võrra
4. Mingilt maalt tuleb treppimine pooleli jätta, sest puu on infinite sügavusega ja poleks alamatel tasanditel enam nähtav. Mis maalt, vaatame katse-eksituse meetodil (pakume et 3)
5. Pealkirjad kuvatakse nii pikalt kui nad on. Päris normaalne on kui pealkirja saab lugeda. Kui jätaks ühe rea ainult, siis oleks viide nagu nagu "Inimeste ja taimede..." mis on suhteliselt sisutühi.

**Comment by KailiAll** [comment]
@erkkijakobson 
Kas selline lahendus sobib?

**Comment by erkkijakobson** [comment]
vaja visuaali, eriti md-paddingu osas - kaugele läheb jm, kas nt   

(?) Alusharidus
(?) **Põhiharidus**
Keel ja kirjandus
..Eesti keel
....Kirjuamine
....*Ainsus ja mitmus*

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
