### ISSUE TITLE
Pop-up privaatse kogumiku nähtavuse muutmiseks jagamise nupul klikkimisel

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#118]
**Vajadus**
Kasutajalt on tarvis küsida luba privaatse kogumiku avalikuks või lingiga jagatavaks tegemiseks, sest muidu ta ei saaks privaatset kogumikku jagada.
**Tulem**
- [x] Kogumiku vaatamise vaates jagamise nupul vajutades avatakse pop-up, kui materjal on privaatne. 
- [x] Selles pop-upis on tekst stiilis "jagamiseks tee kogumik avalikuks või lingiga jagatavaks". Popupis on seega 2 radio nuppu ning all ääres paremal "Share" ja "Cancel".

**Comment by atatter** [comment]
@aivo0 kas see funktsionaalsus käib ainult kogumikku omava kasutaja kohta või see peaks toimima ka admini ja moderaatori (kas moderaator näeb üldse privaatseid kogumikke) jaoks

**Comment by KailiAll** [comment]
Erkki kommentaar: kasutaja jaoks peab flow olema kiire ja mugav alates privaatse kogumiku jagamisnupule vajutamisest kuni nt facebooki sissekande postitamiseni.

**Comment by KailiAll** [comment]
@erkkijakobson 
Palun vaata, kas nii on sobilik ja anna meile tagasiside.

**Comment by erkkijakobson** [comment]
mis on põhjus, miks kasutajalt lisaklikki nõuame valiku kinnitamiseks? ehk miks ei ole dialoogaknas vaid 3 nuppu?
1. tee kogumik avalikuks
2. muuda lingi abil avatavaks
3. tühista

**Comment by atatter** [comment]
Peale esimest valikut kontrollitakse kas backendis muutmine õnnestus ja õnnestumise korral tehakse teine nupp klikitavaks. Läbi javascripti ei saa kasutajat teisele lehele saata, kuna mitmed browserid blokeerivad popupid ära. Selleks on teisel nupul vajalik aadress olemas.

**Comment by erkkijakobson** [comment]
aadress oleks samuti eelmise kommentaari kahe esimese nupu taga lisaks käsule nähtavuse staatust muuta - miks kogumiku staatus backendis ette ära muuta, et seejärel tühista nupuga tagasi muuta?

**Comment by atatter** [comment]
Kui üks nupp teeks nii jagamist kui ka staatuse muutmist, siis võib tekkida olukord, kus staatuse muutmine ebaõnnestub ja kasutaja on oma kogumiku jagamisega edasi läinud.

**Comment by erkkijakobson** [comment]
see on ju ok, sest ebaõnnestumine tuleb mõlemal juhul backendis ära hallata: ühel juhul saab töövoo edukalt lõpetada selle asemel, et jääda kinni vaatesse, kus on näha mitteaktiivne nupp (kogesin seda)

ka praegu ei keela süsteem aadressiribalt kopeeritud privaatse kogumiku viida jagamist sotsiaalvõrku
