### ISSUE TITLE
Jagatava lingi hankimine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#119]
Näide Chrome Google Earth Pluginast (avaneb hoveri peale)
![image](https://cloud.githubusercontent.com/assets/16906555/20617727/c6a02f80-b2f3-11e6-8a44-ac0d859cc7ed.png)
![image](https://cloud.githubusercontent.com/assets/16906555/20617737/d43a4c5c-b2f3-11e6-815c-9021cd03343d.png)

**Comment by aivo0** [comment]
@erkkijakobson Kahjuks see lahendus ei tööta mobiilis. Sama probleem, nagu praegu on fab nupuga.

**Comment by erkkijakobson** [comment]
milles probleem avaldub? direktiivi kohaselt on hoveri asemel sõrmepuude ok ja nii me + juba töötab

**Comment by aivo0** [comment]
Probleem praeguse puhul on, et mobiilis peab nupul sekundi sõrme fab nupul peal hoidma, muidu alamvalikuid ei tule. Võiks olla nii, et kas klikid või hoiad sõrme peal, siis tulevad valikud.
Sama moodi siin lahendades enamik kasutajaid ei näeks kunagi jagamise valikuid - ainult oskaksid linki kopeerida.

**Comment by aivo0** [comment]
Sõltub tööst #137. Kui seal saab FAB nupu normaalselt toimima kõikide seadmete jaoks, siis on see siin kasutatav.

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
