### ISSUE TITLE
Toetatud platvormi filter

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#12]
**Vajadus:** kasutajal peab olema võimalus määrata otsitulemustes, millisel platvormil õppematerjale ta soovib näha
**Analüüs:** pakkuda välja ja rakendada filtri aluseks olevad EstCORE andmeväljad
**Tulemus:** kasutaja määrab, et soovib tulemustes näha õppevara, mis toimib nutiseadmetel (välistab nt flash-i) või nt välistab õppevara, mida ta oma op süsteemi pakkuja valiku tõttu avada ei saa (nt apple seadet nõudvad materjalid)

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
