### ISSUE TITLE
Huvitegevuse taksonoomia ikoon vasakmenüüsse

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#120]
taxon tabelis id=9

Huvitegevuse alla tulevad (infoks)
- kunst
- loodus
- muusika
- näitekunst
- sport
- tants
- teadus
- tehnoloogia
- üldkultuur

**Comment by kokakoola** [comment]
huvitegevus saab endale palleti, mis praegu on kutseharidusel ja kutseharidus saab mutrivõtme, ikoon build

**Comment by aivo0** [comment]
**Tulem**
- [ ] Huvitegevusele ikoon lisatud. Kutseharidusel mutrivõtme ikoon,
