### ISSUE TITLE
Tööriista riba lisamine kogumiku muutmise vaatesse

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#121]

**Comment by aivo0** [comment]
**Töö:**
Kogumikku muutev kasutaja saab kogumiku muutmise vaates kasutada tööriistariba, et lisada kogumikku uusi või juba e-Koolikotis olemasolevaid materjale, lisada alampeatükke või sisuteksti. 

See asendab praeguses lahenduses välja “e-Koolikoti välise materjali aadress” ja “Lisa materjal” ning “Lisa fail” nuppe. Ning ka uue peatüki lisamine toimuks edaspidi kogumiku all asetsevast nupust.

Sketšid uuest lahendusest:
![image](https://cloud.githubusercontent.com/assets/8111493/20665906/3c2b77dc-b56a-11e6-9c15-04b28a8a1a3a.png)
![image](https://cloud.githubusercontent.com/assets/8111493/20665935/6088b61c-b56a-11e6-9a9b-9b54b90527cd.png)
**Tulem:**
- [ ] Kogumiku muutmise vaates on tööriistariba iga peatüki alaosas.
- [ ] Kogumiku muutmise vaates on lehe allosas peatükki lisamise tööriistariba.
- [ ] Tööriistaribalt saab algatada uue materjali lisamise.
- [ ] Tööriistaribalt saab algatada e-Koolikotist materjalide otsimise.
- [ ] Tööriistaribalt saab lisada sisuteksti.
- [ ] Tööriistaribalt saab lisada alampeatüki.

**Comment by kokakoola** [comment]
@erkkijakobson @KailiAll @gglukmann 
Leitud UX probleem:
Kui kasutaja vajutab Lisa uus peatükk, siis praegu lisatakse uus peatükk, mille pealkiri on Uus peatükk ja see on musta värvi ja lõplik ja miski ei indikeeri, et seda nimetust saaks muuta.
Ettepanek täienduseks:
Peale Lisa uus peatükk vajutamist:
- [ ] Uus peatükk nimi on "Kirjuta siia uue peatüki pealkiri"
- [ ] Eelnimetatud tekst on placeholderi välimusega elik halli värvi
- [ ] Kursor on aktiveeritud pealkirja sisetamise real.

Vajab lisahindamist.

**Comment by KailiAll** [comment]
Sisuteksti osa vajab uut eraldi piletit.

**Comment by martlausNG** [comment]
#93 all on sisuteksti lisamine
