### ISSUE TITLE
Sisse logimisel avaneb vasakmenüüs Minu asjad, 2 punkt ei sulgu kunagi

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#122]

**Comment by aivo0** [comment]
**Tulemus** 
- [ ] Sisse logimisel avaneb vasakmenüüs Minu asjad
- [ ] Teine vasakmenüü punkt ("Õppekavad" või kogumiku peatükid) ei sulgu automaatselt kunagi. Hetkel sulgub nt abilehtedele minnes ja kogumikku muutes.
