### ISSUE TITLE
Kogumiku lisamise modaalakna muudatus

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#123]

**Comment by aivo0** [comment]
**Vajadus**
Kasutaja saab kogumikku luua järgnevat vormi kasutades, et uus kogumik lisada võimalikult lihtsalt:
![image](https://cloud.githubusercontent.com/assets/8111493/20700611/0a9ab27a-b617-11e6-9b44-6ba74ff5769e.png)
**Vastuvõtutingimused (muudatused võrreldes hetkeolukorraga)**

- [ ] Kohustuslikud andmeväljad on ülalpool (Pealkiri, Haridus, Vanus ja Ainevaldkond)
- [ ] Valida peab saama mitut vanuse kategooriat ja ainevaldkonda. Seotud taskiga #114 .
- [ ] “Kokkuvõte” pealkirja asemel kasutatakse “Kogumiku kirjeldus”
- [ ] “Kogumiku kirjeldus” blokk on tõstetud vormil allapoole “Haridus” ja “Vanus” blokke ning tekstisisestamise lahter ei ole vaikimisi avatud. “Kogumiku kirjeldus” juures on noole sümbol, mille vajutamise korral avaneb teksti sisestamise lahter.
- [ ] Märksõnade sisestamine on antud põhiandmete vormilt eemaldatud - Enteri vajutamine ei ole kasutajate jaoks loomulik sellises situatsioonis ja tekitab pigem olukordi kus märksõnu ei lisata või nende lisamiseni jõudes jäetakse tegevus pooleli.
- [ ] “Katkesta” nupu värv on helehall. “Loo kogumik” nupp vaikimisi tumehall ja kohustuslike väljade täitumisel muutub süsteemselt siniseks.
- [ ] Kui Hariduse ja Ainevaldkonna all on ka Teema ja Alamteema, siis nende valiku peale peab tekkima ka hallikas toonis pealkiri (kasutajale muidu ebaselge, kas tegemist kohustusliku või mitte-kohustusliku väljaga)
