### ISSUE TITLE
Materjali lisamise modaali täiendus

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#126]
**Vajadus**
Põhilised murekohad:
Materjali kohustuslikud väljad võiksid olla esimesel vahelehel. 
Kirjelduse kast võtab liiga palju ruumi.
Mitmes keeles kirjelduse lisamine võiks olla paremini lahendatud.

Samas võiks jääda 3 vahelehte - ühele kõikide väljade paigutamine teeb vormi liiga pikaks.

**Comment by martlausNG** [comment]
See on ainult disaini ja UX task.

**Comment by kokakoola** [comment]
Palun loetleda kõik materjali kohustuslikud väljad

**Comment by martlausNG** [comment]
See task peab ära lahendama soovid #61 ja #95.

**Comment by kokakoola** [comment]
Loetelu tuvastatud kohustuslikest väljadest:
- Materjali link või fail (file upload, input)
- Materjali keel (eeldefineeritud select)
- Materjali pealkiri (input)
- Pealkirja ja kirjeduse keel (eeldefineeritud select)
- Haridustase + ainevaldkond (select) + Teema (vabatahtlik, select)  1 kuni mitu
- Vanus (select)
- Üldpädevused (chip, autocomplete)
- Läbivad teemad (chip, autocomplete)
- Autori eesnimi (Input) või Väljaandja (Input)
- Autori perenimi (Input)

Vabatahtlikud väljad: 
- Pilt (file upload)
- Kirjeldus (wysiwyg textarea) 1 kuni mitu keelt
- Tüüp (multiselect)
- Lihtsustatud õppekava (checkbox)
- Märksõna (chip, autocomplete)
- retsensioon (input, file upload)
- kuupäev (kalender)
- litsentsi tüüp (select)
- tasuline (checkbox)

NB, blokeerijad ja takistajad: 
- Eesnime abitekstisa öeldakse et "Väljaandja või autor on kohustuslik", järgmine väli on Perenimi, mis on kohustuslik - väljaandjal ei pruugi olla perenime kui see on nt kirjastus.
- kui oled lisanud mitu keelt esimesse tabi, ei näe enam teiste tabide päiseid/veateadet sellel, sest vaade on pikk ja päis on fixed positioniga.
- wysiwygi ikoonid pole iseseletuvad, vajavad tooltippe.

**Comment by kokakoola** [comment]
@erkkijakobson  Kui materjalile on lisatud fail, ei ole praeguses versioonis võimalik seda ümber muuta lingiks. Kas see on oodatav käitumine?

**Comment by kokakoola** [comment]
@erkkijakobson @aivo0  mis tüüpi on retsensioon? fail upload on loogiline, aga see input - kas on mõeldud et sinna kirjutatakse retsensioon? samas mis siis on Kirjeldus?

**Comment by erkkijakobson** [comment]
- faili peab saama kustutada, nt X abil, misjärel saad jälle valida kas fail või link
- retsensioon on nt BDOC vormingus, või on selle asemel link retsentsioonile kirjastuse lehel

**Comment by kokakoola** [comment]
Kaasnev arendusvajadus:
- Võtmesõnade eemaldamine detailvaatest

**Comment by KailiAll** [comment]
**Tulem**
![image](https://cloud.githubusercontent.com/assets/19947450/22101585/bc246f7a-de3c-11e6-8204-06949855bf2a.png)
