### ISSUE TITLE
Illustreeriva faili lisamine kogumikku

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#127]
**Vajadus**
Peab saama lisada kogumikule faile, mis ei lähe materjaliks.

**Comment by aivo0** [comment]
@erkkijakobson Siin oleks vaja ära piiritleda, mis meedia tüübid (kas ainult pildid ja ainult video) ja mis faili suurused on siin lubatud. Ja mis suurustega kasutaja neid siis näeb (kogumiku muutmise vaates ja hiljem kogumiku detailvaates). Samuti, kas vaja piltide lõikamist seal. Ja kas (nagu materjalide puhul) peaks taustal genereerima ka väiksemaid pilte.
Soovitame levinumaid pildiformaate: jpg, png, gif. 
See task vajab ka taski #129 sisendit.

**Comment by aivo0** [comment]
Ootab @erkkijakobson tagasisidet, et kas siin saame ära piiritleda, et illustreerivad failid on pildid. 
Siis on visioon, et neid pilte saab lisada kogumikku samamoodi, kui materjale ja tekste.

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
