### ISSUE TITLE
Teate näitamine kogumiku muutmisel materjale otsides

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#128]
**Vajadus**
Kasutaja scrollimine lehe ülaosasse, ükskõik, kas kasutaja alustab edit vaates liht- või detailotsingut
Otsiriba placeholder on muutmise režiimis 'Otsi siit materjale sellesse kogumikku'

**Comment by aivo0** [comment]
Eeldab taski #103.

**Comment by aivo0** [comment]
**Vajadus**
Kui kasutaja on kogumiku vaates ja hakkab valib uue materjali lisamise e-Koolikotist, siis kasutaja suunatakse materjalide otsingu vormile, kusjuures vorm on keritud ülesse ja otsiriba _placeholder_ tekst on "Otsi siit materjale sellesse kogumikku".
**Tulem**
- [ ] Kogumiku muutmise vaatest e-Koolikotist materjali lisama asudes on vorm keritud ülesse ja otsiriba _placeholder_ tekst on "Otsi siit materjale sellesse kogumikku".

**Comment by KailiAll** [comment]
Erkki kommentaar: 
#128 kerimist ei ole ju vaja kuna meil on floativ päiseriba, samuti peaksime oskama avanevat täpse otsingu kasti #117 tulemusel üles kerimata näidata
