### ISSUE TITLE
Uuendatud kogumiku vaate disain (muutmise vaatest ja view vaatest)

### ISSUE THREAD

**Issue by aivo0** [hariduspilv/koolikott#129]
**Vajadus**
Teha korrektne disain, kuidas näeb välja paigutus, materjalide ja tekstikastide ümber tõstmine (drag and drop & layout). 
**Tulemus**
- [ ] Disain on tehtud.

**Comment by martlausNG** [comment]
Disain selle jaoks, kuidas näevad välja kõrvuti paiknevad materjalid ja sisutekstid. Ühtlasi ka kuidas näeb välja kogu kogumik ühtse tükina.

**Comment by KailiAll** [comment]
Tulem saadetud meiliga ja tutvustatud koosolekul Erkkile.
