### ISSUE TITLE
Õppevara lingi indekseerimine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#131]
- [x] võimaldada otsida linki: nt sisestades otsingusse 'youtube' kuvatakse kõiki materjale sellelt lingilt
- [x] vältida suggest-as-you-type spämmi sama domeeninime linkide kohta: nt et sisestades 'you....' oleks soovitustes 'youtube' või 'youtube.com' üksi koos teiste tänaste soovitustega, mitte ainult:
  - youtube.com/watch?v=bgucOpFQwzc
  - youtube.com/watch?v=.....
  - youtube.com/watch?v=.....

**Comment by aivo0** [comment]
**Lahendus**
Indekseerime ühest lingist mitu tükki (nt Youtube, Youtube.com, Koolitaja, Koolitaja.eenet.ee jne).
