### ISSUE TITLE
Soovitava otsingu seiskamine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#132]
Täna ei ole võimalik suggesterist lihtsalt (visuaalselt) väljuda, et teostada otsing enda valitud fraasile:
* enter teostab poole sõna pealt esimese süsteemi poolt soovitatud fraasi põhjal otsingu
* backspace lühendab otsingut tähemärgi võrra, püsib eelmine olukord (soovituste list on näha)
* escape tühistab otsingu (korrektne käitumine, lihtsalt viimases hädas vajutab kasutaja ka seda)

Chrome on lahendanud selle juba külastatud linke otsides arusaadavamalt:
- [x] esimene soovitatud fraas, mida enter otsib on lisaks ka otsiribal endal kuvatud highlight olekus
- [x] backspace kustutab selle highlighti ja lubab enteri abil vaid kasutaja sisestatud fraasi otsida
- [x] kui peale backspace'i vajutada enteri asemel järgmist soovituse tähte, tuleb see highlight tagasi

**Comment by aivo0** [comment]
**Vajadus**
Õppevarade otsingus peab saama otsitermini valimata jätta, mida süsteem soovitab. Seega soovitused ei tohi olla vaikimisi valitud. Jäljendada võib siin Google.ee-d (mitte Chrome-i), kui soovitusi saab valida,  kuid pole kohustust.
Ja soovituse valimisel peaks muutuma otsingukasti sisestatud tekst (sama juhtub ka Google's)
**Tulem**
- [ ] e-Koolikoti põhiotsingusse teksti sisestamisel soovitused pole automaatselt valitud. Ja 'enter' klahvi vajutamisel seega soovitused sulguvad ja otsingu tulemused on ainult vastavalt sisestatud tekstile.
- [ ] Otsingu soovituse valimisel muutub otsingulahtrisse sisestatud tekst.

**Comment by erkkijakobson** [comment]
@RannarA ettesoovitatud tekstist peab saama mööduda, tüüpiliselt edasi noolega, tabulaatoriga
kasutajaliides ei tohiks hanguda normaalse trükikiiruse juures - hetkel tekib lag peale paari tähte
