### ISSUE TITLE
RequireJS väljavõtmine

### ISSUE THREAD

**Issue by gglukmann** [hariduspilv/koolikott#134]
Praegu laetakse alguses väga suur requireJS fail, mis teeb lehe laadimise väga aeglaseks. Vahetaks require välja, mis võimaldab meil kasutada angulari enda moodulite laadimist. Sellega oleks meil tulevikus lihtsam ka minna angular 2 peale. Eelduseks on #133, mille tulemusena me ei peaks enam js bundleid tegema.

**Comment by aivo0** [comment]
- [ ] requireJS-i enam ei laeta ja lahendus jääb tööle.
