### ISSUE TITLE
Kogumike võtmesõnade eemaldamine

### ISSUE THREAD

**Issue by aivo0** [hariduspilv/koolikott#135]
**Vajadus**
Kogumikele lisatud võtmesõnasid peab kasutaja saama eemaldada. See võimalus kadus kogumiku lisamise/muutmise modaali ümber tegemisega. 
Võtmesõnad peaksid eemaldatavad olema ainult kogumiku muutmise vaates.
**Tulem**
- [x] Kogumiku muutmise vaates on iga võtmesõna kohta eemaldamise ikoon.
- [x] Kasutaja, kes saab kogumikku muuta, saab ka kogumikult võtmesõnasid eemaldada.

**Comment by KailiAll** [comment]
Erkki kommentaar:
#135 nagu varsemalt, siis lisaks autorile saab võtmesõnu eemaldada ka admin ja aineekspert

Sellega oleme arvestanud.
