### ISSUE TITLE
Murdepunktide korrastamine

### ISSUE THREAD

**Issue by aivo0** [hariduspilv/koolikott#136]
**Vajadus**
e-Koolikoti murdepunktide loogika vajab ühtlustamist. Inspiratsiooniks [Contacts](https://contacts.google.com), [Inbox](https://inbox.google.com), [Keep](https://keep.google.com), [Plus](https://plus.google.com)

**Tulem**
- [ ] Murdepunktid on viidud [Angular Flex Layout](https://github.com/angular/flex-layout) raamistikule (esmalt töötada läbi sealne README)
- [ ] Sisuosa flex on defineeritud portaali tasandil (täna omab iga vaade/leht eraldi sisuosa suurust)
- [ ] Murdepunktidel kuvatavas on kokku lepitud (nt iPad lapiti omab nähtavat menüüd, püsti mitte; mobiilne seade ei paku sisselogimisvahendina ID-kaarti jne)
- [ ] Murdepunktid on realiseeritud

**Comment by erkisisask** [comment]
Vt ka #297

**Comment by erkisisask** [comment]
Osaliselt tarnitud MS14 tarnepakiga (rakenduse versioon 1.15.0) 07.02.2018a. Tööd taskiga jätkuvad edasistes sprintides.

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
