### ISSUE TITLE
Pluss nupu (FAB nupu) täiendamine

### ISSUE THREAD

**Issue by aivo0** [hariduspilv/koolikott#137]
**Vajadus**
Pluss nupp _(floating action button)_ e-Koolikoti alumises paremas nurgas peab olema ka mobiilis hästi kasutatav. See tähendab, et kasutaja peaks intuitiivselt pääsema ligi selle nupu alamvalikutele, mis hetkel avanevad mobiilis ainult teatud aja nupul näppu hoides. 
Selle lahendamiseks võib vaja olla, et nupp toimib PC-l ja mobiilsetes seadmetes erinevalt. Aga üldine loogika võiks toimida nii:
Pluss nupule lisandub animatsioon, mille jooksul nupp ei ole klikitav/vajutatav. Selle ajaga ilmuvad kasutaja jaoks alamvalikud. Alates animatsiooni lõpust on pluss nupp ise kui ka kõik alamvalikud klikiga valitavad.
Animatsioon tekib PC seadmel hiirega peale liikumisel, mobiilsel seadmel näpuga peale liikumisel.

**Tulem**
- [x] Nupp ise on lilla asemel roosaka alatooniga punane
- [x] Animatsioon on lisatud: pluss märk muutub pliiatsiks
- [x] Mobiilis avaneb pluss nupp puutega, PC-l avaneb nii hoveri kui ka klikiga.
- [x] Nupp pole klikitav/vajutatav animatsiooni ennem, kui alamvalikud on avanenud
- [x] Kui alamvalikud on avanenud, siis saab klikkida nii nupule endale kui ka alamvalikutele. 
![20161212_143859](https://cloud.githubusercontent.com/assets/19947450/21100032/6c9a3294-c07a-11e6-97a5-3f0492fb5351.jpg)

**Comment by kokakoola** [comment]
Mõistlik lahendus on:
1. klikiga ja see töötab mobiilis ja desktopil ühtviisi.
2. suur FAB ise avab menüü - nagu dropdown - ja ise ei tee rohkem midagi. Avaneva menüü väiksed FABid kannavad funktsionaalsust.
3. Sama loogika laieneb kõigile FABidele üle rakenduse (nt Share, #119 )

**Comment by kokakoola** [comment]
Praegu tegin muutuse kogumiku ikooni, mitte pliiatsi peale

**Comment by erkkijakobson** [comment]
[*Make floating action buttons positive actions like Create, Favorite, Share, Navigate, and Explore.*](https://material.io/guidelines/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button)
Toodanguversioon täidab direktiivi, arenduskeskkonnas pole hektel kumbki ikoon positiivne tegevus

Issue ilmselt veel WIP, mistõttu ka nupu värv ei paista hetkel korrektne: (+) on pigem oražikas, mille järgsed 2 lillat nupu ei näikse minevat kuidagi kokku väikse kaardi vaiketaustadega (sinine kogumiku taust  vs lilla kogumiku nupp; valdavalt rohelistes toonides materjalide taust vs lilla lisamise nupp)

ka animatsioon ilmselt WIP staatuse tõttu keerleb hetkel kauem, kui esitletud Paperi prototüübis
