### ISSUE TITLE
Teistes keeltes tõlke puudumisel eestikeelse väärtuse kuvamine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#139]
**Täna:** kui *translationGroup 2* või *3* jaoks on puudu *translation* siis kuvatakse kasutajale *translationKey*
**Vajadus:** kirjeldatud juhul kuvatakse kasutajale *translationGroup 1 translation* (ehk eestikeelne tõlge)

**Comment by aivo0** [comment]
**Tulem**
- [ ] Kui kasutaja keeles tõlge on puudu, siis kuvatakse eesti keelne tõlge.

**Comment by erkisisask** [comment]
Viimase aastaga on jooksvate arenduste jooksul päris palju juba ära tehtud seda. Vajab kaardistamist, palju selliseid kohti veel järel on.

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
