### ISSUE TITLE
Educloud metaandmete korje

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#14]
- [ ] pakkuda lahendus Educloud Basaari metaandmete korje realiseerimisks
- [ ] kirjeldada vajalikud muudatused andmete küsimiseks ECA süsteemilt

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
