### ISSUE TITLE
Peale tuleva vasakmenüü „tagasi“ nupu animeerimine nooleks

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#140]
Täna on menüü ikoon vasakul ja kitsal ekraanil pealetuleva vasakmenüü tagasinool paremal pool logo
Vaja, et pealetuleva vasakmenüü tagasinool oleks samuti logost vasakul, animeeruks tagasinooleks

![20161212_143903](https://cloud.githubusercontent.com/assets/19947450/21100062/a1f1619c-c07a-11e6-8599-c1ac35b3ff74.jpg)

**Comment by aivo0** [comment]
**Tulem**
- [ ] Kogumiku muutmisel otsides muutub menüü ikoon nooleks.

**Comment by atatter** [comment]
Pole ühtegi kohta kus animatsiooni rakendada

**Comment by erkkijakobson** [comment]
tagasinoole asukohta saab rakendada nt pealetulevale menüüle, animatsiooni ennast nt matejali valimisel

**Comment by aivo0** [comment]
@erkkijakobson Me räägime onju peale tulevast valgest ribast. Kas animatsioon võiks olla see, et valge riba tuleb animeeritult? Tagasi noolekese animeerimist ei kujuta ette, sest seda esialgsel sinisel ribal pole. Kui materjal märgistada, siis ilmub valge riba ja seal on kohe siis ka tagasi nooleke.

**Comment by KailiAll** [comment]
Erkki kommentaar: #140 tulem on halvasti sõnastatud  - alustame ikka Issues küsitud juhtudest kus vasakmenüü tuleb ekraanile peale, seejärel muud juhud kus koolm triipu asenduvad tagasinoolega.

**Comment by KailiAll** [comment]
@erkkijakobson 
Palun täpsusta githubi enda soov lahti.
Meie hinnangul ei ole seal midagi animeerida.

**Comment by erkkijakobson** [comment]
sinisel ribal on kolm triipu: kui sinine riba värvub valgeks, animeeruvad need kolm triipu inplace nooleks

**Comment by gglukmann** [comment]
@erkkijakobson @KailiAll Seal on kaks täiesti erinevat ikooni erinevates kohtades, seal pole midagi animeerida. Valge menüü tuleb sinise peale, mitte sinine ei muutu valgeks. Kui soovi on siis võib seda animatsiooni parandada, et oleks paremini aru saadav. Inboxis ei animeeru see ka, meil on täpselt sama moodi tehtud.

**Comment by erkkijakobson** [comment]
@gglukmann selge, arvasin et päis vahetab värvi.
