### ISSUE TITLE
Mobiilivaate täiendused

### ISSUE THREAD

**Issue by aivo0** [hariduspilv/koolikott#141]
**Vajadus**

- [x] Esilehel sorteerimise nupp pealkirja kõrvale.

- [x] Mobiilivaates pole näha detailotsingut, näha on ainult otsiriba, mis katab ära kogu headeri. Pärast otsingu teostamist jääb riba alles, kus on otsitud sõna. Ribale tekib X (sulgemise) nupp ja back nupp, mis tühistab otsingu.

Sõltub taski #90 täiendusest.

**Comment by gglukmann** [comment]
@kokakoola ettepanek võtta pealkiri ära
