### ISSUE TITLE
Soovituse loogika paremmenüüle

### ISSUE THREAD

**Issue by aivo0** [hariduspilv/koolikott#143]
**Vajadus**
Vaja soovitamise loogikat, kasutades taksonoomiat, silte, vanust ja üldpädevusi ja läbivaid teemasid. 
Seotud selle kuvamisega: #84.
**Tulem**
- [x] Paremmenüül kuvatakse pisikaarte sõltuvalt taksonoomiast (puudutab kogumiku muutmise vaadet ja kogumike detailvaadet).

**Comment by aivo0** [comment]
@kokakoola Kas pisipilte kuvatakse ka materjalide detailvaates?

**Comment by kokakoola** [comment]
jah

**Comment by KailiAll** [comment]
**Tulemus:**
- [ ] Materjalid on järjekorras.
- [ ] Järjekord on loogika põhine ja nende põhjal tehakse otsing. Nelja välja (taksonoomia, tagid, vanus, üldpädevused ja läbivad teemad) põhjal teostatakse otsing.
