### ISSUE TITLE
Õpiväljundid teenusena välistele süsteemidele

### ISSUE THREAD

**Issue by aivo0** [hariduspilv/koolikott#145]
**Vajadus**
Väljundite sidumine õppekavaga peab toimima ka teenusena välisele süsteemile, liidese spec wikisse.
Eeldab #11.
**Tulem**
- [ ] Õpiväljundid on lisatud e-Koolikoti avalikku teenusesse. 
- [ ] Kogu liides, sh õpiväljundid on Wikis dokumenteeritud.

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati tõsta see töö e-Koolikoti Confluence'i analüüsi backlogi.
