### ISSUE TITLE
Sotsiaalvõrku jagamisel sisu puudu

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#149]
![image](https://cloud.githubusercontent.com/assets/16906555/21309945/f3036d5a-c5e8-11e6-9175-75498eced6d3.png)

esineb facebooki ja google+ postitusi tehes, twitteriga ei ole testinud, emaili jagamisel ei esine

**Comment by erkkijakobson** [comment]
G+ kuvab nüüd veel vähem metaandmeid kui v1.6.0, materjali pildi asemel on **animeeritud** preloader:
![image](https://cloud.githubusercontent.com/assets/16906555/21501536/72c89100-cc51-11e6-9b7c-0c046603302f.png)
(sisutühi tulem ei erine kas postitada läbi jagamisnupu või asetada ise materjali link uude postitusse)

FB kuvab ise linki uude postitusse asetades puudulikult pealkirja ja kirjelduse, pilt puudu:
![image](https://cloud.githubusercontent.com/assets/16906555/21501624/01762502-cc52-11e6-8bdd-3b75ba62aabd.png)

FB kuvab materjali jagamise nuppu vajutades veateate:
![image](https://cloud.githubusercontent.com/assets/16906555/21501403/4b1a0c7a-cc50-11e6-9056-744e9df33d45.png)

Twitteri ja e-posti nupu alt jagamine korras

**Comment by erkkijakobson** [comment]
Saime FB veateatest lahti - uuendasin eelmise kommentaari ekraanitõmmist (pilt ja kirjeldus puudu)

Lisaks tuvastasime FFga veaolukorra kus jagamisnupujärgne popup sulgub ise kohe enne FB avamist
Teatud materjalide puhul seda viga esine - või on selle juhtumise sagedus ette prognoosimatu

**Comment by KailiAll** [comment]
@erkkijakobson 
palun default pilti, mida näidata juhul, kui materjalil/kogumikul pilti ei ole

**Comment by KailiAll** [comment]
@erkkijakobson 
Palun testi LIVEs

**Comment by kokakoola** [comment]
![logo_koolikott](https://cloud.githubusercontent.com/assets/672595/21763468/b6d471ec-d666-11e6-9928-4dffb09f349d.png)

**Comment by erkkijakobson** [comment]
Pilt sobib, toodangus testimine:
G+ puudu õppevara pilt, pealkiri, kirjeldus (nii jagamisnupu alt kui linki uude postirusse kopeerimisel)
FB puudu õppevara pilt, õppevara pealkirja ja kirjelduse asemel kuvab saidi metat (lingi kopeerimisel)
FB jagamisnupp annab enamikes detailvaadetes vea https://www.facebook.com/dialog/return/close?error_code=100&error_message=picture+should+represent+a+valid+URL#_=_

**Comment by gglukmann** [comment]
G+ peab ilmselt siis ka APIga tegema
FB lingi kopeerimisel ta kasutab defaulti jah, sellest ma olengi rääkinud, et kuna meil on angular siis facebook ei saa aru, kui meta tagidest ning alguses jäi ainult {{$root.name}} näha. Sellepärast ma tegin fallbackiks default tekstid ja pildi. Selleks, et lingi kopeerimisel tööle saada, peaks hakkama serveri poolt lehti serveerima. (sama ka G+ puhul)

**Comment by gglukmann** [comment]
FB jagamisnupu viga tuleneb sellest, et meil on piltide urlid: https://oxygen.netgroupdigital.com/rest/picture/thumbnail/lg_xs/a7ef921b3c4a1542366f93947178fc8c5c563e05 ja need pole FB jaoks valiidsed, peaks olema *.png või *.jpg vms

**Comment by gglukmann** [comment]
mul oleks vaja google share clientID'd (.... .apps.googleusercontent.com)
