### ISSUE TITLE
Automaatne OAI-PMH sünkroniseerimine ei tööta

### ISSUE THREAD

**Issue by martlausNG** [hariduspilv/koolikott#15]
Töötab kui teha restart.

**Comment by erkkijakobson** [comment]
testimiseks #62

**Comment by erkkijakobson** [comment]
viga endiselt üleval nt https://koolielu.ee/waramu/view/1-a5d1476d-a7d9-4a4b-b40f-92bee1a23bf9 ei ole jõudnud iseseisvalt toodangusse. Testkeskkonda saime alles täna vaid peale rakenduse restarti. Arenduskeskkonnas on olemas sellepärast et sinna tehakse pidevalt restarte.

**Comment by KailiAll** [comment]
Palun saada logid.
