### ISSUE TITLE
Täpse otsingu metaväljad kadunud

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#150]
![image](https://cloud.githubusercontent.com/assets/16906555/21316184/42439682-c608-11e6-9476-57f6138a0744.png)

Läbivad teemad, üldpädevused, õppekirjandus, lihtsutatud õppekava jm väljad ei tule enam nähtavale

**Comment by KailiAll** [comment]
Viga on parandatud.
![image](https://cloud.githubusercontent.com/assets/19947450/21500059/c3d01662-cc43-11e6-9887-e5e4b71556c2.png)
