### ISSUE TITLE
Otsitulemusi ei kuvata - infinite scroll ei toimi

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#151]
uhd ekraanilaiusel ei käivitu infinite scroll - 573st otsitulemusest kuvatakse vaid 24 - rohkemat ei näe, avalehel kuvatakse materialboxe 1 rida veel vähem ja samuti rohkemat süsteem ei näita
![image](https://cloud.githubusercontent.com/assets/16906555/21421150/00dcef20-c83a-11e6-863c-09e8ef51e720.png)

**Comment by KailiAll** [comment]
@erkkijakobson mis monitoris viga on?

**Comment by gglukmann** [comment]
@erkkijakobson meil on xl suuruse fix eraldi taskina kirjas.

**Comment by erkkijakobson** [comment]
@KailiAll viga ei ole riistvaraline
@gglukmann nii on tõesti - lausa 2 tk - muutsin käesoleva Issue sõnastust
