### ISSUE TITLE
Eemaldada teavituse dialoog avaliku kogumiku muutmisel

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#152]
![image](https://cloud.githubusercontent.com/assets/16906555/21428711/113550ea-c864-11e6-8231-f975b7562c0e.png)

**Comment by KailiAll** [comment]
Kogumiku pakkumusse lisatud info:

Kasutaja suunamine kogumiku jagamisele  
1 Kasutajatel on täna võimalik enda kogumik muuta privaatseks või avalikuks - kasutades kogumise muutmise vaates “silma” ikooni. a muutes kogumiku avalikuks tehakse see nähtavaks e-Koolikoti siseselt teistele kasutajatele (autenditud ja autentimata) 2 Lisaks on kogumiku omanikul võimalik pärast muudatuste kinnitamist (pärast seda, kui on klikkinud “kinnita ja välju” nuppu) kogumiku sisemenüüst kopeerida otselink kogumikule.   
**Ettepanekud:** 
Kui kasutaja vajutab kogumiku muutmise vaates “kinnita ja välju” nuppu, siis kuvatakse talle hüpikaken valikutega: „Välju ja tee avalikuks“ ning „Välju avalikuks tegemata“.

**Comment by KailiAll** [comment]
**Enne muudatust:**
Avan minu kogumiku (avalik)
Klikin kolme täpi menüü - ja klikin "Muuda kogumikku"
Kuvati teavitusaken
![image](https://cloud.githubusercontent.com/assets/19947450/21500963/9e74e51a-cc4c-11e6-8b9e-debb7afafbcd.png)

**Pärast muudatust:**
Avan minu kogumiku (avalik)
Klikin kolme täpi menüü - ja klikin "Muuda kogumikku"
Teavitust ei kuvata.

@erkkijakobson 
Kas nii sobib?

**Comment by erkkijakobson** [comment]
@KailiAll kogumiku pakkumuse ettepanek jäi tööst välja, kuna oli oht igakordselt kasutajat spämmida
selle Issue lahendus visuaalselt ok - dialoogakent kogumikku muutmiseks avades ei näita enam üldse
