### ISSUE TITLE
Valge päise tagasinupp logo asemel

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#153]
1. muuda kogumikku
2. otsi materjale otsiribalt
3. linnuta materjal
4. vajuta päisel tagasi

![image](https://cloud.githubusercontent.com/assets/16906555/21428906/09d3312c-c865-11e6-8e0b-4c89ca8364a3.png)

**Comment by gglukmann** [comment]
@erkkijakobson mis selle taskiga mõeldud on?

**Comment by KailiAll** [comment]
Lahendus
1. muuda kogumikku (päis värvus lillaks)
2. otsi materjale otsiribalt (päis on lilla)
3. linnuta materjal (päis läks valgeks)
![image](https://cloud.githubusercontent.com/assets/19947450/21451850/16b4e948-c90b-11e6-827f-682fc6bce5a2.png)
5. vajuta päisel tühista (TÜHISTA- tühistab linnutatud valiku)
6. liigud tagasi vaatesse, kust otsisid otsinguribalt materjale (päis on lilla) ja seal on ka tagasi nupp
![image](https://cloud.githubusercontent.com/assets/19947450/21451923/a85c055c-c90b-11e6-92fd-23f131233daf.png)

**Comment by KailiAll** [comment]
@erkkijakobson 
Päisel tekib valge riba peale Tühista, mis tühistab esmalt linnutatud valiku ja seejärel tekib sinna tagasi nupp.
Need on kaks erineva funktsionaalsusega nuppu ja tegemist ei ole veaga.
