### ISSUE TITLE
Haridustaseme valikmenüü muudatused

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#154]
- [x]  Nii materjali kui ka kogumiku loomise modaalis võtakse ära Educational contextil ja Domainil valikud "Kõik". 
- [x] Samas nad jäävad alles otsingusse. 
- [x] Materjali ja kogumiku lisamisel on kohustuslik lisada Educational context ja Domain (täna materjalil see pole kohustuslik, kogumikul on).

**Comment by erkkijakobson** [comment]
valikut 'Kõik' ei tohi olla: kohustuslik valida educationalContext - sama peab kehtima ka materjali lisades
