### ISSUE TITLE
Favikoon korda

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#158]
Peaks kujutama luupi, aga sakilisuse tõttu paistab pigem ketassaena - võrdluseks telia.ee vs emt.ee
![image](https://cloud.githubusercontent.com/assets/16906555/21586566/27162e78-d0db-11e6-85e6-016a9bf9e121.png)

Lisada ka täna puuduolevad vormingud, et järgnev test näitaks vaid rohelist:
https://realfavicongenerator.net/favicon_checker?protocol=http&site=e-koolikott.ee

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
