### ISSUE TITLE
UX analüüsi läbiviimine, user flowde kirjutamine ja wikisse analüüsi sektsiooni loomine

### ISSUE THREAD

**Issue by martlausNG** [hariduspilv/koolikott#16]
Mare eestvedamisel.
- [ ] UX analüüs
- [ ] User flowd - Wikisse
- [ ] Wiki alapeatüki loomine UX/UI probleemide ja lahenduste kohta

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
