### ISSUE TITLE
Tuuri sisu loomine

### ISSUE THREAD

**Issue by kokakoola** [hariduspilv/koolikott#163]
Eelduseks on #54, tuuri lisamine. Siin määratakse 
- elemendid, mida tuur läbib
- järjekord 
- sisu
iga lehe kohta eraldi.

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
