### ISSUE TITLE
Juhendid uutele kasutajatele

### ISSUE THREAD

**Issue by kokakoola** [hariduspilv/koolikott#164]
Esimest korda Minu asjades näidatakse igal alamlehel tervitusjuhendit, mis
a) täidab praeguse tühja lehe
b) juhatab, mida seal teha saab
c) seab reeglid, mida teha võib
Juhendit näidatakse juhul, kui kasutajal ei ole ühtki Materjali/Kogumikku/Lemmikut

**Comment by kokakoola** [comment]
Juhend sisaldab:
- seletus, mis juhul kasutada Kogumikku, mis juhul Materjali
- soovitus tekstisisestuse korral wordist asju mitte otse üle kopeerida või võtta eelnevalt wordi stiilid maha, juhend siin: https://support.office.com/en-us/article/Clear-formatting-199d9ab5-727d-4ab8-8c87-ccc641da4f35

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati tõsta see töö e-Koolikoti Confluence'i analüüsi backlogi.
