### ISSUE TITLE
Otsing ei toimi enam

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#171]
[ ] lihtotsingus annab iga otsisõna nüüd tuhandeid vasteid, milles otsitu ei sisaldu
[ ] detailvaates autorile klikkimine annab samuti tuhandeid vasteid, milles otsitu (autor) ei sisaldu

**Comment by erkkijakobson** [comment]
autori otsing annab endiselt valesid vasteid, küll mitte enam tuhandeid aga siiski, nt:
https://oxygen.netgroupdigital.com/search/result?q=author:%22Chef%20%20Jeff%22&type=all

**Comment by KailiAll** [comment]
@erkkijakobson
Kas viga seisneb sellest, et kui otsida autori järgi, siis tuleb ka teiste autorite vasteid?

**Comment by erkkijakobson** [comment]
Seisnes - arenduskeskkonnas paistab materjali autoril klikkides otsing nüüd korras olevat.

Küll aga on veel kõigis keskkondades katki kogumiku autori otsing: klikk autoril viib lihtsalt avalehele

**Comment by erkkijakobson** [comment]
näide: https://e-koolikott.ee/search/result?q=leekreaktsioon&type=all
esimesed 9 on relevantsed, ülejäänud 13 otsitulemust otsitut ei sisalda

**Comment by KailiAll** [comment]
Kogumikul ei ole sellist asja nagu autori järgi otsing ja samuti puudub selline asi ka materjali puhul publisheri ja lisaja jaoks.

Kogumike ja materjalide lisajate/väljastajate peal klikkimine viib lehele, kus on välja toodud selle kasutaja poolt lisatud materjalid/kogumikud. See pole otseselt otsing, sest sinna hulka võib tulla ka asju mis on lisatud näiteks Mati Maasika poolt, aga mille autor on kalle kaalikas (tundub et see on funktsionaalsus mis kehtib ainult sisse loginud kasutajatele)

Kogumike puhul puuduvad otseselt sellised asjad nagu "autor", mis tähendab, et täpselt sellist käitumist nagu on materjalidel ei saa oodata. Otseses mõttes autori järgi otsing saab toimuda ainult selliste materjalide puhul, millel on lisamisel ära täidetud autori väljad. Kogumikel selline väli üldse puudub.

**Comment by KailiAll** [comment]
@erkkijakobson 
Kas me teeme parandustarne ära?

**Comment by erkkijakobson** [comment]
https://oxygen.netgroupdigital.com/search/result?q=leekreaktsioon&type=all ei toimi veel korrektselt

**Comment by KailiAll** [comment]
@erkkijakobson 
Palun täpsusta, miks see ei toimi?
Meil oli selline arendusülesanne, mis sai ka realiseeritud:
https://github.com/hariduspilv/koolikott/issues/131

**Comment by AllarVi** [comment]
@erkkijakobson, @KailiAll  
Otsingusõna "leekreaktsioon" puhul on kõik otsingutulemused vähemalt osaliselt
relevantsed, sest tulemustes sisalduvas materjali aadressis sisaldub sõna "eek".

Näiteks tagastab "leekreaktsioon" vasteks materjali "Ettevõtte teooria ja
konkurents (1 osa)". Selle materjali aadressiks on
"https://www.eek.ee/media/?id=VL4aeb161a3aec1", kus sisaldub sõna "eek".

Selline indekseerimine on realiseeritud arenduse #131 raames.

**Comment by erkkijakobson** [comment]
teeme ülejäänud parandustega tarne ära

131 indekseerimist tuleb lähemalt uurida

**Comment by KailiAll** [comment]
Tarne tehtud 21.06.2017.
