### ISSUE TITLE
Embbedimise parandused

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#174]
Palun parandada vead.

**IE vead:**
- [x] WebM (ei saa parandada, kuna brauser ei toeta seda formaati)
- [x] Ogg (ei saa parandada, kuna brauser ei toeta seda formaati)
- [x] EPUB (IEsse tekib link ja lingil klikkides tekib eraldi aken. Kasutuselolev IE teek bibi.js on kõige kasutuskõlblikum IE jaoks, kuid paraku see ei toeta hetkel IEd. )
- [x] e-Koolikotis peab avanema embedditult https://learningapps.org/1289642 (kasutaja peab ise lubama; juhend allpool)

**Mozilla vead:**
- [x] WebM

**Safari vead:**
- [x] WebM (ei saa parandada, kuna brauser ei toeta seda formaati)
- [x] Ogg (ei saa parandada, kuna brauser ei toeta seda formaati)

**Comment by erkkijakobson** [comment]
Materjali eelvaade (pilt, heli, pdf, jt) ei lae detailvaate avamisel 50% juhtudest, kuvatakse nt tühjus:
![image](https://cloud.githubusercontent.com/assets/16906555/25373608/0a3e4292-29a3-11e7-85f7-86b16bca0741.png)

Ülemine pilt Chromega, allolev pilt Firefoxist, mis laeb materjaliks avalehe, materjali id mõlemal 7730:

![image](https://cloud.githubusercontent.com/assets/16906555/25373754/908ba1e6-29a3-11e7-9dd9-ebd761ec6d45.png)

**Comment by erkkijakobson** [comment]
Firefox konsoolis 4 errorit (manus), Chrome näitab neist kolme - puudub kirje 'Cannot play media'
![image](https://cloud.githubusercontent.com/assets/16906555/25376370/8f50120e-29ac-11e7-951c-8a30f63e5047.png)

**Comment by erkkijakobson** [comment]
tõstsin prioriteeti: pooltel juhtudel (enamikel esmaavamistel) mitteilmuvad akendamised, nt https://e-koolikott.ee/material?id=7785 on tekitanud olukorra, kus kasutajad raporteerivad need materjalid katkiseks (isegi kogumikke raporteeritakse) ja aineeksperdid kontakteeruvad kasutajatoega, et nende materjalid on miskipärast katkiseks raporteeritud - ongi esmapilgul katkised aga tegelikult ei ole katkised st süsteem on katkine

**Comment by KailiAll** [comment]
Kommentaarid osade vigade kohta, mida me ei saa parandada, kuna brauser ei toeta seda:

**Internet explorer**
1) WebM
2) Ogg

**Safari**
1) WebM
2) Ogg

Osade vigade puhul peab kasutaja ise oma seadmes lubama IEs järgmisT : 
Internet Options> Security > Miscellaneous> Access data sources across domains - Siia tuleb panna linnuke vms

Kui kasutaja ei ole seda ise lubanud, ei saa avada järgmiseid linke:
**Internet Explorer**
1) vimeo link
2) soundcloudi link
3) https://learningapps.org
