### ISSUE TITLE
Esmaautentimise järgne dialoog ei liigu eest

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#175]
Läbiviidud töötoa kasutajatest ilmnes viga 10% juhtudest, olukorra tekitamise sammud:
1. esimest kord sisse logides avaneb esiletõstetud FAB tutvustus
2. tutvustus ei liigu eest ei 'Sain aru' ega 'Näita tuuri' lingile vajutades

Varasem näide samast veaolukorrast: tuur avaneb tumendatud overlay alla, vaatest väljuda ei saa:

![image](https://cloud.githubusercontent.com/assets/17288515/23998004/56d52bf4-0a5c-11e7-91bd-16b3c7baacd6.png)

**Comment by KailiAll** [comment]
@erkkijakobson 
Palun täpseid samme, kuidas veani jõuti.
Millega logiti sisse (ID-kaart, Mobiil-ID, Stuudium).
Ja mida kasutaja edasi tegi.

**Comment by erkkijakobson** [comment]
juhud, mil olin protsessi jälgimas kasutati ID kaarti, teistel kordadel nägin juba tekkinud veaolukorda;
kasutaja ühtki sammu edasi teha ei saanud, kõigil kordadel oli visuaalselt ette näha veaolukorra teke: justkui teinuks süsteem peale autentimisprotsessi lõppu aga enne antud dialoogi kuvamist sunnitud või pooliku refreshi lehele

**Comment by KailiAll** [comment]
@erkkijakobson 
Kahjuks ei õnnestu selle info põhjalt viga korrata.
Testiti nii chromes kui firefoxix 3 erineva versiooniga, aga viga ei saanud korrata.
Palun täpset brauseri versiooni/ versioone, millega viga tekkis.

**Comment by erkkijakobson** [comment]
sulgen kuni ei õnnestu korrata
