### ISSUE TITLE
Uue õppevara sobivaks märkimine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#177]
Raporteeritud õppevara avades on näha punane päis ja must bänner, millel nupud kustutamiseks ja korrasolevaks märkimiseks. Vajadus:
1. kuvada vähemalt sarnast bännerit aineeksperdi rollile kõigis detailvaadetes sobivuse märkimiseks
2. kui aineekspert märgib õppevara sobivaks/korrasolevaks, siis aineekspertidele enam bännerit ei näidata
3. vähemalt väikekaartidel kuvada kõigile kasutajatele visuaalset vihjet sobiaks märgituse kohta
4. kui lisaja õppevara muudab, kaob sobivuse staatus ja märge, tekib vajadus uuest ülevaadata-kinnitada
5. administraatorile peab toimingust tekkima ajaline, nt kvartaalne statistika ekspertide-valdkondade kaupa

**Comment by JaakL** [comment]
Esmalt üks üldine küsimus ja siis spetsiifilised küsimused/märkused seoses eelnevalt Erkki poolt märgitud punktidega.

Kas tegemist on „Uue“ õppevara valideerimisega aineeksperdi poolt, „Raporteeritud“ õppevara valideerimisega aineeksperdi poolt, „Muudetud“ õppevara valideerimisega aineeksperdi poolt või kõigi kolmega?


1.	_kuvada vähemalt sarnast bännerit aineeksperdi rollile kõigis detailvaadetes sobivuse märkimiseks_

- „Vähemalt sarnast“?
- Antud bänner on vajalik ainult „ebasobiva“ ja „muudetud“ materjali/portfolio puhul? Segadust tekitab just sõnapaar „kõigis detailvaadetes“.
- Kas praegu toimib kuidagi teisiti, kui eelpool kirjeldatud?
- Ise hetkel testides tundub, et nii ebasobivaks raporteeritud kui ka muudetud õppevaradel on antud bänner nähtav. Kasutaja oli küll Admin Admin (ehk mitte aineekspert).

2.	_kui aineekspert märgib õppevara sobivaks/korrasolevaks, siis aineekspertidele enam bännerit ei näidata_

- Arusaadav, baasis määratakse järelikult vastavale ImproperContent objektile „deleted“ väärtuseks 1. 
- Mis saab, kui baasis on antud õppevara kohta mitu ImproperContent objekti? Kas kõigile määratakse korraga „deleted“ ehk kas mitme kaebuse puhul määratakse ühe sobivaks kinnitamisega kõik kaebused baasis kustutatuks?  
- Kuidas UI’s mitu kaebust korraga kuvatakse? (Vist sain aru – „raporteeris“ tulbas kuvatakse „Mitmed kasutajad“, aga igaks juhuks uurin)
- Kas süsteem peab järgima ka seda, kes ja millal antud „ebasobiva materjali“ kustutas või sobivaks määraks? Statistika osa silmas pidades oleks see vajalik.
- Lisaks oleks statistikat silmas pidades ka lihtsam, kui õppevara kustutamisel selle ülevaatamise protsessi jooksul (kui tegemist on ka raporteeritud õppevaraga) märgitaks kustutatuks ka ImproperContent objekt. Hetkel seda ei tehta ja kustutatakse vaid LearningObject objekt, mistõttu lihtsa päringuga jääb mulje, justkui oleks antud õppevara raporteerimisele tagasiside andmata ja statistikasse sellest jälje jätmiseks tuleb päringu tegemisel oluliselt rohkem pead murda.

3.	_vähemalt väikekaartidel kuvada kõigile kasutajatele visuaalset vihjet sobiaks märgituse kohta_

- „Vähemalt väikekaardil“ – kas tähendab, et oleks vajalik ka muudel elementidel (pisikaart vms), kui esteetiliselt sobib?
- Mis antud visuaalse vihje eesmärk on? Kas autori teavitamine või kasutajatele kindluse loomine, et tegemist on kvaliteetse õppevaraga?
- Mis momendil antud vihjet kuvatakse? Kui kaua antud vihjet kuvatakse?
- Kas peab kuvama „sobivaks“ märgitust või pigem „ebasobivaks“ märgitust ja „muudetud“ staatust? 
- Viimase kahe puudumine tähendab automaatselt esimest situatsiooni („sobiv“ staatus). Samas, kui eesmärgiks on tekitada kasutajatele kindlustunne, et tegemist on kvaliteetse õppevaraga, siis igasugune positiivne märk õppevara juures on kasutajakogemuse poolest igati teretulnud.
- Kas tavakasutajatele on väikekaardil/suurel kaardil kuvatud, kui antud materjal on raporteeritud? Kas peaks olema?

4.	_kui lisaja õppevara muudab, kaob sobivuse staatus ja märge, tekib vajadus uuest ülevaadata-kinnitada_

- Ehk tekib baasi antud learningObject’ile viitav uus „ChangedLearningObject“ objekt. 
- Kas samal ajal ei tohi olla õppevara muudele kasutajatele (peale aineekspertide ja admin’ide) kättesaadav? Või peaks juures olema märge „Muudetud ja kinnitamata“ vms?
- Miks raporteerimiste puhul toimub baasis objektide soft delete, aga muudatuste puhul mitte?
- Soft delete puudumine ei võimalda tõenäoliselt muudatuste ajalugu track’ida – statistika eesmärgil oleks see vajalik.

5.	_administraatorile peab toimingust tekkima ajaline, nt kvartaalne statistika ekspertide-valdkondade kaupa_

- Mis on antud statistika eesmärk?
- Mis formaadis väljundid vajalikud on?
- Läbi rääkida UI vaated, mis selleks vajalikud on.
- Disain Marelt, minu poolt saaks vaid lehtede sisu struktuuri mock’i.
- Vaja läbi rääkida statistikapäringu parameetrid ja päringute koostamise võimalused lõppkasutajale (administraatorile).

**Comment by KailiAll** [comment]
@JaakL 
Tulemina lisa kas siia või wikisse analüüsi dokument.

**Comment by JaakL** [comment]
User story'd on lisatud Wikisse järgnevate peatükkidena.

**Peamine _feature_:**
[Õpiobjekti üle-vaatamine (raporteeritud, muudetud, uus)](https://github.com/hariduspilv/koolikott/wiki/Dokumentatsioon-(Feature):-%C3%B5piobjektide-%C3%BClevaatamine)

**Vajalikud kõrval_feature_'id ning analüüsikoosolekul esile kerkinud seotud teemad**:
[Ebasobivaks raporteerimise muudatused](https://github.com/hariduspilv/koolikott/wiki/Dokumentatsioon-(Feature):-Ebasobivaks-raporteerimine)

[Katkiste materjalide listvaade ainevaldkonna-põhiseks](https://github.com/hariduspilv/koolikott/wiki/Dokumentatsioon-(Feature):-Katkiste-materjalide-haldus)

[Kustutatud materjalide listvaade ainevaldkonna-põhiseks](https://github.com/hariduspilv/koolikott/wiki/Dokumentatsioon-(Feature):-Kustutatud-%C3%B5piobjektide-haldus)
