### ISSUE TITLE
Andmemudeli loomine

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#178]
Vastavalt 06.07.2017 toimunud koosolekule tuli soov kontseptuaalse andmemudeli osas.

**Comment by JaakL** [comment]
Järgneval lingil on kättesaadav andmemudeli diagramm. 
https://invis.io/4XCL7UAEQ#/243768157_Andmemudel

Teatud seoste ning andmeobjektide sisu selgitamiseks on lisatud juurde märkused, mis avanevad _tooptip_'i kujul, kui nendel vajutada. Antud märkused on leitavad siniste punktide/ringide juurest (enne esimest klikki kiirgavad enda ümber pulseerivalt suuremaid ringe, et oleks parem leida).

Diagrammil olevad tabelid ei ole kirjeldatud äärmise detailsusega (andmeväljadel puuduvad andmetüübid ning eemaldatud on triviaalsed andmeväljad tabelitest ning vähetähtsamad vahetabelid).

Kui tekib täpsustavaid küsimusi mingis kindlas osas, saan soovi korral täiendada.
