### ISSUE TITLE
e-Koolikoti arhitektuuri ja repositooriumi vajaduse analüüs

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#179]
Vajadus on vaadata üle e-Koolikoti arhitektuur lähtuvalt sellest, et HITSA ülesandeks on luua ühtne repositoorium mitmele teisele õpikeskkonnale ja repositooriumile.

**Comment by erkisisask** [comment]
Vt ka 17.aug [koosolekul ](https://projektid.hitsa.ee/pages/viewpage.action?pageId=10292295) arutatut.

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
