### ISSUE TITLE
Õppevara vistutamine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#18]
Youtube- ja Slidesharele lisaks täiendavate keskkondade õppevara vistutatud kujul kuvamine

- [x] Kasutaja näeb embeddituna alljärgnevaid keskkondi: [https://noembed.com/providers](https://noembed.com/providers)

**Comment by martlausNG** [comment]
Needs review.

**Comment by Jointts** [comment]
Review OK.

**Comment by erkkijakobson** [comment]
ei vistutu
![image](https://cloud.githubusercontent.com/assets/16906555/19378765/2bc7a4ce-91f7-11e6-896b-5cb3188258c6.png)
