### ISSUE TITLE
Tühi otsing tagastab vale arvu materjale

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#180]
***Vea kordamine*:**
1. Kirjutad otsisõna lahtrisse otsitava sõna nt "otsisõna"
2. Süsteem teostab selle peale automaatse otsingu ja tagastab teate "Ühtegi vastet ei leitud."
![image](https://user-images.githubusercontent.com/19947450/29456501-9d8ccb6a-841e-11e7-8541-131445ede2c9.png)
3. Tühjendad otsingu lahtri.
4. Süsteem teostab selle peale automaatse otsingu ja tagastab rohkem vasteid kui süsteemis tegelikult on.
Konkreetse näite puhul tagastas vastuseks "Otsingule leidus 24147 vastet." kuigi kui vaadata sisukorras olevate materjalide arvu, siis ei saa see number nii suur olla.
![image](https://user-images.githubusercontent.com/19947450/29456527-c034af8e-841e-11e7-9b96-07828073d4c9.png)

**Comment by JaakL** [comment]
Bugiga seotud ja koosolekul täiendavalt otsinguga esile tõusnud teemad:
[Õppevara otsing](https://github.com/hariduspilv/koolikott/wiki/Dokumentatsioon-(Feature):-%C3%95ppevara-otsing)

**Comment by AndersNG** [comment]
Bugiparandus tarnitud MS 9 tarnega.
