### ISSUE TITLE
PDF lingi akendamine ei toimi

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#182]
Näited:
https://e-koolikott.ee/material?id=6154
https://e-koolikott.ee/material?id=6397

Oodatud tulemus: lehel kuvatakse akendatud PDF
Hetkeolukord (testitud Chrome ja Firefoxiga):
![image](https://user-images.githubusercontent.com/16906555/29665363-71a264ca-88dc-11e7-86c7-4611154247ef.png)

**Comment by OlegPahhomov** [comment]
https://github.com/mozilla/pdf.js/issues/7153 tundub olevat sarnane asi

**Comment by erkisisask** [comment]
Tarnitud MS10 tarnega.
