### ISSUE TITLE
Kogumiku muutmise disainilahenduse arenduse analüüs

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#183]
Tulem:
Tulemina lisada palun sellesse piletisse või viide wikisse analüüs, mis sisaldab arenduse jaoks vajalikku infot.

**Comment by JaakL** [comment]
_User story_'d koondatud Wikis järgneva _feature_'i alla:
[Kogumiku lisamine ja muutmine](https://github.com/hariduspilv/koolikott/wiki/Dokumentatsioon-(Feature):-Kogumiku-lisamine-ja-muutmine)
