### ISSUE TITLE
Andmebaasimuudatused uute (üle vaatamata) õpiobjektide eristamiseks

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#184]
Luua andmebaasi uus tabel NewLearningObject, mis sisaldab järgnevaid veerge:

- ID (bigint(20); auto increment)
- learningObject (bigint(20); viide learningObject tabelikirjele)
- deleted (tinyint(1); kas õpiobjekt on üle vaadatud või mitte; vaikimisi 0)
- deletedBy (bigint(20); viide kasutajale, kes märkis õpiobjekti ülevaadatuks)
- deletedAt (timestamp; õpiobjekti üle vaatamise aeg)

Uue õpiobjekti (kogumik/materjal) loomisel süsteemis tekitatakse sellele õpiobjektile viitav kirje ka NewLearningObject tabelisse, kus learingObject väli viitab loodud õpiobjektile ning deleted välja väärtus on 0.

**Acceptance criteria:**
- [x] Õpiobjektiga seotud andmebaasikirjete alusel on võimalik tuvastada kas õpiobjekt on läbinud esmase ülevaatuse

- [x] Õpiobjektiga seotud andmebaasikirjete alusel on võimalik tuvastada õpiobjekti esmase ülevaatuse aeg ja teostaja

[Task 1.2.1 in User Story 1.2 - Uute objektide üle vaatamine.docx](https://github.com/hariduspilv/koolikott/files/1288196/User.Story.1.2.-.Uute.objektide.ule.vaatamine.docx)

**Comment by OlegPahhomov** [comment]
Muutus tabeli nimi:

FirstReview (
  id             BIGINT  AUTO_INCREMENT,
  learningObject BIGINT NOT NULL,
  reviewed       BOOLEAN NOT NULL DEFAULT FALSE,
  reviewedBy     BIGINT NULL ,
  createdAt      TIMESTAMP NULL ,
  reviewedAt     TIMESTAMP NULL ,
  PRIMARY KEY (id),
  FOREIGN KEY (learningObject) REFERENCES LearningObject (id),
  FOREIGN KEY (reviewedBy) REFERENCES User (id)
);

**Comment by AndersNG** [comment]
Tarnitud MS 9 tarnega.
