### ISSUE TITLE
Uute (üle vaatamata) õpiobjektide bänner

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#185]
Kuvada aineeksperdi ja administraatori rollis kasutajatele uute üle vaatamata õpiobjektide detailvaatel musta bännerit teatega „Õppematerjal on üle vaatamata.“ (kogumiku puhul „Kogumik on üle vaatamata.“). Bänner sisaldab lisaks ka nuppu õpiobjekti sobivaks märkimiseks.

Uue (üle vaatamata) õpiobjekti sobivaks märkimise järel ei ole enam õpiobjekti detailvaatel kuvatud musta bännerit teatega „Õpiobjekt on üle vaatamat“ ega õpiobjekt pole kuvatud „Üle vaatamata õppevara“ listvaates.

Bänner on kuvatud, kui õpiobjektiga seotud NewLearningObject objekti deleted välja väärtus on 0. 

Kui kasutajale on kuvatud vastav bänner, on kasutaja navbar’i värvitooniks punane (nagu aineekspertidel ja administraatoril on üldiselt töölaua funktsionaalsuste kasutamisel).

Bänneril oleval linnukese ikoonil vajutades kinnitatakse õpiobjekt ülevaadatuks ning:

- Vastaval NewLearningObject objektil määratakse baasis deleted väärtuseks 1
- Vastaval NewLearningObject objektil määratakse baasis deletedAt väärtuseks antud hetke timestamp.
- Vastaval NewLearningObject objektil määratakse baasis deletedBy väärtuseks nupul vajutanud kasutaja ID

**Acceptance criteria:**
- [x] Aineekspertidele ja administraatoritele on üle vaatamata õpiobjekti detailvaate päises kuvatud musta bännerit teatega „See õppevara on üle vaatamata“
- [x] Üle vaatamata õpiobjektid peavad olema ligipääsetavad kõikidele kasutajatele (sh anonüümsetele kasutajatele)
- [x] Üle vaatamata õpiobjekti esmasel ülevaatamisel sobivaks märkimisel tuleb sellega seotud NewLearningObject andmebaasi objektil märkida deleted väärtuseks 1
- [x] Üle vaatamata õpiobjekti esmase üle vaatamise järel süsteem õpiobjekti detailvaate päises musta bännerit ei kuva 
- [x] Esmase ülevaatamise järel ei ole õpiobjekt kuvatud „Üle vaatamata õppevara“ listvaates
- [x] Esmase ülevaatamise järel lisatakse andmebaasis õpiobjektile ülevaatamise teostaja ja aeg

[Task 1.2.3 in User Story 1.2 - Uute objektide üle vaatamine.docx](https://github.com/hariduspilv/koolikott/files/1288196/User.Story.1.2.-.Uute.objektide.ule.vaatamine.docx)

**Comment by AndersNG** [comment]
Tarnitud MS 9 tarnega.
