### ISSUE TITLE
Üle vaatamata uute õpiobjektide jaoks eraldi listvaade

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#186]
Kuvada aineeksperdi ja administraatori rollis kasutajatele Töölaua menüüs täiendav menüüpunkt:

- Üle vaatamata õppevara

Antud menüüpunkt viitab uuele vaatele, mis sisaldab tabelit üle vaatamata materjalide ja üle vaatamata kogumikega.

Listvaate tabel peab sisaldama järgnevaid veerge:

- Pealkiri (Kogumiku/materjali pealkiri)
- Lisaja (Kogumiku/materjali lisanud kasutaja nimi)
- Lisatud (Kogumiku/materjali lisamise kuupäev)

Tabeliridade parempoolses otsas peab olema kuvatud nupp „Ava“, mis viib vastava õpiobjekti detailvaatele.

Listvaate tabel peab olema sorteeritav kõikide veergude alusel.

Eelmainitud uutes listvaadetes peab olema kasutaja navbar’i värvitooniks punane (nagu aineekspertidel ja administraatoril on üldiselt töölaua funktsionaalsuste kasutamisel).

Aineeksperdi rollis kasutajale peab „Üle vaatmata õppevara“ listvaade sisaldama vaid vastava aineeksperdiga seotud valdkondade õpiobjekte.

- Ehk kasutajale peab olema listvaates kuvatud vaid õpiobjektid, millega seotud Taxon objektid (seosed LearningObject_Taxon tabelis) on seotud ka kasutajaga (seosed User_Taxon tabelis).

**Acceptance criteria:**

- [ ] Töölaua menüüvalikutes on administraatorile ja aineeksperdile kuvatud uus menüüvalik „Üle vaatamata õppevara“
- [ ] „Üle vaatamata õppevara“ listvaates on aineeksperdile kuvatud ainult aineeksperdiga seotud valdkondade materjalid ja kogumikud, mis pole läbinud esmast ülevaatust
- [ ] „Üle vaatamata õppevara“ menüüvaliku juures on aineeksperdile kuvatud ainult aineeksperdiga seotud valdkondade materjalide ja kogumike arv, mis pole läbinud esmast ülevaatust
- [ ] „Üle vaatamata õppevara“ listvaates on administraatorile kuvatud kõik materjalid ja kogumikud, mis pole läbinud esmast ülevaatust
- [ ] „Üle vaatamata õppevara“ menüüvaliku juures on adminsitraatorile kuvatud kõikide materjalide ja kogumike arv, mis pole läbinud esmast ülevaatust
- [ ] „Üle vaatamata õppevara“ listvaates on kasutajale navbar kuvatud punase tooniga
- [ ] „Üle vaatamata õppevara“ listvaates kuvatud tabel on sorteeritav kõikide veergude alusel

[Task 1.2.4 in User Story 1.2 - Uute objektide üle vaatamine.docx](https://github.com/hariduspilv/koolikott/files/1291519/User.Story.1.2.-.Uute.objektide.ule.vaatamine.docx)

**Comment by AndersNG** [comment]
Tarnitud MS 9 tarnega.
