### ISSUE TITLE
Linnukese (checkmark) ikoon üle vaadatud materjalide tuvastamiseks

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#187]
Kuvada aineeksperdi ja administraatori rollis kasutajatele õpiobjekti detailvaatel, väikekaardil ja pisikaardil märget selle kohta, et õpiobjekt on aineeksperdi poolt märgitud üle vaadatuks.

Linnuke peab olema kuvatud järgnevates kohtades:

- Väikekaart
- Pisikaart
- Detailvaade

Linnuke on kuvatud järgnevatel tingimustel:

- NewLearningObject objekti deleted välja väärtus on 1 ja LearningObject’ile ei viita ühtegi ChangedLearningObject objekti, mille deleted välja väärtus oleks 0.
- Teostatav peale task’i 1.3.1 „Andmebaasimuudatused uute õpiobjektide soft delete võimaldamiseks“ realiseerimist.

Käesoleva taski testimise eelduseks on ChangedLearningObject tabeli korrektne toimimine süsteemselt ja äriloogiliselt.

**Acceptance criteria:**

- [ ] Esmase ülevaatuse läbinud õpiobjektidel, millel pole kinnitamata muudatusi, on detailvaatel kuvatud märge (roheline checkmark)
- [ ] Esmase ülevaatuse läbinud õpiobjektidel, millel pole kinnitamata muudatusi, on väikekaardil kuvatud märge (roheline checkmark)
- [ ] Esmase ülevaatuse läbinud õpiobjektidel, millel pole kinnitamata muudatusi, on pisikaardil kuvatud märge (roheline checkmark)

[Task 1.2.2 in User Story 1.2 - Uute objektide üle vaatamine.docx](https://github.com/hariduspilv/koolikott/files/1291528/User.Story.1.2.-.Uute.objektide.ule.vaatamine.docx)

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
