### ISSUE TITLE
Kustutatud õppevara kolme täpi menüü kuvada ainult administraatorile

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#190]
- [ ] Kustutatud õppevara detailvaatel kuvada kolme täpi menüü ainult administraatori rollis kasutajatele

![Kolme punkti menüü](https://user-images.githubusercontent.com/3177716/31946539-62519c9a-b8d2-11e7-9d50-c3f986282851.png)

- [ ] Administraatori rollis kasutajale on kuvatud "Minu asjad" menüü alampunkt „Kustutatud õppevara"
- [ ] Aineeksperdi rollis kasutajale ei ole kuvatud "Minu asjad" menüü alampunkt „Kustutatud õppevara"
- [ ] Administraatori rollis kasutaja jaoks sisaldab „Kustutatud õppevara" listvaade kõiki kustutatud kogumikke ja materjale

**Comment by JaakL** [comment]
Muudetud _issue_ pealkirja sõnastust _whitelist_ loogika põhiseks.

Muudetud esialgse ülesandepüstituse juures nõude sõnastust _whitelist_ loogikale vastavaks. Kustutatud õppevara detail- ja listvaade korrektne käitumine kirjeldatud Wikis:
[Kustutatud õpiobjektide haldus](https://github.com/hariduspilv/koolikott/wiki/Dokumentatsioon-(Feature):-Kustutatud-%C3%B5piobjektide-haldus)

**Comment by erkisisask** [comment]
Tarnitud MS11 tarnepakiga (rakenduse versioon 1.12.0).
