### ISSUE TITLE
Youtube Live vistutamine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#191]
Kliendi märkmed:
- [ ] youtube lingi lisamisel materjaliks (#59) eelmäärata õppevara tüübiks 'Video'
- [ ] kui on tegu livestreamiga, kuvada akendatud kujul ka kommentaaride voogu

--------------------------------
Kasutaja rollis tavakasutaja, aineekspert, administraator saab luua Youtube Live video alusel materjale, mis on kuvatud E-koolikotis vistutatud kujul koos selle juurde kuuluva aktiivse live chat’iga.

Kõikides rollides kasutajad, kellel on ligipääs materjalile, mis on tehtud Youtube Live video alusel, on võimalik lugeda ja sisestada sõnumeid video juurde kuuluvas aktiivses live chat’is.

**Acceptance criteriad**
- [ ] Süsteem kuvab aktiivse live chat’i olemasolu puhul Youtube Live video all vistutatud kujul live chat’i
- [ ] Lisades materjali lingiks Youtube’i lingi, määrab süsteem automaatselt materjali tüübiks „Video“
- [ ] Live chat’i vistutatud elementi ei kuvata, kui ülekanne on lõppenud.
- [ ] Kogumikus vistutatud materjal Youtube Live lingiga tuleb samuti kuvada koos live chat’iga, kui video puhul tuvastatakse aktiivne live chat
- [ ] Süsteem tuvastab korrektselt, kui Youtube videoga kaasneb aktiivne live chat
- [ ] Süsteem tuvastab korrektselt, kui live chat muutub mitteaktiivseks
- [ ] Süsteem kuvab Youtube Live video juurde kuuluva live chat’i video all eraldi vistikuna
- [ ] Vistutatud live chat täieneb sõnumitega, mis on sisestatud läbi E-koolikoti vistiku või Youtube’i
- [ ] E-koolikotis oleva vistiku kaudu on võimalik sisestada sõnumeid live chat’i
- [ ] Google’i kontoga sisselogimata kasutajatele kuvatakse sõnumi tekstikasti asemel nuppu sisselogimiseks
- [ ] Peale sisselogimist läbi eelmainitud nupu, suunab brauser kasutaja korrektsele E-koolikoti vaatele

Analüüs: https://github.com/hariduspilv/koolikott/wiki/Feature:-Youtube-Live-vistutamine

**Comment by erkisisask** [comment]
Analüüs valmis, tarnitud MS12 sprindiga.

**Comment by erkisisask** [comment]
27.12.2017 Tellija otsusega sulgemisele.
