### ISSUE TITLE
Angular põhiversiooni uuendamise eeltööd v.1

### ISSUE THREAD

**Issue by AndersNG** [hariduspilv/koolikott#192]
Angular põhiversiooni uuenduse läbiviimiseks teostatakse järgnevad eeltööd:

- [ ] Front-end direktiivid viia üle ES6 standardile ja kirjutada komponentideks
       Fookus: infiniteSearchResult.js, recommend.js, restrict.js,slideshare.js
- [x] Ühtse HTML wrapper kasutuselevõtt kõigis vaadetes

- [x] Front-end komponentide uuendamine
        Angularjs 1.6.1 -> 1.6.4
        Angular Material 1.1.1 -> 1.1.4

**Comment by AndersNG** [comment]
ES6 direktiivide osa tarnitakse MS 11 raames, kuna MS 10 vaadete muutmine toob kaasa vajaduse direktiive ümber kirjutada. HTML wrapper ja komponentide uuendused sisalduvad MS10 tarneversioonis.

**Comment by erkisisask** [comment]
ES6 direktiivide jaoks loodud MS11 tarne jaoks eraldi pilet: https://github.com/hariduspilv/koolikott/issues/229

**Comment by erkisisask** [comment]
Tarnitud MS10 tarnega.
