### ISSUE TITLE
Ebasobivaks raporteeritud õpiobjekti kustutamisega/sobivaks märkimise andmebaasitööd

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#193]
Lisada andmebaasis **ImproperObject** tabelisse väli **deletedBy** tüübiga bigint, mis viitab välisvõtmena vastava õpiobjekti üle vaatanud (kustutanud/sobivaks märkinud) kasutaja kirjele User tabelis.

Lisada andmebaasis **ImproperObject** tabelisse väli **deletedAt** tüübiga timestamp, kuhu salvestatakse vastava ebasobiva õpiobjekti ülevaatamise (kustutamise/sobivaks märkimise) aeg.

Lisada andmebaasi võimalus eristamaks, kas ebasobiv õpiobjekt kustutati või märgiti sobivaks.

**Acceptance criteria**

- [ ] Raporteeritud õpiobjekti andmebaasikirje alusel on võimalik tuvastada raporteeritud õpiobjekti ülevaatamise tulemus (kustutamine/sobivaks märkimine)
- [ ] Raporteeritud õpiobjekti andmebaasikirje alusel on võimalik tuvastada õpiobjekti ülevaatamise aeg ja teostaja

[Task 1.1.1 in User Story 1.1 - Aineksperdi-poolne ebasobivaks raporteeritud õpiobjekti ülevaatamine.docx](https://github.com/hariduspilv/koolikott/files/1344411/User.Stories.E-koolikott.-.sprindid.1.ja.2.220917.docx)

**Comment by EgleRR** [comment]
Tabeli nimi  "ImproperObject" asemel "ImproperContent"

Väljade nime muudatused:
"deleted" -> "reviewed"
"added" -> "createdAt"

Uued lisatud väljad:
"reviewedBy" (deletedBy asemel)
"reviewedAt" (deletedAt asemel)

Võimalus eristamaks, kas kustutati/märgiti sobivaks:
Lisatud juurde väli "status":
- kustutati väärtus = "DELETED"
- märgiti sobivaks väärtus = "ACCEPTED"

**Comment by erkisisask** [comment]
Tarnitud MS10 tarnega.
