### ISSUE TITLE
Ebasobivaks raporteeritud õpiobjekti kustutatuks märkimise täiendused

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#195]
Rakenduses aineeksperdi poolt ebasobivana raporteeritud õpiobjekti kustutamisel (sõltumata õpiobjekti tüübist: materjal või kogumik) tuleb baasis vastava ImproperObject kirjega teostada järgnevad toimingud:

- lisada kustutanud aineeksperdi kasutaja User tabeli ID väljale deletedBy

- lisada kustutamise hetke timestamp väljale deletedAt

- märkida deleted välja väärtuseks 1 

- Märkida andmebaasis vastava ImproperContent tabeli kirje juures antud objekti kustutamise tüübiks „Kustutamine.

Ebasobivaks märgitud ning seejärel kustutatud õppematerjali taastamise järgselt ei tohi õpiobjekti detailvaatel olla kuvatud must bänner teatega „Raporteeritud ebasobivaks“.

**Acceptance criteria**

- [ ] Aineekspertidele ja administraatoritele on raporteeritud õpiobjekti detailvaate päises kuvatud musta bännerit, kus saab märkida õpiobjekti sobivaks või seda kustutada
- [ ] Raporteeritud õpiobjektid peavad olema ligipääsetavad kõikidele kasutajatele (sh anonüümsetele kasutajatele)
- [ ] Raporteeritud õpiobjekti kustutamise järel süsteem õpiobjekti detailvaate päises musta bännerit teatega „Raporteeritud ebasobivaks“ ei kuva
- [ ] Raporteeritud õpiobjekti kustutamise järel õpiobjekti tavakasutajatele kuvatud ei ole
- [ ] Raporteeritud õpiobjekti kustutamise järel ei ole õpiobjekt kuvatud „Ebasobivad materjalid“/“Ebasobivad kogumikud“ listvaates
- [ ] Raporteeritud õpiobjekti kustutamise järel kuvatakse administraatorile ja aineeksperdile õpiobjekti detailvaatel halli bännerit teatega „See õppevara on kustutatud“
- [ ] Raporteeritud õpiobjekti kustutamisel tuleb selle andmebaasi objektil märkida deleted väärtuseks 1
- [ ] Raporteeritud õpiobjekti kustutamisel lisatakse andmebaasis raporteeritud õpiobjekti kirjele ülevaatamise tulemuseks „Kustutamine“
- [ ] Kustutatud ja raporteeritud õpiobjekti taastamise järel ei ole õpiobjekti detailvaate päises kuvatud aineekspertidele ja administraatoritele musta bänneritud teatega „Raporteeritud ebasobivaks“

[Task 1.1.3 in User Story 1.1 - Aineksperdi-poolne ebasobivaks raporteeritud õpiobjekti ülevaatamine.docx](https://github.com/hariduspilv/koolikott/files/1344411/User.Stories.E-koolikott.-.sprindid.1.ja.2.220917.docx)

**Comment by EgleRR** [comment]
"deletedBy" välja asemel kasutusel "reviewedBy"
"deletedAt" välja asemel kasutusel "reviewedAt"
"deleted" välja asemel kasutusel "reviewed"
"status" välja väärtus -> "DELETED"

**Comment by erkisisask** [comment]
Tarnitud MS10 tarnega.
