### ISSUE TITLE
Ebasobivaks raporteeritud õpiobjektide bänner

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#196]
Ebasobivaks raporteeritud õpiobjektide detailvaatel kuvatud must bänner tuleb ümber muuta collapsible tüübiga elemendiks, et oleks võimaliks välja kuvada kogu raporteerimise põhjus.

Kui raporteerimise põhjus(ed) on pikem(ad) kui 1 rida, on vaikimisi bänneri collapsible element suletud seisus (collapsed) ja raporteerimise põhjus kuvatud vaid osaliselt ning katkestatud kolme punktiga. Kui collapsible element on avatud seisus (expanded), on kuvatud kogu põhjuse tekst.

Kui materjal on raporteeritud mitme kasutaja poolt ning raporteerimise põhjused on erinevad (valikuväljal valitud erinevad väärtused), tuleb iga põhjus kuvada reavahedega eraldatult. Mitme erineva põhjuse puhul tuleb ebasobivaks raporteeritud õpiobjekti vaatel kasutada bänneri kuvamiseks collapsible elementi.

Kui musta bänneri collapsible element on suletud (collapsed) seisus, kuvatakse hiirekursorina käemärki ning bänneri kohal hiirega hõljudes (hover) kuvatakse kasutajale tooltip tekstiga „Kuva kogu põhjuse tekst“. 

Kui musta bänneri collapsible element on avatud (expanded) seisus, kuvatakse hiirekursorina käemärki ning bänneri kohal hiirega hõljudes (hover) kuvatakse kasutajale tooltip tekstiga „Peida põhjuse tekst“.

**Acceptance criteria**:

- [ ] Raporteeritud õpiobjekti detailvaatel kuvatud must bänner on collapsible tüübiga HTML element, kui raporteerimise põhjuse tekst on vaja kuvada mitmel real
- [ ] Musta bänneri collapsible element on vaikimisi suletud (collapsed) seisus
- [ ] Mitme raporteerimise puhul on mustal bänneril kuvatud raporteerimise põhjused eraldatud reavahedega
- [ ] Suletud seisus collapsible elemendi kohal hiirega hõljudes (hover) kuvab süsteem tooltip’i „Kuva kogu põhjuse tekst“
- [ ] Avatud seisus collapsible elemendi kohal hiirega hõljudes (hover) kuvab süsteem tooltip’i „Peida põhjuse tekst“
- [ ] Suletud seisus collapsible elemendis oleva põhjuse teksti lõpus on kuvatud kolm punkti
- [ ] Collapsible elemendi kohal hiirega hõljudes (hover) on hiirekursoriks käemärk

[Task 1.1.4 in User Story 1.1 - Aineksperdi-poolne ebasobivaks raporteeritud õpiobjekti ülevaatamine.docx](https://github.com/hariduspilv/koolikott/files/1344411/User.Stories.E-koolikott.-.sprindid.1.ja.2.220917.docx)

**Comment by erkkijakobson** [comment]
Uues lahenduses ei tohiks enam olla võimalik, et põhjuseks toodud Materjal esineb topelt:
![image](https://user-images.githubusercontent.com/16906555/31124018-3de7df8c-a84b-11e7-8f2f-9a83cd42c0df.png)

**Comment by kokakoola** [comment]
Disain, kui põhjus on pikk või on mitu põhjust e. ei mahu ühele reale:
- kasutusel _collapse_
- banneril kuvatakse a) põhjus b) peale koolonit selgitus nii palju kui mahub. edasi _ellipsis_ . 
- collapse sisus esimesel kuvatakse a) raporteerija nimetähed, mummu sees (värv indikeerib raporteerija rolli, lihtinimene on sinine, moderaator ja admin punane), :hoveriga  näidatatkse _tooltip_ raporteerija nimega Tulevastes iteratsioonides võiks olla ka :mailto link b) põhjus c) põhjus täismahus (max 255 tähemärki)
- banneril kuvatakse esimene põhjus nii palju kui mahub. collapse sisus kuvatakse esimesena seesama põhjus täismahus (kordus)
https://projects.invisionapp.com/d/main#/console/8788509/257210095/preview

Disain, kui põhjus on lühike, mahub ühele reale:
https://projects.invisionapp.com/d/main#/console/8788509/257209667/preview

Muud asjad jäävad esialgu samaks (ikoonid)

**Comment by erkkijakobson** [comment]
disain ok s.o. lehe keskel olev (väljaspool vasakmenüüd kus hetkel terminoloogia ja punktid paigast)

**Comment by erkisisask** [comment]
Tarnitud MS10 tarnega.
