### ISSUE TITLE
Ebasobivate õpiobjektide listvaadete „Põhjus“ veerg

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#198]
Aineeksperdi ja administraatori rollis kuvatud „Ebasobivad materjalid“ ja „Ebasobivad kogumikud“ listvaadete veerus „Põhjus“ peab kuvama tekstiväärtuseid erinevalt vastavalt järgnevatele tingimustele:

- Kui kogumiku/materjaliga seotud raporteerimiste arv on 1 ning antud raporteerimisega on seotud vaid 1 põhjus, peab süsteem „Põhjus“ veerus kuvama antud põhjuse teksti.
- Kui kogumiku/materjaliga seotud raporteerimiste arv on suurem kui 1 ning iga antud raporteerimisega on seotud vaid sama põhjus, peab süsteem „Põhjus“ veerus kuvama antud põhjuse teksti
- Kui kogumiku/materjaliga seotud raporteerimiste arv on 1 ning antud raporteerimisega on seotud rohkem kui 1 põhjust, peab süsteem „Põhjus“ veerus kuvama teksti „Erinevad põhjused“
- Kui kogumiku/materjaliga seotud raporteerimiste arv on suurem kui 1 ning antud raporteerimistega on seotud rohkem kui 1 erinevat põhjust, peab süsteem „Põhjus“ veerus kuvama teksti „Erinevad põhjused“

**Acceptance criteria:**

- [ ] Ühe raporteerimisega (1 põhjus) seotud kogumiku puhul on kuvatud korrektne tekst
- [ ] Ühe raporteerimisega (1 põhjus) seotud materjali puhul on kuvatud korrektne tekst
- [ ] Ühe raporteerimisega (mitu põhjust) seotud kogumiku puhul on kuvatud korrektne tekst
- [ ] Ühe raporteerimisega (mitu põhjust) seotud materjali puhul on kuvatud korrektne tekst
- [ ] Mitme raporteerimisega (sama põhjus) seotud kogumiku puhul on kuvatud korrektne tekst
- [ ] Mitme raporteerimisega (sama põhjus) seotud materjali puhul on kuvatud korrektne tekst
- [ ] Mitme raporteerimisega (erinevad põhjused) seotud kogumiku puhul on kuvatud korrektne tekst
- [ ] Mitme raporteerimisega (erinevad põhjused) seotud materjali puhul on kuvatud korrektne tekst

[Task 1.1.6 in User Story 1.1 - Aineksperdi-poolne ebasobivaks raporteeritud õpiobjekti ülevaatamine.docx](https://github.com/hariduspilv/koolikott/files/1344411/User.Stories.E-koolikott.-.sprindid.1.ja.2.220917.docx)

**Comment by kokakoola** [comment]
Disain siin:
https://projects.invisionapp.com/d/main#/console/8788509/257209670/preview
- Peidame palun Lisa kogumik-materjal nupu - adminvaade pole selleks õige koht, segab  - ETTEPANEK, kinnitamata
- Tabeli pealkiri ja otsiväli kõrvuti. Muidu raiskame vertikaalset ruumi - ETTEPANEK, kinnitamata
- Tabelite veergudel `ellipsis` kui väärtus on tekst 
- Tabelite veerud joondatud vasakule v. a. Arv, kuupäev, mis on `centered`
- Tabelite veergudel Arv, kuupäev on min ja max laius
- Tabelite veergudel on mõisltik `max-width` v.a. kirjelduse veerul
- Kui lehekülgi on 1, `paginationit` ei näidata  - ETTEPANEK, kinnitamata
- Kaardil otsi väljal klõpsates alajoon sinine (vt kogumiku sisestamine)  - ETTEPANEK, kinnitamata
- Tabelite veergude read on klikatavad, seda indikeerib hover, noolt ega nuppu ei ole  - ETTEPANEK, kinnitamata
- Jälgi `th` joone värvi, see on tumedam!

**Comment by erkkijakobson** [comment]
Jälgida terminoloogiat menüüs ja pealkirjas - ei ole **kõlbmatu õpivara** vaid **raporteeritud õppevara**

Tehtud ettepanekud:
1. lisamise nupp on vaatest sõltumatu ja jääb paika - segav oleks peitmisel tekkiv nupu vilkumine kas a) admin vaate ja detailvaate vahel või b) tavalise ja raporteeritud õppevara detailvaate vahel
2. tabeli pealkiri ja otsiväli viia kõrvuti - sobib, rakendada sama kõigile listvaadetele!
3. kui lehekülgi on 1, paginatsiooni rida ei näidata - sobib, rakendada sama kõigile listvaadetele!
4. listvaate otsingu sinine alajoon - sobib, rakendada sama kõigile listvaadetele!
5. listvaate veergudel pole ei noolt ega nuppe - sobib, aga kaaluda kuidas listvaateid siin ühildada!

Lisada ka tüübi ikoonile tooltip tüübi enda kohta ja tüübi ikoon teistesse listvaadetesse. Disain ok.

**Comment by AndersNG** [comment]
Jääme kehtiva terminoloogia juurde - raporteeritud õppevara.

1. Jääme olemasoleva lahenduse juurde.
2. Realiseeritakse eraldi piletina mõnes järgmises MS - rakenduks kõigile sarnastele listvaadetele.
3. Realiseeritakse eraldi piletina mõnes järgmises MS - rakenduks kõigile sarnastele listvaadetele.
4. Realiseeritakse eraldi piletina mõnes järgmises MS - rakenduks kõigile sarnastele listvaadetele.
5. Realiseeritakse eraldi piletina mõnes järgmises MS - rakenduks kõigile sarnastele listvaadetele.

**Comment by erkisisask** [comment]
Tarnitud MS10 tarnega.
