### ISSUE TITLE
Õpiobjekti kustutamisel seotud objektide kustutamine

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#199]
Rakenduses õpiobjekti (materjal/kogumik) kustutamisel tuleb kustutatuks märkida (deleted=1) ka antud õpiobjektiga seotud kirjed järgnevatest andmetabelitest, mis ei ole veel kustutatud staatuses:

- ChangedLearningObject
- ImproperObject
- BrokenContent

**Acceptance criteria:**

- [ ] Raporteeritud ja seejärel kustutatud õpiobjekti taastamise järel ei ole õpiobjekti detailvaate päises kuvatud aineekspertidele ja administraatoritele musta bännerit teatega „Raporteeritud ebasobivaks“
- [ ] Muudetud ja seejärel enne 10 päeva möödumist kustutatud õpiobjekti taastamise järel ei ole õpiobjekti detailvaate päises kuvatud aineekspertidele ja administraatoritele musta bännerit teatega muudetud andmete kohta
- [ ] Katkiseks märgitud ja seejärel kustutatud materjali taastamise järel ei ole õpiobjekti detailvaate päises kuvatud aineekspertidele ja administraatoritele musta bännerit teatega „Raporteeritud katkiseks“
- [ ] „Kustutatud materjalid“ ja „Kustutatud kogumikud“ listvaadetes sisalduvad materjalid ja kogumikud ei sisaldu ülejäänud töölaua ega tavakasutaja menüü listvaadetes (ebasobivad, katkised, muutunud, üle vaatamata, tavakasutaja materjalide/kogumike vaated)
- [ ] Üle vaatamata ja kustutatud õpiobjekti taastamise järel ei ole õpiobjekti detailvaate päises kuvatud aineekspertidele ja administraatoritele musta bännerit teatega „See õppevara on üle vaatamata“

[Task 1.4.1 in User Story 1.4 - Üldine õpiobjektide kustutamine.docx](https://github.com/hariduspilv/koolikott/files/1344411/User.Stories.E-koolikott.-.sprindid.1.ja.2.220917.docx)

**Comment by erkisisask** [comment]
Tarnitud MS10 tarnega.
