### ISSUE TITLE
Olemasoleva materjali kontroll uue lisamisel

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#2]
URLi põhine süsteemisoleva materjali kontroll peab rakenduma ka FABist uue materjali lisamisel

- [x] arvestama peab erinevaid URLi kujusid: http-ga ja ilma, kaldkriipsuga lõppev või ilma
- [x] kustutatud materjale uuesti ei saa lisada, kuvatakse süsteemne Toast vastava teatega
- [x] asetades URLi väljale olemasoleva lingi peab süsteem kasutajale sellest märku andma. Märguanne toimub täna olemasolevate veateadetega. Enne ei saa materjali salvestada kui veateated ei ole eemaldatud.

**Comment by RannarA** [comment]
Needs review

**Comment by Jointts** [comment]
Review OK.

**Comment by erkkijakobson** [comment]
Issue kirjelduses oli ka võimalus olemasoleva lingi puhul materjali detailvaatesse suunduda

**Comment by martlausNG** [comment]
Siin seda pole ja hindamisel me seda ka ei ole kirja pannud. Seega ei peaks seda ka olema.

**Comment by martlausNG** [comment]
Kas selle võib sulgeda?
