### ISSUE TITLE
Kustutatud õpiobjektide listvaated aineekspertide eest peidetuks

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#200]
Aineeksperdi rollis kasutajal ei tohi olla "Töölaud" menüü alamvalikute seas valitavad järgnevad menüüpunktid: "Kustutatud kogumikud" ja "Kustutatud materjalid".

**Acceptance criteria**

- [ ] „Kustutatud materjalid“ menüüpunkt ei ole kuvatud "Töölaud" menüü alampunktina aineeksperdina sisse logitud kasutajale
- [ ] „Kustutatud kogumikud“ menüüpunkt ei ole kuvatud "Töölaud" menüü alampunktina aineeksperdina sisse logitud kasutajale

**Comment by erkisisask** [comment]
Siin taskis kirjeldatud f-s realiseeritakse https://github.com/hariduspilv/koolikott/issues/190 raames.
