### ISSUE TITLE
Raporteerimist kinnitaval modaalil kuvada põhjuse valikuväli ning põhjuse täpsustamiseks tekstiväli

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#202]
Rakenduses õpiobjekti või mõne selle elemendi (tag või kommentaar – vt task 4.1.2) ebasobivaks märkimisel tuleb koos raporteerimise kinnitust pärivas modaalaknas kuvada ka checkbox valik „Põhjus“ raporteerimise põhjuse (põhjuste) valimiseks ning „Põhjuse täpsustus“ mittekohustuslik tekstiväli.

Kui raporteerimine algatati võtmesõna pealt, on „Põhjus“ vaikimisi kohustusliku väärtusega „Võtmesõna“ ning ülejäänud põhjuse märkeruudud ei ole kasutajale kuvatud. 

Väljal „Põhjus“ vähemalt ühe väärtuse valimine on kohustuslik. Kui väljal väärtust ei ole valitud, on modaalakna nupp „Teavita“ mitteaktiivne.

- Antud lahenduse toimimiseks tuleb:
- a.	andmebaasis ImproperContent  tabelisse lisada väli reasonSpecification (varchar(255)), kuhu salvestatakse väljal „Põhjuse täpsustus“ sisestatud tekst.
- Valikuväärtuste valikute jaoks tuleb luua kas koodi või andmebaasi tasemel lahendus:
- a.	Baasi tasemel: luua uus tabel ReportingReason, kuhu sisestada kõik raporteerimise põhjused. Lisaks tuleb ImproperContent tabelis viia reason veerg üle bigint andmetüübi peale ning panna viitama ReportingReason tabeli kirjetele.

**Acceptance criteria**

- [ ] Ebasobivaks raporteerimise modaal peab sisaldama märkeruudu valikuvälja raporteerimise põhjuse valimiseks, kui ei raporteerita otseselt kommentaari või võtmesõna
- [ ] Ebasobivaks raporteerimise modaal peab sisaldama tekstivälja põhjuse täpsustuse sisestamiseks
- [ ] Võtmesõna raporteerimisel on põhjusena kuvatud „Võtmesõna“ ning seda ei ole võimalik muuta
- [ ] Raporteerimise modaalil sisestatud andmed on hiljem kuvatud aineekspertidele ja administraatoritele õpiobjekti mustal bänneril 

[Task 4.1.1 in User Story 4.1 - Materjali/kogumiku raporteerimine.docx](https://github.com/hariduspilv/koolikott/files/1344411/User.Stories.E-koolikott.-.sprindid.1.ja.2.220917.docx)

**Comment by kokakoola** [comment]
Disain:
https://invis.io/5K8KXIETH#/257337372_Teavita-Modaal
- ülemine tekst sinisel ribal sama suur kui varasematel modaalidel.
- ülemise sinise riba tekst muutub vastavalt põhjusele:
  a) mis selllel õpivaral viga on
  b) mis sellel kommentaaril viga on
  c) mis sellel võtmesõnal viga on
see tekst kannab sama rolli, mis ülaltoodud kirjelduses "vaikimisi kohustusliku väärtusega märkeruut" 

Märkeruutudest: 
- katkine link - ETTEPANEK, kinnitamata
- ülejäänud - mu arust pole väga selge tavainimesele, mida tähendab et viga on vormis või metaandmetes. võiks teksti veel mõelda.

Selgitus on textarea max 255 tähemärki. Tähemärkide arvu täitumisel kuvada hoiatust: "Rohkem teksti ei mahu!" (vt mõni koht kus on kasutusel Textangular)

Kinnitus jääb nagu täna on, `toast`

**Comment by erkkijakobson** [comment]
Disain ok, märkeruutudest näitame vaid 3 ja sõnastame esmatõlkes:
- Sobimatu sisu
- Katkine vorm või viit
- Puudus kirjeldavates andmetes

Esimest märkeruutu kasutaja eest ära ei valiks, kuna ta seda kohe maha võtta ei saa, siis on rohkem segadust, kui teha "SAADA" nupp algul halliks ja kuvada sel tooltipi 'Palun vali üks kolmest valikust'

**Comment by erkisisask** [comment]
Tarnitud MS10 tarnega.
