### ISSUE TITLE
Kommentaari raporteerimise funktsionaalsuse lisamine

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#203]
Rakenduses õpiobjekti (materjal/kogumik) detailvaatel kuvatud kommentaaride juurde tuleb lisada hüüumärgi ikooniga nupp kommentaari ebasobivaks raporteerimiseks. Nupu asukoha määrab disainer.

Vastava ikooni kohal hiirega hõljudes (hover) peab süsteem kuvama kasutajale tooltip’i tekstiga „Raporteeri kommentaar ebasobivaks“.

Ikoonil vajutades kuvab süsteem taskis 4.1.1 (Raporteerimist kinnitaval modaalil kuvada põhjuse valikuväli ning põhjuse täpsustamiseks tekstiväli) kirjeldatud ebasobivaks raporteerimise kinnitusmodaali, kus „Põhjus“ vaikimisi kohustusliku väärtusega „Kommentaar“ ning ülejäänud põhjuse märkeruudud ei ole kasutajale kuvatud. 

**Acceptance criteria**

- [ ] Iga õpiobjektiga seotud kommentaari juures on kuvatud hüüumärgiga ikoon kommentaari raporteerimiseks
- [ ] Kommentaari raporteerimisel on põhjusena kuvatud „Kommentaar“ ning seda ei ole võimalik muuta
- [ ] Raporteerimise modaalil sisestatud andmed on hiljem kuvatud aineekspertidele ja administraatoritele õpiobjekti mustal bänneril 
- [ ] Kommentaari ebasobivaks raporteerimise järel peab olema kommentaariga seotud materjal nähtav „Ebasobivad materjalid“ listvaates administraatorile ning vastava ainevaldkonnaga seotud aineeksperdile
- [ ] Kommentaari ebasobivaks raporteerimise järel peab olema kommentaariga seotud kogumik nähtav „Ebasobivad kogumikud“ listvaates administraatorile ning vastava ainevaldkonnaga seotud aineeksperdile

[Task 4.1.2 in User Story 4.1 - Materjali/kogumiku raporteerimine.docx](https://github.com/hariduspilv/koolikott/files/1344411/User.Stories.E-koolikott.-.sprindid.1.ja.2.220917.docx)

**Comment by kokakoola** [comment]
Disain: 
https://invis.io/5K8KXIETH#/257337374_Materjali_Detail_Ko-lbmatu
- Vahetaks ümmarguse alert-ikooni kolmnurkse vastu. Ümmargune kipub info-ikooniga sassi minema. Vanasti ei saanud kohe õiget panna, sest seda polnud raamistusse veel tehtud.
- ikoon on vaikimisi hall, hoveriga sinine, käemäergiga. 
- hoveriga tuleb `tooltip` seletusega, mida see ikoon teeb: "Märgi kõlbmatuks."
- võtmesõna raporteerimisel võiks olla ka samasugune kolmnurkne ikoon. Ka võiks nii ikoon kui +1 olla algselt hallid ja hoveriga muutuda siniseks - hetkel domineerivad liialt

**Comment by erkkijakobson** [comment]
Kolmnurk üheselt arusaadava raporteerimise nupuna sobib:
- protos on kummaline putukamärk, asendada see ka kolmnurgaga
- kuna nõuame autenti, siis toome üldraporteerimise ka nähtavale (3 täpi asemel kui see oleks seal ainuke nupp - kopeeri link kolme täpi alt ära või liigub jagamise alla, kus ta sobivam koht)

Vaja followup Issuet kommentaari eemaldamise kohta kommenteerija, aineksperdi ja admin jaoks.

**Comment by AndersNG** [comment]
Muudame ikonograafiat ja realiseerime vastavalt kinnitatud prototüübile - raporteerimise nuppude asukohad jäävad hetkel nii nagu prototüübis toodud.

Kommentaaridest teine (üldraporteerimise eemaldamine kolme punkti menüüst) nõuab rohkem läbimõtlemist ja kirjeldust ning eraldi disaini. Sellest tulenevalt realiseeritaks eraldi piletina ja mõnes tulevases MS.

**Comment by erkisisask** [comment]
Tarnitud MS10 tarnega.
