### ISSUE TITLE
Raporteerimisel anonüümse kasutaja autentima suunamine

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#204]
Anonüümse kasutaja poolt rakenduses õpiobjekti või mõne selle elemendi (tag või kommentaar – vt task 4.1.2) ebasobivaks raporteerimisel kasutajale enne raporteerimise kinnituse modaalakna kuvamist esitleda autentimise modaali koos teatega „Õppevara ebasobivaks raporteerimiseks tuleb kasutaja sisse logida“.

Autentimise järel peab süsteem kasutajale kuvama ebasobivaks raporteerimise modaalakna, mille taustal õpiobjekti detailvaade, millelt kasutaja raporteerimise algatas.

**Acceptance criteria**

- [ ] Anonüümsele kasutajale on kuvatud nupud/ikoonid õpiobjekti, kommentaari ning võtmesõna raporteerimise algatamiseks
- [ ] Sisselogimise õnnestumise järel jääb kasutaja sama õpiobjekti detailvaatele ning kuvatakse algatatud raporteerimise modaal

[Task 4.1.3 in User Story 4.1 - Materjali/kogumiku raporteerimine.docx](https://github.com/hariduspilv/koolikott/files/1344411/User.Stories.E-koolikott.-.sprindid.1.ja.2.220917.docx)

**Comment by kokakoola** [comment]
Disain:
https://invis.io/5K8KXIETH#/257337373_Tuvasta-Modaal

Pealkirja ja sinise riba suurus sama suur kui teistel, varasematel modaalidel.
- Logodega nupud aitavad kiiremini orienteeruda
- Mobiil-ID on ainuke mis vajab andmete sisestamist - eraldatud teistest nuppudest

**Comment by erkkijakobson** [comment]
Disain valdavalt ok:
1. võtta ära + märk nii placeholder tekstist kui kohustusliku sümbolina, mida sisestada mID jaoks
2. samale disainile viia ka tavaline ja Minu asjade autentimisdialoog (vastavaga päise tekstiga)

**Comment by erkisisask** [comment]
Tarnitud MS10 tarnega.
