### ISSUE TITLE
Õpiobjektide muudatuste alusel  "Muutunud õppematerjalid" listvaate kirjete tekitamine

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#206]
"Muutunud õppematerjalid" loogika täiendamise analüüs.

- Täiendada tabelikirjete tekkimist
- Kombineerida kogumikud ja materjalid
- Ümber nimetada menüüpunkt
- Kirjeldada erijuhud ja süsteemi käitumine nende esinemisel

**Comment by kokakoola** [comment]
Disain:
https://invis.io/5K8KXIETH#/258799507_Muudetud_List

**Comment by erkisisask** [comment]
Lõplikud analüüsid: 
https://github.com/hariduspilv/koolikott/wiki/Muutunud-%C3%B5ppevara-haldamine
https://github.com/hariduspilv/koolikott/wiki/Muutunud-%C3%B5ppevara-loomine

**Comment by erkisisask** [comment]
Tarnitud MS10'ga.
