### ISSUE TITLE
Arendus- ja testkeskkondade eraldamine

### ISSUE THREAD

**Issue by AndersNG** [hariduspilv/koolikott#208]
Vajadus:  luua uus keskkond (rakendus, baas, solr), kus saab testida tarneid.
Vajadus uue keskkonna järgi tuleneb vahetarnete tegemise vajadusest (ja seotud testmise vajadusest). Sellega seoses tekib olukordi, kus master ja develop koodiharud on erinevad - nt develop koodiharus on andmebaas või solr on juba edasi arendatud. Sel juhul ei saa backendi tarne versioonile panna (tehnilised vead) ning peame selle seadma developi versioonile, mis on aga tarnest erinev. Selle puhul tekivad teadmatult front-endi vale versiooni parandusi, mis lõppkasutajale põhjustavad vigu.

Lahendus: luuakse uus keskkond, mis on lähtekoodi master haru peal - tarne testkeskkond.

Tööd, mis teostatakse:

- [ ] Installeerida MySQL andmebaas.
- [ ] Installeerida Solr.
- [ ] Installeerida nodejs/bower 
- [ ] Installeerida ja konfigureerida back-endi rakendus
- [ ] Installeerida ja konfigureerida front-endi rakendus
- [ ] Seadistada andmebaasi dop skeema ja tabelid
- [ ] Seadistada serveri õigused
- [ ] Jenkinsi buildide seadistused ja refaktoor buildide eristamiseks

**Comment by erkisisask** [comment]
Keskkonna seadistamise juhend: https://github.com/hariduspilv/koolikott/wiki/Setup-summary

**Comment by erkisisask** [comment]
Tarnitud MS10 sprindiga.
