### ISSUE TITLE
Solr otsingumootori ja seotud raamistike uuendus

### ISSUE THREAD

**Issue by AndersNG** [hariduspilv/koolikott#209]
Töö sisu:
- Solr otsingumootori versiooni uuendamine versioonilt 6.1.0->6.6.0->7.0.1
- Jersey versiooni uuendamine versioonilt 2.21->2.26
- Kaasnevate uuenduste teostamine. Jetty veebiserver (9.4.6->9.4.7) ja org.apache.abdera (1.1.1->1.1.3)

Eesmärgid:
- Parandada versiooni uuendamisega Solr jõudlust, laiendada funktsionaalsusi ning tagada komponendi jätkusuutlikkus
- Tagada RESTful veebiteenuste raamistiku jätkusuutlikkus ning tõrgeteta töö.

**Comment by erkisisask** [comment]
Tarnitud MS10 tarnega.
