### ISSUE TITLE
Listvaadete uus kujundus töölaua vaates

### ISSUE THREAD

**Issue by AndersNG** [hariduspilv/koolikott#210]
Muudatused:
1. tabeli pealkiri ja otsiväli viia kõrvuti - sobib, rakendada sama kõigile listvaadetele!
2. kui lehekülgi on 1, paginatsiooni rida ei näidata - sobib, rakendada sama kõigile listvaadetele!
3. listvaate otsingu sinine alajoon - sobib, rakendada sama kõigile listvaadetele!
4. listvaate ridadel pole ei noolt ega nuppe - sobib, aga kaaluda kuidas listvaateid siin ühildada!
5. Lisada ka tüübi ikoonile tooltip tüübi enda kohta ja tüübi ikoon teistesse listvaadetesse.

NB! Töölaua vasakmenüü muudatusi ei teostata antud Issue raames.

Viide aluseks olevale prototüübile: https://invis.io/5K8KXIETH#/257209670_Avaleht_Admin

**Comment by kokakoola** [comment]
Disain:
https://invis.io/5K8KXIETH#/258799507_Muudetud_List
https://invis.io/5K8KXIETH#/258535722_Teatatud_Admin

**Comment by erkisisask** [comment]
Tarnitud MS11 tarnepakiga (rakenduse versioon 1.12.0).
