### ISSUE TITLE
Versiooniuuendusel vajalikud küpsised puhtaks

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#211]
Kogesime test- ja toodangu keskkonna uuendamisel v1.10 peale olukorda, kus sisseloginud olekus kasutaja jaoks muutus süsteem kasutamatuks: seanss ei aegu, välja logida ei saa, uut versiooni ei laeta (on tühi leht) kuna vana on 'meeles' - allolev on aga juba kasutaja saadetud pilt:
![image](https://user-images.githubusercontent.com/16906555/31485331-24d70ab6-af3c-11e7-89cd-86c59932689b.png)
ajutine lahendus, mida tavakasutaja otsima ei lähe on Inkognito aken või küpsiste käsitsi eemaldamine. Esineb kõigi sirvikutega, ei esinenud varasemate versiooniuuendustega.

**Comment by erkkijakobson** [comment]
tuvastasime vea kordumise ka väljaspool versiooniuuendust: saime täiendava teavituse kasutajalt ja näen juhuslikult ise ka hetkel ülalolevat seisu toodangus - selle teke võib olla seotud sessiooni aegumisega

**Comment by erkisisask** [comment]
Tarnitud MS10 pakiga.

**Comment by erkkijakobson** [comment]
Muudatus võrreldes varasemaga, et väljalogimisnupp hakkas tööle, kuvatakse aga endiselt tühi leht:
![image](https://user-images.githubusercontent.com/16906555/32113490-20df52e2-bb49-11e7-8a1e-d0d29d523ea7.png)

Lehel on vale (eelmine) versiooni number ja vana autentimisdialoog, login ei toimi (caches vana front end?). Neis sirvikutes, mis varem või kaua aega pole lehel käinud, sh Incognito aknas viga ei esine.

**Comment by erkisisask** [comment]
Versiooni uuendamisel cache tühjendamise jaoks avatud eraldi issue #240 , sest see hoopis eraldiseisev asi kui #211 algselt oli.
