### ISSUE TITLE
Tõlkeressursside haldamine administraatorile

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#212]
Tõlkeressursside mugavamaks haldamiseks tuleks luua administraatori rollile kasutatav vaade, millel on võimalik muuta tõlkeressursside keelelisi väärtuseid (ET, EN, RU).

**Comment by erkisisask** [comment]
Analüüs valmis. Tarnitud MS12 sprindiga.

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati tõsta see töö e-Koolikoti Confluence'i analüüsi backlogi.
