### ISSUE TITLE
Uue materjali lisamise modaalakna muutmine

### ISSUE THREAD

**Issue by AndersNG** [hariduspilv/koolikott#213]
Eesmärk: Lihtsustada kasutajate poolsed uute materjalide lisamist.

Töö sisu: Muudetakse uue materjali lisamise modaali struktuuri ja visuaali, et andmete sisestamine oleks ladusam ning kasutaja jaoks arusaadavam. Vähendatakse kasutajalt nõutavate andmeväljade arvu ning kaotatakse eraldi tabidena modaali osad.

Praegu eksisteeriva modaali vaated uue materjali lisamiseks:
![image](https://user-images.githubusercontent.com/19922635/31719293-98bed5c4-b41b-11e7-8f9a-8892e6a3e2ff.png)
![image](https://user-images.githubusercontent.com/19922635/31719327-b88e4ca4-b41b-11e7-9fcf-a30351dee360.png)
![image](https://user-images.githubusercontent.com/19922635/31719355-d29181de-b41b-11e7-87fb-fbcc6a6ffa93.png)

Uue modaali struktuur ja visuaalne lahendus:
![213](https://user-images.githubusercontent.com/31726683/32441994-68c69744-c302-11e7-83dc-2bda6b28cc01.PNG)

**Comment by erkisisask** [comment]
Lisatud Uue modaali visuaal vastavalt 01.11 koosolekul kokkulepitule.

**Comment by erkisisask** [comment]
Sulgen selle duplikaattaski, läheb realiseerimisele kogumiku tööde epicu käigus, issue https://github.com/hariduspilv/koolikott/issues/254 raames.
