### ISSUE TITLE
Muutunud õppevara haldamine -> Andmebaasimuudatused muutunud materjali lingi salvestamiseks ja soft delete kasutamiseks

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#214]
Muutunud õppevara tabelikirje tekitamiseks materjali lingi muutmise järel on vajalik andmebaasis ChangedLearningObject tabelit täiendada text tüüpi andmeväljaga materialSource. Väljale materialSource salvestatakse materjali lingi muutmisel tekkinud ChangedLearningObject puhul materjalile lisatud uus link.

Acceptance criteria:
- [ ] Muutunud õppevara andmebaasikirje võimaldab materjali lingi salvestamist selle muutmise tulemusel, et oleks võimalik taastada muutmise eelne seis
- [ ] Muutunud õppevara andmebaasikirje alusel on võimalik tuvastada kas muudatused on üle vaadatud
- [ ] Muutunud õppevara andmebaasikirje alusel on võimalik tuvastada kas õppevara kustutati või raporteeriti katkiseks/ebasobivaks enne muudatuste ülevaatamist
- [ ] Muutunud õppevara andmebaasikirje alusel on võimalik tuvastada kas muudatus tühistati manuaalselt
- [ ] Muutunud õppevara andmebaasikirje alusel on võimalik tuvastada kas muudatus kinnitati manuaalselt, kinnitati automaatselt või lükati tagasi
- [ ] Muutunud õppevara andmebaasikirje alusel on võimalik tuvastada muutunud õppevara ülevaatuse aeg ja teostaja

Analüüs:
https://github.com/hariduspilv/koolikott/wiki/Muutunud-%C3%B5ppevara-haldamine#user-story-andmebaasimuudatused-muutunud-materjali-lingi-salvestamiseks-ja-soft-delete-kasutamiseks

**Comment by OlegPahhomov** [comment]
Tabeli nimi muutus. ChangedLearningObject -> ReviewableChange.
ReviewableChange kirjeldab paremini objekti olemust. Ülevaadatavad muudatused.

**Comment by erkisisask** [comment]
Tarnitud MS11 tarnepakiga (rakenduse versioon 1.12.0).
