### ISSUE TITLE
Muutunud õppevara haldamine -> Muutunud õppevara bänner

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#216]
Õpiobjektide (kogumik/materjal) detailvaadetel, mis on seotud mõne ChangedLearningObject kirjega tuleb administraatori või aineeksperdi rollis olevale kasutajale kuvada musta bännerit teatega: „Õppevara on muutunud“.

Acceptance criteria:
- [ ] Aktiivse ChangedLearningObject objektiga seotud õppevara detailvaatel on aineeksperdile ja administraatorile kuvatud bänner märkimaks, et õppevara on muudetud
- [ ] Administraator ja aineekspert saavad muutunud õppevara muudetused kinnitada muudetud õppevara bänneri checkmark ikooniga nupust
- [ ] Administraator ja aineekspert saavad muutunud õppevara muudetused tühistada muudetud õppevara bänneri undo ikooniga nupust
- [ ] Kui muudatus on seotud süsteemse võtmesõna lisamisega, eemaldab süsteem muudatuse tühistamisel nii süsteemse võtmesõna kui ka sellega seotud liigituse
- [ ] Muudetud õppevara bänneri checkmark ikooniga nupu abil muudatuste kinnitamise teostaja ja teostamise aeg salvestatakse baasi
- [ ] Muudetud õppevara bänneri undo ikooniga nupu abil muudatuse tühistamise teostaja ja teostamise aeg salvestatakse baasi
- [ ] Muudetud õppevara kinnitamise/tühistamise järel õppevara enam „Muutunud õppevara“ listis ei kuvata
- [ ] Muudetud õppevara kinnitamise/tühistamise järel salvestatakse baasi muudatuse ülevaatamise tulemus (kinnitatud/tühistatud)
- [ ] Muudatusega seotud süsteemsed võtmesõnad on värvidega eristatud teistest võtmesõnadest

Analüüs:
https://github.com/hariduspilv/koolikott/wiki/Muutunud-%C3%B5ppevara-haldamine#user-story-muutunud-%C3%B5ppevara-b%C3%A4nner

**Comment by kokakoola** [comment]
https://invis.io/5K8KXIETH#/258799506_Muudetud_Banner

**Comment by erkisisask** [comment]
Tarnitud MS11 tarnepakiga (rakenduse versioon 1.12.0).
