### ISSUE TITLE
Admini vasakmenüü korrastamine

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#222]
Analüüs: Link allpool.
Disain: Lingid allpool.

**Acceptance criteria**
- [ ] Sisselogimise eelselt on vaikimisi avatud "Sisukord" menüüpunkt ja "Minu asjad" menüüpunkt suletud
- [ ] Sisselogimise eelselt on "Minu asjad" menüüpunkti alampunktidel vajutades kuvab süsteem sisselogimise modaalakna
- [ ] Sisselogimise järgselt on vaikimisi avatud "Minu asjad" menüüpunkt ja "Sisukord" menüüpunkt suletud
- [ ] Aineeksperdile on kuvatud "Minu asjad" menüüpunkti all nii kasutaja kogumikud, materjalid ja lemmikud kui ka aineeksperdi töö listvaated: "Teatatud õppevara", "Uus õppevara", "Muudetud õppevara".
- [ ] Administraatorile on "Minu asjad" menüüpunkti all kuvatud lisaks aineeksperdile kuvatud punktidele ka "Aineeksperdid", "Piiratud kasutajad" ja "Kustutatud õppevara"
- [ ] Uus, teatatud, muudetud ja kustutatud õppevara menüüpunktid viitavad listvaatele, kuhu on koondatud nii vastava staatusega kogumikud kui uued materjalid
- [ ] Aineeksperdi/adminsitraatori töölaua listvaatesse (uus, teatatud, muudetud, kustutatud) kuuluva materjali detailvaatel olles on tumeda tooniga eristatud listvaate menüüpunkt, mille alla antud materjal kuulub
- [ ] Aineeksperdi/adminsitraatori töölaua listvaatesse (uus, teatatud, muudetud, kustutatud) kuuluva materjali detailvaatel olles on "Minu asjad" menüüpunkt vaikimisi avatud ja "Sisukord" suletud
- [ ] Aineeksperdi/adminsitraatori töölaua listvaatesse (uus, teatatud, muudetud, kustutatud) kuuluva kogumiku detailvaatel olles on tumeda tooniga eristatud listvaate menüüpunkt, mille alla antud kogumik kuulub
- [ ] Aineeksperdi/adminsitraatori töölaua listvaatesse (uus, teatatud, muudetud, kustutatud) kuuluva kogumiku detailvaatel olles on nii "Minu asjad" kui kogumiku sisukorra menüüpunkt (kogumiku pealkirjaga) vaikimisi avatud

**Comment by kokakoola** [comment]
Flow alates hetkest kui moderaator/admin tuleb lehele kuni töölauale jõudmiseni, käitumine eri lehtedel:
https://invis.io/5K8KXIETH#/257209669_Avaleht_Anonu-u-mne
Vasakmenüü uus struktuur (admini näitel)
https://invis.io/5K8KXIETH#/258535722_Teatatud_Admin

**Comment by JaakL** [comment]
Vasakmenüü käitumine kirjeldatud ära järgneval GH Wiki lehel:
https://github.com/hariduspilv/koolikott/wiki/Administraatori-ja-aineeksperdi-vasakmen%C3%BC%C3%BC

**Comment by erkisisask** [comment]
Tarnitud MS11 tarnepakiga (rakenduse versioon 1.12.0).
