### ISSUE TITLE
Administraatorile testimiseks rollivahetus

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#223]
Hetkel saab arendus- ja värskes testkeskkonnas erinevaid rolle testida eelseadistatud URLidelt, mis on eeltoodangus ja toodangus turvapõhimõttel keelatud. Neis keskkondades on aga samuti vajadus teatud kasutajatel erinevates rollides teenust kasutada: lihtsustamaks vastuvõtu testimist ja kasutajatoe osutamist.

Ettepanek asendada URLi põhine testkasutaja login kõigis 4 keskkonnas üheselt baasis eraldiseisva admin tabeliga, millesolevad isikukoodid näevad konto nupu all eraldi real järgmisi rolle, users tabeli roll on esiletõstetud:
- Eesnimi Perenimi
- **Admin** | Ekspert | Kasutaja | Piiratud
- Välju

vajutus teise rolli peal teostab baasimuudatuse (vahetab rolli users tabelis) ning vajadusel taaslaeb lehe.

**Comment by erkisisask** [comment]
Analüüs valmis, tarnitud MS12 sprindiga.

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
