### ISSUE TITLE
Õppevara otsing -> mitmesõnalise otsingufraasiga otsing

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#227]
Kõikides rollides kasutajatel on võimalik teostada E-koolikotis otsing täpse fraasi alusel, kasutades selleks fraasi piiritlemiseks jutumärke, et leida oma soovidele täpselt vastavaid õpiobjekte.

Funktsionaalsuse vastuvõtmise kriteeriumid (acceptance criteria):

- [ ] Jutumärkidega otsinguvaade sisaldab kahte tekstiteadet – üks seotud jutumärkidega fraasi otsingutulemustega, teine ilma jutumärkideta otsingufraasi otsingutulemustega
- [ ] Täpsed vasted jutumärkidega fraasile on eraldatud teistest otsingutulemustest (jutumärkideta otsingutulemuste vasted)

Analüüs:
https://github.com/hariduspilv/koolikott/wiki/Dokumentatsioon-(Feature):-%C3%95ppevara-otsing#user-story-mitmes%C3%B5nalise-otsingufraasiga-otsing

**Comment by kokakoola** [comment]
Disain ja flow: https://invis.io/5K8KXIETH#/257209669_Avaleht_Anonu-u-mne
Lisaks kirjeldatud ka tänane flow, kus täppisotsingu kasutamine kasutaja otsitavast teadmatusse jätab.

**Comment by erkisisask** [comment]
Front - mitmesõnalise otsingufraasiga otsingu äriloogika teostamine - 7
Back - äriloogika ja testide täiendamine uue funktsionaalsuse toetamiseks - 12
Testimine - 6

**Comment by erkisisask** [comment]
Issue sulgemisele, sest ei ole enam relevantne, sest kogu otsingu funktsionaalsus saab analüüsi käigus parendusettepanekud.
