### ISSUE TITLE
Statistika aineekspertide tegevuste kohta

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#228]
Luua administraatori rollis kasutale funktsionaalsus aineekspertide sisuhalduse tegevuste alusel statistika pärimiseks.

Analüüsiülesanne kerkis esile issue #177 punktist 5: "Administraatorile peab toimingust tekkima ajaline, nt kvartaalne statistika ekspertide ja valdkondade kaupa."

Kasutajatel rollis _administraator_ (edaspidi: administraator) on võimalik teostada E-koolikotis päringuid õppevara modereerimise statistika kohta, et omada ülevaadet aineekspertide rollis olevate kasutajate (edaspidi: ekspertide) töö üle.

**Detailid:**

Administraatorile on loodud eraldi vaade, mis võimaldab teostada erinevate sisendparameetrite alusel päringuid ekspertide tegevuste statistika kohta.

Statistikapäringute vaade sisaldab:

- Statistikapäringu filtrit:
  - Andmeväljad päringu tingimuste seadistamiseks.
- Statistikapäringu tulemused tabelina:
  - Iga otsingutingimustele vastava individuaalse eksperdi tegevustega seotud õppevara statistika.

Administraator saab päringutulemuste alusel genereerida ka _xlsx, xls ja csv_ formaatides väljundfaili ning selle otse enda arvutisse alla laadida.

Tulemuste alusel genereeritud faile E-koolikotis ei hoiustata.

**Acceptance criteria'd:**
- [ ] Statistikapäringute vaatele navigeerimise vastuvõtukriteeriumid kirjeldatud [spetsifikatsioonis](https://github.com/hariduspilv/koolikott/wiki/User-story:-statistikap%C3%A4ringute-vaatele-navigeerimine)
- [ ] Statistikapäringu vaate filtri kasutamise vastuvõtukriteeriumid kirjeldatud [spetsifikatsioonis](https://github.com/hariduspilv/koolikott/wiki/User-story:-Statistikap%C3%A4ringu-vaate-filtri-kasutamine)
- [ ]  Statistikapäringu tulemuste tabeli vastuvõtukriteeriumid kirjeldatud [spetsifikatsioonis](https://github.com/hariduspilv/koolikott/wiki/User-story:-Statistikap%C3%A4ringu-tulemuste-tabel)
- [ ]  Statistikapäringu tulemuste väljundi ekspordivõimaluste vastuvõtukriteeriumid kirjeldatud [spetsifikatsioonis](https://github.com/hariduspilv/koolikott/wiki/User-story:-Statistikap%C3%A4ringu-tulemuste-v%C3%A4ljundi-eksportimine)

## [Statistika disain siin](https://invis.io/5K8KXIETH#/272712777_Statistika-1)

**Comment by erkisisask** [comment]
Analüüs valmis. Tarnitud MS12 sprindiga.

**Comment by kokakoola** [comment]
Prototüüp (flow, klikatav) ja disain: https://invis.io/5K8KXIETH#/272712777_Statistika-1

**Comment by erkisisask** [comment]
Tarnitud MS15 tarnepakiga (rakenduse versioon 1.16.0) 06.03.2018a.
