### ISSUE TITLE
Tag'i olemasolul uue samanimelise tekitamine

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#231]
MS10 tööde testimise käigus testija avastas nüansi, et kui avada portfoolio või materjal ning seejärel sisestada mingi suvalise nimega tag, siis tag lisatakse kenasti ära. 
Aga kui seejärel sisestada uuesti täpselt sama nimetusega tag, siis lisatakse ka see uuesti ära ja kasutajale midagi ei teavitada.
Arendaja vaatas koodist järele ning selline f-s on realiseeritud 2016 aastal, seega justkui oleks see nii teadlikult tollal ka tehtud.

Milline peaks olema korrektne käitumine uue sama nimega tagi lisamisel? Paluks siia kirjeldada acceptance criteriad, siis Jaak saab vajadusel täpsemad nõuded arenduse jaoks kirjeldada.

**Comment by JaakL** [comment]
1. Täpsustus olemasoleva funktsionaalsuse osas:
* Proovides lisada õppevarale võtmesõna, mis on õppevaral juba olemas, toimib süsteem järgnevalt:
  * Sisestusklahvi (enter) vajutamisel tühjendab tekstivälja
  * Uut võtmesõna sildi elementi ei teki (ega ka uut võtmesõna objekti baasi)
  * Teadet selle kohta, et võtmesõna on juba olemas, ei kuvata
2. Sellest tulenevalt küsimused:
* Kas on vajalik indikeerida, et sisestatud võtmesõna on juba õppevaral olemas?
  * Näiteks: viidata olemasolevale võtmesõna elemendile, värvides selle ajutiselt teist värvi?
  * Kas sellises olukorras on kasutaja segaduse vältimiseks vajalik kuvada teade, et võtmesõna on juba õppevarale lisatud?
  * Kas on vajalik välja kuvada ka teistele kasutajatele, et võtmesõna on lisatud mitme inimese poolt?
* Kui vajadus selliseks indikeerimiseks puudub, kas olemasolev lahendus on sobiv?
  * Nimelt, kasutajal võib tekkida segadus – miks midagi ei muutu, kuigi ta sisestas võtmesõna ja süsteem võtmesõna välja tühjendas. Kasutaja ootus on, et viimati sisestatud võtmesõna on kuvatud kõige viimase võtmesõnana. Hetke funktsionaalsuse alusel nii ei juhtu.

**Comment by erkisisask** [comment]
Teema hetkel endiselt aktuaalne. Võtmesõnade lisamine ja kustutamine toimib kenasti, kuid tuleks välja mõelda ka lahendus, kui kasutaja hakkab uuesti samanimelist võtmesõna sisestama. 

Kuid võimalik, et probleem kaob, kui realiseeritakse piirang, et kasutaja saab ühele õppevarale sisestada maksimaalselt 15 võtmesõna. See hulk on piisavalt väike, et kasutaja saaks silmaga olemasolevad üle vaadata ja veenduda, kas sisestatav võtmesõna sisaldub nende 15 hulgas või mitte.

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
