### ISSUE TITLE
Süsteemiülene ikoonide ühtlustamine

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#232]
Vastavalt 13.10 peetud [kõnekoosolekul](https://projektid.hitsa.ee/pages/viewpage.action?pageId=13503250)  läbi räägitud ikoonide kasutusele, tuleb süsteemiüleselt viia ikoonid üle kokkulepitud (ja disaini prototüübis kasutatud) ikoonidele ja tagada ühtlane ikoonide kasutamine süsteemiüleselt.

Kokkulepitud ikoonid on välja toodud Wiki lehel: [Ikoonid](https://github.com/hariduspilv/koolikott/wiki/Ikoonid)

- [ ] E-koolikotis kasutatavad ikoonid vastavad kokkulepitud ikonograafiale

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
