### ISSUE TITLE
Süsteemiülene terminite ühtlustamine

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#233]
Vastavalt 13.10 peetud [kõnekoosolekul](https://projektid.hitsa.ee/pages/viewpage.action?pageId=13503250)  läbi räägitud terminite kasutusele, tuleb süsteemiüleselt viia terminid üle kokkulepitud (ja disaini prototüübis kasutatud) terminitele ja tagada nende ühtlane kasutamine süsteemiüleselt.

Kokkulepitud terminid on välja toodud Wiki lehel: [Terminoloogia](https://github.com/hariduspilv/koolikott/wiki/Terminoloogia)

- [ ] E-koolikotis kasutatavad terminid vastavad kokkulepitud terminoloogiale ja ei kasutata samade asjade väljendamiseks sünonüümseid termineid

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati tõsta see töö e-Koolikoti Confluence'i analüüsi backlogi.
