### ISSUE TITLE
Õppevara otsing -> Otsinguvälja filtri ikoonile täpsustav tekst

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#234]
Vastavalt 13.10 peetud [kõnekoosolekul](https://projektid.hitsa.ee/pages/viewpage.action?pageId=13503250) kokkulepitule, tuleb E-koolikoti _navbar_'il oleva otsinguvälja filtri (täpse otsingu) avamise nupu juurde lisada selgitav tekst "Filter", lihtsustamaks kasutajale selle funktsionaalsuse üles leidmist.

- [ ] Filtri ikooniga nupu kohal hiirega hõljudes kuvab süsteem ka tooltip'i "Ava täpne otsing".
- [ ] Kui täpne otsing on avatud, kuvab süsteem antud samal kohal risti ikooniga nupu (tooltip'iga "Sulge täpne otsing"), millel vajutades süsteem sulgeb filtri ning tühjendab otsinguvälja.

Vajadus on kirjeldatud ka Wiki [lehel](https://github.com/hariduspilv/koolikott/wiki/Dokumentatsioon-(Feature):-%C3%95ppevara-otsing#user-story-otsing-t%C3%BChja-otsinguv%C3%A4lja-alusel-234).

**Comment by kokakoola** [comment]
DIsain:
https://invis.io/5K8KXIETH#/258535722_Teatatud_Admin

**Comment by erkisisask** [comment]
10

**Comment by erkisisask** [comment]
@erkkijakobson , lähtudes 13.oktoobril toimunud koosoleku punktist nr 6, siis milline konkreetselt peaks olema tooltipi tekst avatud/suletud olekus https://projektid.hitsa.ee/pages/viewpage.action?pageId=13503250 ?

**Comment by erkisisask** [comment]
See issue saab tarnitud #253 raames, ei kuulu täiendavalt arveldamisele.
