### ISSUE TITLE
X-tee versiooniuuendus

### ISSUE THREAD

**Issue by OlegPahhomov** [hariduspilv/koolikott#235]
Loetelu X-tee versiooniuuendusega seotud tegevustest:
- Analüüs, kuidas praegu on EHISega liidestus on tehtud
- Uue korrektse näidispäringu küsimine EHISest
- Xtee6 uue headeri struktuuri arendus ja testimine
- Konfiguratsiooni loogika täiendamine versiooni valimiseks

**Comment by erkisisask** [comment]
Tarnitud MS12 tarnepakiga (rakenduse versioon 1.13.0).
