### ISSUE TITLE
Teatatud õppevara haldamine -> Ebasobivate ja katkiste listvaadete konsolideerimine

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#236]
Konsolideerida ühese "[Teatatud õppevara](https://projects.invisionapp.com/share/5K8KXIETH#/screens/258535722_Teatatud_Admin)" vaate alla kogumikud ja materjalid, mis on teatatud ebasobiva või katkisena. 

Konsolideeritud listvaade on kirjeldatud: [Teatatud õppevara listvaade](https://github.com/hariduspilv/koolikott/wiki/Teatatud-%C3%B5ppevara-haldamine#user-story-ebasobivate-ja-katkiste-listvaadete-konsolideerimine-236)
Konsolideeritud aineeksperdi/admini menüü vorm ja käitumine on kirjeldatud: [Administraatori ja aineeksperdi vasakmenüü](https://github.com/hariduspilv/koolikott/wiki/Administraatori-ja-aineeksperdi-vasakmen%C3%BC%C3%BC)

Acceptance criteria:
- [ ] „Teatatud õppevara“ menüüvalik ja listvaade on koondanud järgnevad menüüvalikud ja listvaated
-- [ ] "Katkised materjalid"
-- [ ] "Katkised kogumikud"
-- [ ] "Ebasobivad materjalid"/"Teatatud materjalid"
-- [ ] "Ebasobivad kogumikud/Teatatud kogumikud"
- [ ] „Teatatud õppevara“ listvaate tabel sisaldab katkise ja ebasobivana teatatud õppevara kirjeid
- [ ] Kui ühe õppevaraga on seotud mitu teatamist on „Teatatud õppevara“ listis kuvatud Teataja ja Teatatud veeru väärtused vastavalt kirjeldatud tingimustele.
- [ ] „Teatatud õppevara“ menüüvalik on kuvatud nii administraatoritele kui ka aineekspertidele
- [ ] „Teatatud õppevara“ listvaates on aineeksperdile kuvatud tabeliridadena ainult aktiivsed teatatud materjalid ja kogumikud, mille valdkond on seotud ka aineeksperdi valdkonnaga
- [ ] Aineeksperdile kuvatud „Teatatud õppevara“ menüüvaliku juures on kuvatud ainult aktiivsed teatatud materjalide ja kogumike arv, mille valdkond on seotud ka aineeksperdi valdkonnaga
- [ ] Administraatorile kuvatud „Teataud õppevara“ listvaates on tabeliridadena kuvatud kõik aktiivsed teatatud materjalid ja kogumikud
- [ ] Administraatorile on kuvatud „Teatatud õppevara“ vaates kõikide valdkondadega seotud aktiivsed teatatud kogumikud ja materjalid
- [ ] Administraatorile on kuvatud „Teatatud õppevara“ menüüvaliku kõrval kõikide valdkondadega seotud aktiivsete teatatud kogumike ja materjalide arv

**Comment by erkisisask** [comment]
Tarnitud MS11 tarnepakiga (rakenduse versioon 1.12.0).
