### ISSUE TITLE
Kogumiku peatükkide haldamine -> Eemaldada peatükkide haldamisest üleliigsed elemendid

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#244]
Eemaldada peatükkide haldamisest üleliigsed elemendid.

Acceptance criteria:
- [ ] Materjali positsiooni liigutamise noolenupud on eemaldatud
- [ ] „+ Alampeatükk“ nupp on peatüki jalusest eemaldatud
- [ ] „+ Materjal“ nupp on peatüki jalusest eemaldatud
- [ ] Peatüki kustutamise nupp on kuvatud peatüki paremal pool, kui antud peatükki aktiivselt ei hallata.
- [ ] Kui kogumikus on 1 peatükk, ei ole kustutamise nupp kuvatud.

Taski kirjeldus wikis: https://github.com/hariduspilv/koolikott/wiki/Task:-Eemaldada-peat%C3%BCkkide-haldamisest-%C3%BCleliigsed-elemendid

Task kuulub featuuri https://github.com/hariduspilv/koolikott/wiki/Feature:-kogumiku-peat%C3%BCkkide-haldamine koosseisu.

**Comment by kokakoola** [comment]
disain: 
https://invis.io/5K8KXIETH#/239878529_2-_Kogumik_algus_m-rks-na

**Comment by erkisisask** [comment]
- Eemaldada kogumiku peatüki jalusest nupp „+ Alampeatükk“ - 1
- Eemaldada kogumiku peatükis oleva materjali juurest noolenupud antud peatükis materjalide järjekorra seadistamiseks - 1
- Eemaldada dropdown nupp „+Materjal“ peatüki jalusest - 1
- Antud nupuga seotud funktsionaalsused (uue ja olemasoleva materjali lisamine) viia üle uutele vormi nuppudele - 3
- Muuta peatüki kustutamise nupu asukohta - 1
- Peatüki kustutamiseks on nupp kuvatud vaid siis, kui kogumikus on enam kui 1 peatükk - 2
- testimine 5

**Comment by erkisisask** [comment]
Tarnitud MS12 tarnepakiga (rakenduse versioon 1.13.0).
