### ISSUE TITLE
Kogumiku peatükkide haldamine -> Peatükkide haldamise vormiplokid

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#245]
Kasutajatel rollis tavakasutaja, aineekspert, administraator on võimalik kogumiku muutmise vormil hallata peatüki sisu, kasutades selleks peatüki kõrval kuvatud kolme vormiplokki: Lisa sisu, Küljenda, Lisa sisuplokk.

Acceptance criteria:
- [ ] Peatüki sisu haldamise nupud on kuvatud aktiivselt hallatava peatüki kõrval olevas vormiplokis.
- [ ] Kasutajatel rollis tavakasutaja, aineekspert, administraator on kogumiku muutmise vormil peatüki kõrval kuvatud kolme vormiplokki: Lisa sisu, Küljenda, Lisa sisuplokk.

Story kirjeldus wikis: https://github.com/hariduspilv/koolikott/wiki/User-story:-peat%C3%BCkkide-haldamise-vormiplokid

Story kuulub featuuri https://github.com/hariduspilv/koolikott/wiki/Feature:-kogumiku-peat%C3%BCkkide-haldamine koosseisu.

**Comment by kokakoola** [comment]
disain: 
https://invis.io/5K8KXIETH#/240041014_4-_Kogumiku_algus_1_tulp

**Comment by erkisisask** [comment]
- Hallatava peatüki kõrval (paremal pool) on kasutajatele kuvatud kolme vormiplokki - 3
- „Lisa sisu“ vormiploki nupud - 2
- „Küljenda“ vormiploki nupud - 2
- "Lisa sisuplokk“ nupud - 1
- frondi loogika, cssi, javascripti loomine nuppude toimimiseks - 12
- testimine - 6

**Comment by erkisisask** [comment]
Tarnitud MS12 tarnepakiga (rakenduse versioon 1.13.0).
