### ISSUE TITLE
Kogumiku peatükkide haldamine -> Peatükkide järjekorra muutmine sisukorras

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#246]
Kasutajatel rollis tavakasutaja, aineekspert, administraator on võimalik kogumiku muutmise vormil muuta peatükkide järjekorda, lohistades peatüki pealkirja sisukorras edasi või tagasi.

Acceptance criteria:
- [ ] Peatüki asukoht sisukorras muutub vastavalt positsioonile sisukorras, mille kohal peatükki lohistades hiireklahv vabastati
- [ ] Peatüki asukoha muutmisel sisukorras, muutub koheselt ka peatüki asukoht kogumikus vastavalt sisukorras määratud uuele asukohale
- [ ] Peatüki asukoht sisukorras ei muutu, kui peatüki pealkirja lohistades vabastatakse hiireklahv mõne muu elemendi kohal kui sisukord
- [ ]  Lohistatava ala kohal hiirega hõljudes muutub hiirekursori kuju indikeerimaks kasutajale, et tegemist on lohistatava elemendiga 

Story kirjeldus wikis: https://github.com/hariduspilv/koolikott/wiki/User-story:-peat%C3%BCkkide-j%C3%A4rjekorra-muutmine-sisukorras

Story kuulub featuuri https://github.com/hariduspilv/koolikott/wiki/Feature:-kogumiku-peat%C3%BCkkide-haldamine koosseisu.

**Comment by erkisisask** [comment]
- Peatükkide järjekord on hallatav ekraani vasakul kuvatud sisukorras peatükkide pealkirju hiirega üles/alla lohistades - 5
- Peatükki lohistamiseks on sisukorras iga peatüki kõrval kuvatud ikoon, mida on võimalik kasutada peatüki asukoha muutmiseks - 2
- Ikooni ümber on täiendava puhverala loomine - 3
- Peatüki liigutamiseks järjekorras ettepoole saab kasutaja ikooni peal hiirega vajutada ja seejärel selle õigesse kohta lohistada - 5
- Angulari drag & drop komponendi juurutamine - 8
- Testimine - 6

**Comment by erkkijakobson** [comment]
kursori muutumine ja/või tooltip peab kasutajale andma teada lohistamise võimalusest

**Comment by erkisisask** [comment]
Tarnitud MS12 tarnepakiga (rakenduse versioon 1.13.0).
