### ISSUE TITLE
Kogumiku peatükkide haldamine -> Peatükkide järjekorra muutmine nuppudega

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#247]
Kasutajatel rollis tavakasutaja, aineekspert, administraator on võimalik kogumiku muutmise vormil muuta peatükkide järjekorda kasutades peatüki kõrval kuvatud üles/alla nuppe.

Acceptance criteria:
- [ ] Kui kogumikus on rohkem kui 1 peatükk, on iga peatüki kõrval nupud peatüki järjekorras üles/alla liigutamiseks, millel vajutades liigutab süsteem peatükki (koos alampeatükkidega) ühe võrra üles/alla.
- [ ] Kõige ülemisel peatükil on aktiivne vaid alla liigutamise nupp.
- [ ] Kõige alumisel peatükil on aktiivne vaid üles liigutamise nupp.

Story kirjeldus wikis: https://github.com/hariduspilv/koolikott/wiki/User-story:-peat%C3%BCkkide-j%C3%A4rjekorra-muutmine-nuppudega

Story kuulub featuuri https://github.com/hariduspilv/koolikott/wiki/Feature:-kogumiku-peat%C3%BCkkide-haldamine koosseisu.

**Comment by kokakoola** [comment]
disain: 
https://invis.io/5K8KXIETH#/240235404_12-_Kogumik_formaadi_pilti

**Comment by erkisisask** [comment]
- Kui kogumikus on rohkem kui 1 peatükk (üles/alla liigutamise nupud) - 4
- Kõige ülemisel piieatükil on aktiivne vaid alla lgutamise nupp - 2
- Peatüki kõrval oleva „Alla“ nupu loogika realisatsioon - 4
- Kõige alumisel peatükil on aktiivne vaid üles liigutamise nupp - 2
- Peatüki kõrval oleva Üles nupu loogika realisatsioon - 4
- Baasisalvestuse loogika täiendamine - 4
- Testimine - 4

**Comment by erkisisask** [comment]
Tarnitud MS12 tarnepakiga (rakenduse versioon 1.13.0).
