### ISSUE TITLE
Kogumikule meediafaili lisamine -> Meediafaili lisamise modaal

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#249]
Kasutajatel rollis tavakasutaja, aineekspert, administraator on võimalik kogumiku muutmise vormil sisuplokki meediafailide vistutamiseks kasutada meediafaili lisamise modaalvormi, mis sisaldab välju:

- Link meediafailile (URL tekstiväli, **kohustuslik**))
- Pealkiri (tekstiväli, **kohustuslik**)
- Autor (tekstiväli, **kohustuslik**)
- Olen ise autor (märkeruut; märkimisel täidab süsteem "Autor" välja kasutaja nimega ja muudab "Autor" välja mittemuudetavaks)
- Allikas (tekstiväli, **kohustuslik**)
- Litsentsi tüüp (rippmenüüvalik, **kohustuslik**)

Story kirjeldus wikis: https://github.com/hariduspilv/koolikott/wiki/User-story:-meediafaili-lisamise-modaal

Story kuulub featuuri https://github.com/hariduspilv/koolikott/wiki/Feature:-kogumikule-meediafaili-lisamine koosseisu.

Näidis:
![meedia lisamine to-be](https://user-images.githubusercontent.com/31726683/34098379-c52b814a-e3e4-11e7-8ff1-9e2599a97a11.png)

15.12 uuendatud disain: https://projects.invisionapp.com/share/5K8KXIETH#/screens/240723649_Lisa_Meedia

Acceptance criteria:
- [ ] Meediafaili lisamise modaalvorm avaneb „Lisa meediafail“ nupuvajutuse järel
- [ ] Modaalvormi sulgemisel süsteem valideerib faililaiendi sobivust 
- [ ] Ebasobiva laiendi puhul kuvab süsteem kasutajale teadet ja ei sulge meediafaili lisamise modaalvormi.
- [ ] Kui lingitud meediafaili formaat on ebasobiv, kuvab süsteem teate: "Lisatud meediafaili formaat ei ole kasutatav. Sobivad formaadid ja allikad: [sobivate formaatide nimekiri]."
- [ ] Modaalil teostatakse vajalikud kohustuslike väljade täitmise kontrollid vastavalt spetsifikatsioonis kirjeldatule.
- [ ] Modaalvormil olev nupp „Lisa meedia“ on aktiivne vaid siis, kui kõik kohustuslikud väljad on täidetud.
- [ ] Modaalvormi lõpetamisel nupust „Lisa meedia“ kuvab süsteem kasutajale kogumiku vormi, kus hallatavasse peatükki on lisatud antud meediafail embedded elemendina.
- [ ] "Olen ise autor" märkimisel täidab süsteem "Autor" välja kasutaja ees- ja perenimega ning  muudab "Autor" välja mittemuudetavaks.

**Comment by kokakoola** [comment]
disain: https://invis.io/5K8KXIETH#/240723649_Lisa_Meedia

**Comment by erkisisask** [comment]
- Meediafaili lisamise modaalvormi tööd - 6
- Failiformaadi sobivuse valideerimine vormi sulgemisel - 14
- Ebasobiva failiformaadi puhul kuvatakse kasutajale vastavat teadet - 4
- Modaalvormil kohustuslike väljade kontrollid - 6
- Baasisalvestuse loogika ja kontrollide täiendamised - 8
- automaattestide täiendamine - 12
- Testimine - 16

**Comment by erkisisask** [comment]
Tarnitud MS13 tarnepakiga (rakenduse versioon 1.14.0).
