### ISSUE TITLE
Kogumikule meediafaili lisamine -> Meediafaili vistutamine

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#250]
Kasutajatele rollis tavakasutaja, aineekspert, administraator on sisuplokki lisatud meediafailid kuvatud vistutatud kujul koos lisainformatsiooniga.

Acceptance criteria:
- [ ] Toimib JPG faililinkide embed’imine
- [ ] Toimib PNG faililinkide embed’imine
- [ ] Toimib GIF faililinkide embed’imine
- [ ] Toimib MP3 faililinkide embed’imine
- [ ] Toimib OGG faililinkide embed’imine
- [ ] Toimib WAV faililinkide embed’imine
- [ ] Toimib MP4 faililinkide embed’imine
- [ ] Toimib OGV faililinkide embed’imine
- [ ] Toimib WEBM faililinkide embed’imine
- [ ] Toimib YouTube linkide embed’imine
- [ ] Toimib Soundcloud linkide embed’imine
- [ ] Vistutatud elemendi jaluses on meediafaili andmed

Story kirjeldus wikis: https://github.com/hariduspilv/koolikott/wiki/User-story:-meediafaili-vistutamine

Story kuulub featuuri https://github.com/hariduspilv/koolikott/wiki/Feature:-kogumikule-meediafaili-lisamine koosseisu.

**Comment by kokakoola** [comment]
disain: https://invis.io/5K8KXIETH#/261073319_Kogumik_Valmis

**Comment by erkisisask** [comment]
- Pildifaili formaatide (jpg, png, gif) vistutamine - 10
- Kolmandate osapoolte formaatide (Youtube, Soundcloud) vistutamine - 16
- Video-ja helifailidest formaatide (MP4 ja MP3) vistutamine - 20
- kasutaja poolt lisatud meediafailid on kogumiku peatükis kuvatud vistutatud elementidena - 8
- Vistutatud elemendi jaluses on kasutajatele kuvatud meediafaili lisamise vormil sisestatud andmed - 2
- Vistutatud meediafailil topelt hiirekliki tegemisel kuvab süsteem antud meediafaili modaalvormi - 6
- Vaikimisi on kõik meediafailid vistutatud sisuploki kogulaiuses - 4
- vistutatud failide salvestuse loogika väljatöötamine - 22
- automaattestide täiendamine - 8
- Testimine - 24

**Comment by erkisisask** [comment]
Jaagult täiendav kommentaar:
"Rääkisin sellest Erkkiga ja see list, mis ma edastasin Ivarile, jäi põhimõtteliselt ka kehtima: jpg, png, gif pildifailidest; audiost mp3, ogg, wav; videost mp4, ogv, webm; kolmandatest osapooltest Youtube, soundcloud; portatiivsed dokid vajalikud pole (pdf, epub), sest nende kasutamise fookus peab olema materjalides."

Wikis ja Issue kirjelduses täiendused sisse viidud.

**Comment by erkisisask** [comment]
08.12 Avega kokkuleppel onhold kuni ei ole konkreetselt selge vistutavate meediafailide autoriõiguste teemad.

**Comment by erkisisask** [comment]
Autoriõiguste nüansid selgeks räägitud 15.12 kohtumisel, issue töösse.

**Comment by erkisisask** [comment]
@averand - vajab sinu poolt laiendite osas ülevaatamist, millised on tõesti must have, millised mitte.

**Comment by averand** [comment]
jpg, png, gif, mp3, mp4, YT, SC - otsus ei ole "must-have" tüüpi, vaid "alustame millestki" tüüpi.

**Comment by erkisisask** [comment]
Tarnitud MS13 tarnepakiga (rakenduse versioon 1.14.0).
