### ISSUE TITLE
Kogumikule eelistatud materjali lisamine -> eelistatud materjalide kiirotsing

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#252]
Kasutajatel rollis tavakasutaja, aineekspert, administraator on võimalik kogumiku muutmise vormil lisada sisuplokki eelistatud materjale, kasutades eelistatud materjalide kiirotsingut.

Acceptance criteria:
- [ ] Vormil on nupp „Eelistatud materjal“
- [ ] Valitud materjalid lisatakse määratud peatükki embedded elementidena
- [ ] Otsing kuvab tulemustena vaid eelistatud materjale
- [ ] Kasutaja saab materjalide otsinguvaatel navbar’il valida, millisesse peatükki valitud materjal(id) lisatakse. Vaikimisi on valitud peatükk, mille haldamisel vajutati nupul „Eelistatud materjal“

Story kirjeldus wikis: https://github.com/hariduspilv/koolikott/wiki/User-story:-eelistatud-materjali-kiirotsing

Story kuulub featuuri https://github.com/hariduspilv/koolikott/wiki/Feature:-kogumikule-eelistatud-materjali-lisamine koosseisu.

**Comment by kokakoola** [comment]
disain ja flow: https://invis.io/5K8KXIETH#/240716552_5-2-1_Lisa_Olol_Materjal_1

**Comment by erkisisask** [comment]
- Vormil on nupp „Eelistatud materjal“ - 2
- Otsing kuvab tulemusi automaatselt ilma otsinguväljale teksti sisestamata - 4
- Valitud materjalid lisatakse määratud peatükki vistutatud elementidena - 4
- Otsing kuvab tulemustena vaid eelistatud materjale - 4
- Kasutaja saab materjalide otsinguvaatel navbar’il valida, millisesse peatükki valitud materjal(id) lisatakse - 6
- Vaikimisi on valitud peatükk, mille haldamisel vajutati nupul „Eelistatud materjal“ - 2
- Kasutaja ei saa otsinguseadistustes eelistatud materjalide seadistust muuta - 2
- Testimine - 10

**Comment by erkisisask** [comment]
Tarnitud MS13 tarnepakiga (rakenduse versioon 1.14.0).
