### ISSUE TITLE
Kogumikule olemasoleva materjali lisamine -> Olemasoleva materjali kiirotsing

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#253]
Kasutajatel rollis tavakasutaja, aineekspert, administraator on võimalik kogumiku muutmise vormil valida sisuplokki materjale E-koolikotis olemasolevate materjalide seast, kasutades olemasolevate materjalide kiirotsingut.

Acceptance criteria:
- [ ] Vormil on nupp „Olemasolev materjal“
- [ ] Valitud materjalid lisatakse määratud peatükki embedded elementidena
- [ ] Kasutaja saab materjalide otsinguvaatel navbar’il valida, millisesse peatükki valitud materjal(id) lisatakse. Vaikimisi on valitud peatükk, mille haldamisel vajutati nupul „Olemasolev materjal“

Story kirjeldus wikis: https://github.com/hariduspilv/koolikott/wiki/User-story:-olemasoleva-materjali-kiirotsing

Story kuulub featuuri https://github.com/hariduspilv/koolikott/wiki/Feature:-kogumikule-olemasoleva-materjali-lisamine koosseisu.

**Comment by kokakoola** [comment]
disain: https://invis.io/5K8KXIETH#/240716552_5-2-1_Lisa_Olol_Materjal_1

**Comment by erkisisask** [comment]
- Vormil on nupp „Olemasolev materjal“ -2
- Nupul vajutades kuvab süsteem otsinguvaate materjalide lisamiseks kogumikku - 4
- Otsing kuvab tulemusi automaatselt ilma otsinguväljale teksti sisestamata - 8
- Valitud materjalid lisatakse määratud peatükki vistutatud elementidena - 4
- Kasutaja saab materjalide otsinguvaatel navbar’il valida, millisesse peatükki valitud materjal(id) lisatakse - 4
- Vaikimisi on valitud peatükk, mille haldamisel vajutati nupul „Olemasolev materjal“ - 4
- „Uus“ nupu eemaldamine - 1
- disaini täiendamine (checkbox) - 4
- Testimine - 8

**Comment by erkisisask** [comment]
Tarnitud MS12 tarnepakiga (rakenduse versioon 1.13.0).
