### ISSUE TITLE
Kogumikule uue materjali lisamine -> uue materjali lisamise uus modaal

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#254]
Lihtsustada kasutajate poolsed uute materjalide lisamist.

Muudetakse uue materjali lisamise modaali struktuuri ja visuaali, et andmete sisestamine oleks ladusam ning kasutaja jaoks arusaadavam. Vähendatakse kasutajalt nõutavate andmeväljade arvu ning kaotatakse eraldi tabidena modaali osad.

Praegu eksisteeriva modaali vaated uue materjali lisamiseks:
![image](https://user-images.githubusercontent.com/19922635/31719293-98bed5c4-b41b-11e7-8f9a-8892e6a3e2ff.png)
![image](https://user-images.githubusercontent.com/19922635/31719327-b88e4ca4-b41b-11e7-9fcf-a30351dee360.png)
![image](https://user-images.githubusercontent.com/19922635/31719355-d29181de-b41b-11e7-87fb-fbcc6a6ffa93.png)

Uue modaali struktuur ja visuaalne lahendus (vastavalt 01.11 koosolekul kokkulepitule):
![213](https://user-images.githubusercontent.com/31726683/32441994-68c69744-c302-11e7-83dc-2bda6b28cc01.PNG)

Acceptance criteria:
- [ ] Materjali lisamise modaalvorm on kõik ühel vaatel (ei ole jagatud tab’idesse)
- [ ] „Lisa materjal“ nupp modaalvormil on aktiivne vaid siis, kui kohustuslikud väljad on täidetud
- [ ] „Lisaandmed“ vormiplokk on vaikimisi suletud (collapsed) seisus
- [ ] Kasutaja suunatakse vormi lõpetamisel materjali lisamisega korrektsele vaatele (kogumiku vorm / materjali vorm)

Story kirjeldus wikis: https://github.com/hariduspilv/koolikott/wiki/User-story:-uue-materjali-lisamise-uus-modaal

Story kuulub featuuri https://github.com/hariduspilv/koolikott/wiki/Feature:-kogumikule-uue-materjali-lisamine koosseisu.

**Comment by kokakoola** [comment]
disain:
https://invis.io/5K8KXIETH#/262093834_Lisa_Uus_Materjal_Autoriga

**Comment by erkisisask** [comment]
- uue materjali lisamise modaali visuaali muutmine - 12
- kasutajalt nõutavate andmeväljade vähendamine (kohustuslikkuse kontrollid) - 10
- eraldi tabidena modaali osade kokkutõstmine ühe nn tabi sisse - 12
- väljade salvestuse loogika ümberkirjutamine, testide täiendamine - 16
- automaattestide täiendamine - 12
- testimine - 12

**Comment by erkisisask** [comment]
Tarnitud MS12 tarnepakiga (rakenduse versioon 1.13.0).
