### ISSUE TITLE
Kogumiku peatüki sisu vormistamine -> peatüki sisuteksti vormindamise tooltip'i kasutamine

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#255]
Kasutajatel rollis tavakasutaja, aineekspert, administraator on võimalik kogumiku koostamisel kasutada sisuteksti stiili vormindamiseks sisuplokis kuvatud tooltip texteditor’i.

Acceptance criteria:
- [ ] Tekstifraasi aktiivseks valimisel kuvab süsteem tooltip texteditor’i
- [ ] Sisuploki alustamisel kuvab süsteem tooltip texteditor’i
- [ ] Sisuploki sees uue lõigu alustamisel kuvab süsteem tooltip texteditor’i
- [ ] Tooltip’i nuppude alusel on võimalik muuta teksti stiili
- [ ] Aktiivselt valitud teksti vormindamise stiilid on tuvastatavad tooltip’is kuvatud nuppude ikoonide värvide alusel

Story kirjeldus wikis: https://github.com/hariduspilv/koolikott/wiki/User-story:-peat%C3%BCki-sisuteksti-vormindamise-tooltip%E2%80%99i-kasutamine

Story kuulub featuuri https://github.com/hariduspilv/koolikott/wiki/Feature:-kogumiku-peat%C3%BCki-sisu-vormindamine koosseisu.

**Comment by kokakoola** [comment]
disain: https://invis.io/5K8KXIETH#/240041014_4-_Kogumiku_algus_1_tulp

**Comment by erkisisask** [comment]
- Vormindamise texteditor’i kuvamine kasutajale kolmel tingimusel (äriloogika täiendus) - 6
- Tekstifraasi aktiivseks valimisel kuvab süsteem tooltip texteditor’i - 3
- Sisuploki alustamisel kuvab süsteem tooltip texteditor’i - 2
- Sisuploki sees uue lõigu alustamisel kuvab süsteem tooltip texteditor’i - 2
- Tooltip’i nuppude alusel on võimalik muuta teksti stiili - 4
- Aktiivselt valitud teksti vormindamise stiilid on tuvastatavad tooltip’is kuvatud nuppude ikoonide värvide alusel - 2
- testimine - 5

**Comment by erkisisask** [comment]
Tarnitud MS12 tarnepakiga (rakenduse versioon 1.13.0).
