### ISSUE TITLE
Kogumiku peatüki sisu vormistamine ->Süsteemis kasutatava tekstiredaktori väljavahetamine

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#256]
Vahetada välja kogumiku sisuosa haldamisel kasutatav tekstiredaktor, et võimaldada tooltip texteditor’i kasutamine kasutajaloos „Peatüki sisuteksti vormindamise tooltip’i kasutamine“ kirjeldatud moel.

Acceptance criteria:
- [ ] Kogumiku haldamisel kasutatav tekstiredaktor võimaldab tooltip texteditor’i kuvamist vaikimisi lõigu alguses
- [ ] Kogumiku haldamisel kasutatav tekstiredaktor võimaldab tooltip texteditor’i kuvamist aktiivsena valitud teksti kohal
- [ ] Kogumiku haldamisel kasutatav tekstiredaktor võimaldab kasutajaloos „Peatüki sisuteksti vormindamise tooltip’i kasutamine“ kirjeldatud tekstistiile
- [ ] Kogumiku haldamisel kasutatav tekstiredaktorit on võimalik kasutada igas eraldiseisvas sisuplokis ilma süsteemi kiirust märkimisväärselt mõjutamata

Task kirjeldus wikis: https://github.com/hariduspilv/koolikott/wiki/Task:-s%C3%BCsteemis-kasutatava-tekstiredaktori-v%C3%A4ljavahetamine

Task kuulub featuuri https://github.com/hariduspilv/koolikott/wiki/Feature:-kogumiku-peat%C3%BCki-sisu-vormindamine koosseisu.

**Comment by kokakoola** [comment]
disain: https://invis.io/5K8KXIETH#/240041014_4-_Kogumiku_algus_1_tulp

**Comment by erkisisask** [comment]
- süsteemis kasutatava tekstiredaktori väljavahetamine - 18
- taustaloogika ümberkirjutamine vana redaktori pealt uuele - 12
- tehnilised taustatööd (sh uue redaktori f-nide salvestamine) - 10
- Testimine - 6

**Comment by erkisisask** [comment]
Kuna HTML contenteditable on seni vähe rakendatud ja vähearenenud tehnoloogia ja see korralikult nõuete järgi toimima saada, osutus keerulisemaks kui algselt arvati, siis WYSIWYG’i töö suurenemise põhjused on:
- objektide vistutamise võimalusele redigeeritava sisu hulka (täpsemini see, kuidas vistutatud objektid liigutatava kursori all käituvad)
- wysiwyg’i fookuse ja kursori asukoha säilitamine tööriistariba toimingute järel (muuda tulba laiust, liiguta tulpa jms)
- wysiwyg’i tekstivormindamise nupud ja paste'imine — kasutusele võetud Medium Editor’i tööriistad ei toiminud out-of-the-box kõik päris sedasi, kuidas kasutajaloos kirjeldatud ja lubas teha/ paste'ida ka vigast vormingut (panna bullet-loendit pealkirja sisse jms).

46.

**Comment by erkisisask** [comment]
Tarnitud MS12 tarnepakiga (rakenduse versioon 1.13.0).
