### ISSUE TITLE
Litsentsitüüpide haldamine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#26]
**Tulem**

Materjalide-kogumike detailvaates:
- [ ] litsentsid omavad tõlkeid, süsteemse 'CC-BY' asemel 'Autorile viitamine', kuvab ka meta sisestamisel. Anname inimkeelsed tõlked litsentsidele.
- [ ] kui kasutajaliidese keel on 'et' või 'en', siis 'Autorile viitamine' viib [en kirjeldusele](https://creativecommons.org/licenses/by/4.0/), 'ru' viib [venekeelsele](https://creativecommons.org/licenses/by/4.0/deed.ru)
  (peatselt tekib eestikeelne CC landing page - peab olema lihtne hiljem muuta keele 'et' link vastavaks) - Ehk link litsentsi kirjeldusele.

**Comment by KailiAll** [comment]
Loetleda, millised metaväljad.
Mis saab kuupäeval ja vaatamistel klikkimisel?
Palun kirjutada arendussoovid täpsemalt lahti.

**Comment by KailiAll** [comment]
Esialgne ülesanne:
Materjalide-kogumike detailvaates:

 kuvada metaandmete olemasolul üldpädevusi, läbivaid teemasid, teemasid, alamteemasid

 kavandada asukoht ka hiljem lisanduvatele metaväljadele: vorming, maht, õpiväljundid #11 (EstCORE 4.1, 4.2, 9.4) - vaja näited tekstidest

 kõik detailvaate metaväljad on klikitavad nende põhjal otsingu teostamiseks (ei pruugi aga olla sinised)

 litsentsid omavad tõlkeid, süsteemse 'CC-BY' asemel 'Autorile viitamine', kuvab ka meta sisestamisel. Anname inimkeelsed tõlked litsentsidele

 kui kasutajaliidese keel on 'et' või 'en', siis 'Autorile viitamine' viib en kirjeldusele, 'ru' viib venekeelsele
(peatselt tekib eestikeelne CC landing page - peab olema lihtne hiljem muuta keele 'et' link vastavaks) - Ehk link litsentsi kirjeldusele

 #57 -retsensioon peab olema kuvatud. Faili ikoon.

**Comment by KailiAll** [comment]
kõik detailvaate metaväljad on klikitavad nende põhjal otsingu teostamiseks (ei pruugi aga olla sinised) (lahendatakse #92 )

**Comment by KailiAll** [comment]
kuvada metaandmete olemasolul üldpädevusi, läbivaid teemasid, teemasid, alamteemasid

 kavandada asukoht ka hiljem lisanduvatele metaväljadele: vorming, maht, õpiväljundid #11 (EstCORE 4.1, 4.2, 9.4) - vaja näited tekstidest

Need läksid piletisse #91

**Comment by KailiAll** [comment]
Erkki.

**Comment by KailiAll** [comment]
Erkki.
- litsentsid omavad tõlkeid, süsteemse 'CC-BY' asemel 'Autorile viitamine', kuvab ka meta sisestamisel. 

Palun testtekste kui pikad need sisud on.

**Comment by KailiAll** [comment]
#57 -retsensioon peab olema kuvatud. Faili ikoon. (lahendatakse 91 pileti raames)

**Comment by erkisisask** [comment]
Litsentside eesti keelsed nimetused lahendatud #298 raames. Seega sulgen selle taski.
