### ISSUE TITLE
Kogumiku sisuplokkide haldamine -> sisuplokkide lisamine

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#260]
Kasutajatel rollis tavakasutaja, aineekspert, administraator on võimalik kogumiku koostamisel lisada peatükki uusi sisuplokke, et võimaldada kogumiku sisu detailsemat kujundamist.

Acceptance criteria:
- [ ] „Lisa sisuplokk“ nupuvajutuse järel tekitab süsteem uue sisuploki hallatava peatüki lõppu
- [ ] Kui eelnev sisuplokk oli vasakule joondatud poollai sisuplokk, lisatakse uus sisuplokk poollaiana eelneva sisuploki kõrvale (paremale)
- [ ] Kui eelnev sisuplokk on täislai või poollai ja paremale joondatud, lisatakse uus sisuplokk täislaiana
- [ ] Sisuploki lisamise järel kuvab süsteem antud sisuploki alguses tooltip texteditor’i

Story kirjeldus wikis: https://github.com/hariduspilv/koolikott/wiki/User-story:-sisuplokkide-lisamine

Story kuulub featuuri https://github.com/hariduspilv/koolikott/wiki/Feature:-kogumiku-sisuplokkide-haldamine koosseisu.

**Comment by kokakoola** [comment]
disain:
https://invis.io/5K8KXIETH#/240041014_4-_Kogumiku_algus_1_tulp

**Comment by erkisisask** [comment]
- „Lisa sisuplokk“ nupuvajutuse järel tekitab süsteem uue sisuploki hallatava peatüki lõppu - 3
- Kui eelnev sisuplokk oli vasakule joondatud poollai sisuplokk, lisatakse uus sisuplokk poollaiana eelneva sisuploki kõrvale (paremale) - 6
- Kui eelnev sisuplokk on täislai või poollai ja paremale joondatud, lisatakse uus sisuplokk täislaiana - 4
- Sisuploki lisamise järel kuvab süsteem antud sisuploki alguses tooltip texteditor’i - 2
- salvestamise loogika realisatsioon - 8
- testimine - 3

**Comment by erkisisask** [comment]
Tarnitud MS12 tarnepakiga (rakenduse versioon 1.13.0).
