### ISSUE TITLE
Kogumiku sisuplokkide haldamine -> sisuplokkide laiuse seadistamine

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#261]
Kasutajatel rollis tavakasutaja, aineekspert, administraator on võimalik kogumiku koostamisel seadistada sisuploki laiust, et võimaldada kogumiku sisu detailsemat kujundamist.

Acceptance criteria:
- [ ] Kui sisuplokk on täislai, muudab „Muuda laiust“ nupuvajutus hallatava sisuploki poollaiaks
- [ ] Kui sisuplokk on poollai, muudab „Muuda laiust“ nupuvajutus hallatava sisuploki täislaiaks
- [ ] Kui täislaiale sisuplokile eelneb poollai sisuplokk, mis on vasakule joondatud, viib süsteem hallatava sisuploki „Muuda laiust“ nupuvajutuse järel eelneva poollaia sisuploki kõrvale (paremale)

Story kirjeldus wikis: https://github.com/hariduspilv/koolikott/wiki/User-story:-sisuplokkide-laiuse-seadistamine

Story kuulub featuuri https://github.com/hariduspilv/koolikott/wiki/Feature:-kogumiku-sisuplokkide-haldamine koosseisu.

**Comment by kokakoola** [comment]
disain:
https://invis.io/5K8KXIETH#/240041014_4-_Kogumiku_algus_1_tulp

**Comment by erkisisask** [comment]
- Nupule „Muuda laiust“ täislaia ja poollaia sisuploki seadistuse loomine - 8
- Kui sisuplokk on täislai, muudab „Muuda laiust“ nupuvajutus hallatava sisuploki poollaiaks - 4
- Kui sisuplokk on poollai, muudab „Muuda laiust“ nupuvajutus hallatava sisuploki täislaiaks - 4
- Olenevalt laiusest sisuplokkide asukoha loogika väljatöötamine - 4
- testimine - 4

**Comment by erkisisask** [comment]
Tarnitud MS12 tarnepakiga (rakenduse versioon 1.13.0).
