### ISSUE TITLE
Kogumiku sisuplokkide haldamine -> sisuplokkide järjestuse seadistamine peatükis

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#262]
Kasutajatel rollis tavakasutaja, aineekspert, administraator on võimalik kogumiku koostamisel muuta olemasolevate sisuplokkide järjestust, et võimaldada kogumiku sisu detailsemat kujundamist.

Acceptance criteria:
- [ ] „Liiguta tagasi“ nupp liigutab hallatavat sisuplokki järjestuses ühe sisuploki võrra alguse poole
- [ ] „Liiguta edasi“ nupp liigutab hallatavat sisuplokki järjestuses ühe sisuploki võrra lõpu poole
- [ ] „Liiguta tagasi“ nupp on mitteaktiivne, kui hallatavale sisuplokile ei eelne kogumikus ühtegi sisuplokki
- [ ] „Liiguta edasi“ nupp on mitteaktiivne, kui hallatavale sisuplokile ei järgne kogumikus ühtegi sisuplokki

Story kirjeldus wikis: https://github.com/hariduspilv/koolikott/wiki/User-story:-sisuplokkide-j%C3%A4rjestuse-seadistamine-peat%C3%BCkis

Story kuulub featuuri https://github.com/hariduspilv/koolikott/wiki/Feature:-kogumiku-sisuplokkide-haldamine koosseisu.

**Comment by kokakoola** [comment]
disain: https://invis.io/5K8KXIETH#/240041014_4-_Kogumiku_algus_1_tulp

**Comment by erkisisask** [comment]
- Sisuplokkide järjestuse seadistamiseks on peatüki kõrval olevas Küljenda osas nupud „Liiguta tagasi“ ja „Liiguta edasi“ - 2
- „Liiguta tagasi“ nupp liigutab hallatavat sisuplokki järjestuses ühe sisuploki võrra alguse poole - 4
- „Liiguta edasi“ nupp liigutab hallatavat sisuplokki järjestuses ühe sisuploki võrra lõpu poole - 4
- „Liiguta tagasi“ nupp on mitteaktiivne, kui hallatavale sisuplokile ei eelne kogumikus ühtegi sisuplokki - 4
- „Liiguta edasi“ nupp on mitteaktiivne, kui hallatavale sisuplokile ei järgne kogumikus ühtegi sisuplokki - 4
- testimine - 6

**Comment by erkisisask** [comment]
Tarnitud MS12 tarnepakiga (rakenduse versioon 1.13.0).
