### ISSUE TITLE
Kogumiku sisuplokkide haldamine -> Sisuploki kustutamine

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#263]
Kasutajatel rollis tavakasutaja, aineekspert, administraator on võimalik kogumiku koostamisel kustutada peatükki lisatud sisuplokke.

Acceptance criteria:
- [ ] Sisuplokki on võimalik kustutada, kasutades selleks Küljenda vormiplokis olevat nuppu „Kustuta“
- [ ] Kasutajalt küsitakse kinnitust (modaal).

Story kirjeldus wikis: https://github.com/hariduspilv/koolikott/wiki/User-story:-sisuploki-kustutamine

Story kuulub featuuri https://github.com/hariduspilv/koolikott/wiki/Feature:-kogumiku-sisuplokkide-haldamine koosseisu.

**Comment by kokakoola** [comment]
disain: https://invis.io/5K8KXIETH#/240041014_4-_Kogumiku_algus_1_tulp

**Comment by erkisisask** [comment]
- Peatüki sisuploki kustutamiseks on kuvatud peatüki kõrval olevas Küljenda vormiplokis nupp „Kustuta“ - 2
- Kasutajalt küsitakse kinnitust (modaal) - 4
- Kustutamise katkestamise loogika - 2
- Kustutamise jätkamise loogika - 2
- Baasis sisubloki kustutatuks märkimine - 3
- Nupule vajutades kustutatakse hallatav sisuplokk frondis - 4
- testimine - 4

**Comment by erkisisask** [comment]
Tarnitud MS12 tarnepakiga (rakenduse versioon 1.13.0).
