### ISSUE TITLE
Backendi rakenduse versiooni kuvamine

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#271]
Hetkel e-Koolikoti rakendus küll kuvab frontendi versiooni rakenduse all vasakus nurgas, aga ei kuva back-endi versiooni. Luua võimalus selle kontrollimiseks üle brauseri URLi.

**Comment by erkisisask** [comment]
8

**Comment by OlegPahhomov** [comment]
/rest/version

**Comment by erkisisask** [comment]
Tarnitud MS12 tarnepakiga (rakenduse versioon 1.13.0).
