### ISSUE TITLE
Välise õppematerjali akendamine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#275]
Teenusliides õppematerjali väljaandjale võimaldab autoriseeritud materjalide akendatud kujul kuvamist juhul kui materjal on loodud kuvama standardses veebilehitsejas (lk 5)

https://github.com/hariduspilv/koolikott/blob/master/back-end/misc/documentation/e-Koolikott_Fullscreen_Materials_For_Publishers.pdf

Hetkel see nii ei toimi. Katkine olukord (materjali asukoht on tühi) sai ajutise paranduse versioonis 1.12, et kuvartaks fallbackina linki materjalile.

**Comment by erkisisask** [comment]
Lahendatud 8.dets.
