### ISSUE TITLE
Aineeksperdi kustutamine ei toimi

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#286]
Toodangus on katki läinud #176 - palun kiiret parandust, blokeerib aineeksperdi tööprotsessi.

![image](https://user-images.githubusercontent.com/16906555/33703804-5c8008e2-db32-11e7-8db5-ef6da4c042e6.png)

**Comment by erkisisask** [comment]
Tarnitud 07.12 pakiga 1.12.1 https://github.com/hariduspilv/koolikott/blob/master/CHANGELOG.md

**Comment by erkisisask** [comment]
Parandus paigaldatud toodangusse 12.12.2017.
