### ISSUE TITLE
Youtube video akendus katki

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#292]
**Oodatud tulemus:** video akendub ja mängib maha samas aknas
**Hetke tulemus:** tekib ainult link vt https://e-koolikott.ee/material?id=8120
![image](https://user-images.githubusercontent.com/16906555/33987289-1cae6460-e0c9-11e7-88c8-46e6c3227bee.png)

**Comment by erkisisask** [comment]
Tarnitud 14.detsembril 1.13.1 tarnepakiga.
