### ISSUE TITLE
Materjali ei õnnestu lisada uuest dialoogakanst

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#293]
FABist lisamisel jääb kohustuslike väljade täitmisel LISA nupp halliks - testitud mitme kasutajaga
![image](https://user-images.githubusercontent.com/16906555/33988777-1abe43c8-e0ce-11e7-8bbf-3f194a0d6114.png)

**Comment by erkisisask** [comment]
Tarnitud 14.detsembril 1.13.1 tarnepakiga.
