### ISSUE TITLE
Kogumiku detailvaates meediafaili juures kuvada meediafaili pealkirja, autorit, allikat ning litsentsitüüpi

### ISSUE THREAD

**Issue by erkisisask** [hariduspilv/koolikott#294]
Vastavalt 19.12 kokkulepetele, tuleb vistutatud meediafailide jaluseid kuvada järgnevalt:

- Meediafail:
  - Pealkiri (töötab lingina meediafaili URLile)
  - Autor
  - Allikas
  - Litsents (kujutatud litsentsi lühendina, mis viitab lingina litsentsi selgituse URLile e-koolikotis valitud keeles (ET, EN, RU))

Lisaks tuleb täiendada **materjali vistiku** jalust litsentsi informatsiooniga järgneval kujul:
  - Litsentsi lühend (nt CC BY), mis avab uues tabis litsentside selgituse URLi valitud keeles (ET, EN, RU).
 
(Hetkel on HITSA poolt hallatav litsentside selgituse [URL ](http://hitsa.ee/teenused/autorioigused/litsentside-selgitused) ainult eesti keeles. Kui kunagi tulevikus lisanduvad ka RUS ja ENG lehed, siis viia sisse vastavad muudatused).

Sketch:
![image](https://user-images.githubusercontent.com/3177716/34156011-1373c972-e4c4-11e7-830b-7d6b5f409f80.png)

**Acceptance criteria:**
- [ ] Meediafaili vistiku jaluses on kuvatud selle pealkiri
- [ ] Meediafaili vistiku jaluses olevale pealkirjale vajutades avaneb uues tabis selle sama meediafaili URL
- [ ] Meediafaili vistiku jaluses on kuvatud selle autor
- [ ] Meediafaili vistiku jaluses on kuvatud selle allikas
- [ ] Meediafaili vistiku jaluses on kuvatud selle litsents lühendina ja lingina (nt "Litsents: [CC BY](http://hitsa.ee/teenused/autorioigused/litsentside-selgitused)")
- [ ] Meediafaili vistiku jaluses olevale lingile vajutades avaneb uues tabis litsentsi selgituse [URL](http://hitsa.ee/teenused/autorioigused/litsentside-selgitused)
- [ ] Materjali vistiku jaluses on kuvatud selle litsents lühendina ja lingina (nt "Litsents: [CC BY](http://hitsa.ee/teenused/autorioigused/litsentside-selgitused)")
- [ ] Materjali  vistiku jaluses olevale lingile vajutades avaneb uues tabis litsentsi selgituse [URL](http://hitsa.ee/teenused/autorioigused/litsentside-selgitused)

Story kirjeldus wikis: https://github.com/hariduspilv/koolikott/wiki/User-story:-meediafaili-vistutamine

Story kuulub featuuri https://github.com/hariduspilv/koolikott/wiki/Feature:-kogumikule-meediafaili-lisamine koosseisu.

**Comment by kokakoola** [comment]
disain siin:
[https://invis.io/5K8KXIETH#/261073319_Kogumik_Valmis](url)

**Comment by erkisisask** [comment]
10.

**Comment by erkisisask** [comment]
Tarnitud MS13 tarnepakiga (rakenduse versioon 1.14.0).
