### ISSUE TITLE
Vistiku jaluses litsentsi lingi sidumine süsteemis valitud keeles selgituse URLiga

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#306]
Litsentsi klassifikaatori väärtused tuleb siduda korrektses keeles selgituste URLidega.

- **Backend tööd**: Tõlkeväärtuste tabelisse tekitada juurde uued tõlkevõtmed ja väärtused. 
  - Iga litsentsi (klassifikaatori väärtus) kohta URLile viitav tõlkevõti kõigi kolme süsteemse keele jaoks (ET, EN, RU): [litsentsi klassifikaatoriväärtus]_URL (nt CCBY_URL).
  - URL viitab hetkel CC litsentside puhul [siia ](http://hitsa.ee/teenused/autorioigused/litsentside-selgitused) 

- **Frondi tööd**: 
  - Kogumikus vistutatud materjalide/meediafailide jaluses on litsentsid kuvatud lingina litsentsi selgituse URLile vastavalt süsteemis valitud keeles

**Acceptance criteria:**
- [ ] Kogumikus vistutatud meediafaili jaluses viitab litsents lingina oma selgituse URLile süsteemis valitud keeles
- [ ] Kogumikus vistutatud materjali jaluses viitab litsents lingina oma selgituse URLile süsteemis valitud keeles

**Comment by erkisisask** [comment]
Seotud issuega #298.

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
