### ISSUE TITLE
Vasakmenüüs kuvatud arvude värskendamine jooksvalt

### ISSUE THREAD

**Issue by JaakL** [hariduspilv/koolikott#307]
Sisselogitud kasutajatele vasakmenüüs kuvatakse järgnevate menüüvalikute järel nendes vaadetes sisalduvate vastavate objektide (õppevara/materjalid/kogumikud/kasutajad) arv:
- _Minu kogumikud_
- _Minu materjalid_
- _Minu lemmikud_
- _Teatatud õppevara_ (eksperdil, administraatoril)
- _Uus õppevara_ (eksperdil, administraatoril)
- _Muudetud õppevara_ (eksperdil, administraatoril)
- _Aineeksperdid_ (ainult administraatoril)
- _Piiratud kasutajad_ (ainult administraatoril)
- _Kustutatud õppevara_ (ainult administraatoril)

**Vajadus:**
Kui kasutaja teostab süsteemis mõne tegevuse (nt märgib mõne õppevara lemmikuks), mis muudab objektide arvu ühes eelmainitud vaadetest (nt "Minu lemmikud"), tuleb seda arvu ka menüüvaliku juures automaatselt värskendada.

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
