### ISSUE TITLE
Üleslaetud PDF failid ei kuva

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#310]
Varemlisatud PDF faile ei näe ega saa alla laadida ei kogumikus ega materjali detailvaates
Kasutaja raporteeritud kogumik https://e-koolikott.ee/portfolio?id=9443
Sama probleem nii Chrome kui Firefoxiga
![image](https://user-images.githubusercontent.com/16906555/37340234-1c7e33f6-26c6-11e8-998f-228e1215c09a.png)

**Comment by erkisisask** [comment]
Koodi muudatust ei olnud. Administratiivne serveri poolne muudatus - Nüüd on üle terve süsteemi rangelt en_us.utf-8 nagu võiks. Materjalid nüüd nähtavad korrektselt.
