### ISSUE TITLE
Kirjeldusest vorminduse kadumine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#318]
Avades vormindatud kirjeldusega (nt reavahed, numeratsioon, viideted) õppevara metaandmed muutmiseks, on vormindus avanevas dialoogaknas kadunud ja salvestamisel kaob vormindus üldse ära.

Kadunud on ka varasemalt õppevara kirjelduse metavälja aktiveerimisel ilmuvad vormindusnupud.

Olukorra _workaround_ on `<p> <br> <li> <b> <a href>` jt elementide abil kirjelduse välja vormindamine.

**Comment by erkisisask** [comment]
@erkkijakobson palun pilti + viidet konkreetsele õppevarale, millega olukord esineb.

**Comment by erkisisask** [comment]
Tarnitud 1.18.0 tarnepakiga 16.04.2018.
