### ISSUE TITLE
sisse logimine (ID-kaardiga) firefoxi browseriga ebaõnnestub

### ISSUE THREAD

**Issue by ylahtein** [hariduspilv/koolikott#371]
Sisse logimine firefoxiga ebaõnnestub aeg ajalt,ei oska seost välja tuua (st kui tihti ja millal. Kord logib issse kord ei logi sisse)

**Comment by erkisisask** [comment]
Testitud. Töötab kui seadistused on õiged. Soovitused pöördujale:
- kaart peab enne lugejas olema kui brauser lahti teha
- lubada FF extensionid (vaadata üle, kas vajalikud on enabled)
- uuendada id kaarti tarkvara ära arvutis.
