### ISSUE TITLE
Asendada tekst,mis kuvatakse,kui sisupuus ei leidu ühtegi õppevara (materjali ega kogumiku)

### ISSUE THREAD

**Issue by ylahtein** [hariduspilv/koolikott#377]
Spec https://projektid.hitsa.ee/display/koolikott/Kutsehariduse+taksonoomia, punkt 3

**Comment by erkisisask** [comment]
Tarnitud 1.23.2 tarnepakiga 19.10.2018.

**Comment by erkisisask** [comment]
Tarnitud 1.23.2 tarnepakiga 19.10.2018.

**Comment by erkisisask** [comment]
Tarnitud 1.23.2 tarnepakiga 19.10.2018.
