### ISSUE TITLE
Kasutusjuhendite sisestamine ja kuvamine 

### ISSUE THREAD

**Issue by ylahtein** [hariduspilv/koolikott#379]
Kasutusjuhendite lisamine ADMIN menüü kaudu: https://projektid.hitsa.ee/pages/viewpage.action?pageId=35619186
Kasutusjuhendite kuvamine: https://projektid.hitsa.ee/pages/viewpage.action?pageId=33233489

**Comment by erkisisask** [comment]
Tarnitud 1.24.0 tarnepakiga 01.11.2018
