### ISSUE TITLE
Ikoonid on mõnes telefonis kadunud

### ISSUE THREAD

**Issue by atatter** [hariduspilv/koolikott#40]

**Comment by KailiAll** [comment]
Viga esineb näiteks Samsung Galaxy A3 mudel SM-A310F (Kaili tel näiteks)

**Comment by gglukmann** [comment]
Viga esines Androidi enda brauseriga, konkreetselt versioon 3.5, mis on välja antud 2011 aastal. https://decadecity.net/blog/2013/11/21/android-browser-versions
