### ISSUE TITLE
Lemmikuks lisamine

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#42]
**Arendusvajaduse kirjeldus:**
Õppevara peab olema võimalik lihtsa nupuvajutusega lisada lemmikuks, hiljem peab sellist õppevara lihtne leida olema.

**Tulem:**
- [x] Kasutaja saab lisada õppevara (materjal, kogumik) lemmikuks (täht)
- [x] Lemmikuks lisatud õppevara on märgatav materialbox elemendil
- [x] Lemmikuks lisatud õppevara on märgatav detailvaates
- [x] Kasutaja saab eraldi vaadelda ainult oma lemmikuks lisatud õppevara
- [x] Kasutaja saab lemmikuks lisatut eemaldada

**Comment by martlausNG** [comment]
Needs review.

**Comment by RannarA** [comment]
Review ok.

**Comment by erkkijakobson** [comment]
Lemmikuks lisatud õppevara ei ole märgatav materialbox elemendil

**Comment by martlausNG** [comment]
Kollane täht on hoverides boxil, milles viga esineb?
