### ISSUE TITLE
Lisa materjali juurde lisatavat pilti peab olema võimalik lõigata

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#43]
**Arendusvajaduse kirjeldus:**
1. Lisa materjal
2. Lohista pilt siia või valipilt arvutist
3. Kui pilt on lisatud, peab olema võimalus seda pilti väiksemaks lõigata.

Kasutada croppimiseks mingit Googli enda lahendust contacts.google.com. 

**Tulem:**
- [ ] Esimene tab on pildi TAB, see on alati näha.
- [ ] Default TAB on põhiandmete TAB (Kogumiku loomisel on sama asi).
- [ ] Pilti saab üles laadida nii põhiandmetest kui pildi TABist.
- [ ] Kui pilt tuleb Youtubest, siis mingit teadet ei tule ja rakendub Default croppimine.
- [ ] Pilti on võimalik väiksemaks lõigata.
- [ ] Laed pildi üles ja kasutaja suunatakse pildi croppimise tabi.
- [ ] Pilti on lisaks arvutis leiduvale võimalik lohistada ka teiselt toetatud sirviku vahelehelt.
- [ ] Kuvasuhe peab olema paigas E-koolikoti kuvasuhtega.

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati tõsta see töö e-Koolikoti Confluence'i analüüsi backlogi.
