### ISSUE TITLE
Täpse otsingu keelevaliku muudatus

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#46]
**Muudatuse asukoht**
1. Ava täpne otsing
2. Keel- klõpsad noolekesel
3. Avaneb rippmenüü kõigi keeltega

**Muudatuse tulem**
- [x] Keelte valikusse on lisatud esimeseks valikuks "Kõik keeled"
- [x] Ülejäänud valik sisaldab vaid süsteemisleiduva õppevara keeli, tähestiku järjekorras

NB! Tuleb mõelda, kuidas toimub selle nimekirja uuendamine.

**Comment by martlausNG** [comment]
Needs review.

**Comment by RannarA** [comment]
Review ok

**Comment by erkkijakobson** [comment]
ok
