### ISSUE TITLE
Avalehe ja kogumiku edit vaate tour

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#54]
**Arendusvajadus:**
Esimest korda veebilehele liikudes saad giidiga touri.
Esimest korda kogumiku muutmise režiimi sattudes saad giidga tuuri.
Hiljem võid suvalises vaates selle abi saamiseks aktiveerida.

**Tulem:**
- [ ] Tour on lisatud
- [ ] Tuur asendab (?) nupu menüüs "Kuidas e-Koolikotti kasutada?" (eraldi *help* leht on *deprecated*)

**Comment by aivo0** [comment]
Võimalusel võiks kasutada valmis teeki või lahendust selle realiseerimiseks. 
Hõlmab kogu süsteemi - eraldi tuurid on eri süsteemi osadele.

**Comment by martlausNG** [comment]
See, tähendab, et  igas "suvalises" vaates on üldine tuur, kus on kohtadeks fab nupp, täpne otsing, vasak sidebar, kuidas uuesti tuuri näha, välja peaks ka mõtlema, et kuidas näidata materjali "linnutamist". Edit vaates on eraldi tuur. Salvestame info, et sisselogitud kasutaja on mõlemat tuuri näinud baasi. Autentimata ja autenditud kasutaja saab käivitada tuuri küsimärgi alt alati uuesti. Tuuri saab katkestada, tagasi võtta ja edasi minna.

**Comment by aivo0** [comment]
Autentimata kasutaja ei näe tuuril FAB nupu tutvustust, sest ta ei näe FAB nuppu.

**Comment by kokakoola** [comment]
@gglukmann 
- Tuuri algusesse lisada väike intromodaal backdropiga (nt Sisselogimise modaalaken templiidi põhjal (mis muide on vale kujundusega)), mis tervitab ja pakub võimalust tuuri läbida või mitte (nupud Jah, Ei, mitte praegu) 
- Kui valik on Ei, järgneb 1 tuurtip, paigutusega ? ja sisuga "Olgu nii! Küsimärgi ikooni alt saaad alati tutvustuse uuesti käivitada kui vajadust tunned." Läheb eest ära Timeoutiga.
- Kui valik on Ja, algab tuur

NB! Hilisemal käivitamisel küsimärgi alt ei näidata intromodaali.

- Mobiilivaatesse ei tee tuuri. Alates murdepunktist md
- x-le tuleb lisada tõlge "Katkesta"

**Comment by KailiAll** [comment]
@erkkijakobson 
Palun vaata oxygenis üle, kas tehtud lahendus sobib.

**Comment by KailiAll** [comment]
Erkki kommentaar: tuuri X nupu asemel peaks olega tekst ‘sulge’
