### ISSUE TITLE
Üldpädevust ja läbivate teemade loogika arendamine

### ISSUE THREAD

**Issue by martlausNG** [hariduspilv/koolikott#56]
ÜLDPÄDEVUSED
- [x] Üldpädevuste listis "Ei seostu üldpädevustega" läheb listi lõppu.
- [x] Kui üldpädevuste listis teha valik, siis dropdown sulgub.
- [x] Kui vähemalt üks üldpädevus on valitud, siis ei ole dropdownis näha "Ei seostu üldpädevustega" 
- [x] Kui "Ei seostu üldpädevustega" on valitud ja valitakse mõni teine üldpädevus, siis "Ei seostu üldpädevustega" chip kaob ära.
- [x] Üldpädevuse määramine on kohustuslik väli
- [x] Kui üldpädevuste listis on valitud  "Ei seostu üldpädevustega", siis on see kirjutatud andmebaasi materjali külge, et materjali muutes ei saaks segavat veateadet.

LÄBIVAD TEEMAD
- [x] Läbivate teemade listis "Ei oma läbivaid teemasid" läheb listi lõppu.
- [x] Kui läbivate teemade listis teha valik, siis dropdown sulgub.
- [x] Kui vähemalt üks läbiv teema on valitud, siis ei ole dropdownis näha "Ei oma läbivaid teemasid" 
- [x] Kui "Ei oma läbivaid teemasid" on valitud ja valitakse mõni teine läbiv teema, siis "Ei oma läbivaid teemasid" chip kaob ära.
- [x] Läbivate teemade määramine on kohustuslik väli.
- [x] Kui läbivate teemade listis on valitud  "Ei oma läbivaid teemasid", siis on see kirjutatud andmebaasi materjali külge, et materjali muutes ei saaks segavat veateadet.

**Comment by RannarA** [comment]
Kokkulepitud muudatus: Kui vähemalt üks valik on tehtud, siis "Ei seostu..." / "Ei oma..." valik jääb dropdownis alles, aga selle valimisel ei juhtu midagi.
