### ISSUE TITLE
Youtube API

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#59]
**Tulem**
- [x] materjali viida lisamisel kohtades kus see on võimalik, scrapeda ja eeltäita maksimaalne hulk metavälju, sh pilt.
- [x] toetatud peab olema litsensi väljale tulev 'Youtube litsents' (kuvamisel viide litsensile).

**Comment by martlausNG** [comment]
Kui kasutaja teostab otsingut, õppevara tüüp on "Video" ja vasteid pole, siis tekib sinna nupp "Laienda otsingut youtubes" vms. 
Sellel nupul klikkimisel tehakse otsing Youtubesse ja kuvatakse vastuseid tavaliste Materialboxidena, kus on lisatud infot, mida saame youtubest. 
Kui kasutaja klikib materialboxil avatakse standardne materjali detailvaade, kus on embedded youtube video. (Üks flow ja layout üle rakenduse)
Detailvaates läheks ülemine rida peitu (see kus on haridustase jne) ja selle asemel oleks nupp ja tekst, mis suunaks kasutajat antud youtube videot ekoolikotti lisama, nt "Tee youtube video õppematerjaliks" vms.
Antud nupul klikkimisel avaneb tänase materjali lisamise pop-up-i lihtsustatud versioon (kuna tegelikult on vaja täita ainult 1 väli, mida youtube ei paku - vanus), kus on ainult mõni väli (nt taksonoomia ja/või vanuse valik).
Pop-up-i täitmisel ja salvestamisel lisandub antud youtube video ekoolikotti õppematerjalina.

**Comment by aivo0** [comment]
Mardi kommentaarist laiendatud otsingut siin ei tehta.
