### ISSUE TITLE
Õppevara lisamisel pealkirja ja kirjelduse keel

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#61]
**Muudatuse asukoht**
1. Lisa uus materjal
2. Pealkirja ja kirjelduse keel
3. Klikid alla suunatud noolekesel-> avaneb rippmenüü keelte valikuga

**Muudatuse tulem**
- [ ] pealkirja ja kirjelduse keele valikus kuvatakse ainult järgmisi keeli: 
  1) Eesti
  2) Inglise
  3) Vene

Kuna jääb ainult 3 keelt, mis ei nõua rippmenüü elemendi kasutust, siis analüüsida ka kasutajakogemust ja pakkuda lahendus kuidas pealkirja ja kirjelduse keele valik mugavamaks muuta.
1. vaikimis on aktiivne (nt bold või nt chrome tabile sarnaselt esiplaanil) see keel, mis on tal kasutajaliideses valitud
2. need 3 nuppu toimiks nagu minitabulatsioon st kui aktiivne on 'eesti keel', saab tippida pealkirja ja kirjelduse kasti eestikeelset sisu
3. kui klikkida teisel keelel siis nende kahe input kasti sisu vahetub ja saad sisestada lisaks või eelmise asemel seda infot inglise või vene keeles
4. eelmise keele pealkirja ja sisulahtrite sisu näeb kui uuesti eesti keelel klikata
5. anda kasutajale indikatsiooni täidetuse kohta, nt kui on lisatud eestikeelsed pealkiri ja kirjeldus, siis on nupul 'eesti keel' nn linnukese ikoon

**Comment by KailiAll** [comment]
Eelduseks on #95 .

**Comment by martlausNG** [comment]
Tehakse #126 all.
