### ISSUE TITLE
keskkondade visuaalne eristatus

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#64]
- [ ] [dev](https://oxygen.netgroupdigital.com) keskkonna logo omab silmaorkavat punast/purpur/vm märget 'dev', e-täht kattub praegusega
- [ ] [test](https://dop.hm.ee) keskkonna logo omab silmaorkavat punast/purpur/vm märget 'test', samuti kattuva e-tähega
- [ ] [live](https://e-koolikott.ee) keskkonna logo on muudatusest puutumata, live baasi kasutus preliveks testi logo ei muuda

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
