### ISSUE TITLE
Tasulise materjali faili tugi

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#65]
1. õppevara looja laeb oma tasulise faili enda kontrollitud keskkonda
2. keskkonda laeb ka selle Issue all defineeritud 'exceli tabeli' juurdepääsuõigustega
3. koolikotti lisatud lingil klikkides toimub seal siis kontroll ja access granted või redirect ostukorvi

vajalik detailne sammude kirjeldus (nt wp põhjal), mis ei nõua tugevat tehnilist tausta õppevara loojalt

Tuleb teha veebileht, kus on 2 vaadet - õppematerjal, kuhu suunatakse ja sisselogimise/regamise leht. Ehk eKoolis vajtutakse antud veebilehe lingile. Antud veebileht loeb tokenist kasutajainfo välja ja siis vastavalt suunab kas regama või õppematerjalile.

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
