### ISSUE TITLE
autor materialboxil

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#66]
1. kuvab miskipärast kahte täppi selle autori initsiaali järel
2. g jt konksuga tähtede konks ei ole korralikult nähtav

![screenshot_20160909_214846](https://cloud.githubusercontent.com/assets/16906555/18398860/3a28a9d6-76d7-11e6-847f-f0667b0e609b.png)

**Comment by erkkijakobson** [comment]
kaks täppi endiselt näha, konksudega korras

**Comment by atatter** [comment]
Äkki oskad öelda millal ja kus see viga tekib kuna ma ei suutnud seda korrata.

**Comment by erkkijakobson** [comment]
nime järel on tühik, süsteem käsitleb tühikut kui teist nime?
tühikut nime järel läbi kasutajaliidese kustutada ei saa

**Comment by martlausNG** [comment]
![image](https://cloud.githubusercontent.com/assets/12746653/20337980/fc837bc0-abdc-11e6-8588-a01edeb0e386.png)
Lives paistab korras olevat.
