### ISSUE TITLE
Täpse otsingu pealkirja ja autori eemaldamine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#69]
**Vajadus**
Detailotsingus kuvada vähem väljasid.
**Tulem**
- [x] Pealkiri ja autor on eemaldatud.

**Comment by KailiAll** [comment]
**Tulem**
Avatud otsing:
![image](https://cloud.githubusercontent.com/assets/19947450/21388116/8509967a-c783-11e6-87b4-0612fcb1f7ac.png)
Haridus ja valdkond
![image](https://cloud.githubusercontent.com/assets/19947450/21388171/c4c796e0-c783-11e6-900d-2086d44481c4.png)
Haridus, valdkond, teema
![image](https://cloud.githubusercontent.com/assets/19947450/21388209/ec304e8e-c783-11e6-80d5-a48e86c12f13.png)
(Põhiharidus), Ainevaldkond, Üldpädevused
![image](https://cloud.githubusercontent.com/assets/19947450/21388240/0ff8f53c-c784-11e6-9f6d-cb5b97f89c5d.png)
Haridus (Põhiharidus), Ainevaldkond, Teema, Läbivad teemad, Üldpädevused
![image](https://cloud.githubusercontent.com/assets/19947450/21388285/3ac20dc6-c784-11e6-93af-9bbc0aba1601.png)
Haridus (Põhiharidus), Ainevaldkond, Teema, Alateema, Läbivad teemad, Üldpädevused
![image](https://cloud.githubusercontent.com/assets/19947450/21388341/8359a530-c784-11e6-8a60-daa2fcd07595.png)
