### ISSUE TITLE
Meediafailide kuvamine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#72]
**Arendussoov:**
- [x] HTML tagide ja .js abil meediafailide kuvamine, fallbackina kuvatakse URL nagu täna.

**Tulem:**
- [x] Kasutaja laeb e-koolikotti video üles ja näeb seda embbedituna.
- [x] Browserid Internet Explorer, Chrome, Firefox, Safari toetavad MP4, WebM ja Ogg videoformaati.

**Comment by martlausNG** [comment]
Toetame video, audio ja img tage.

**Comment by erkkijakobson** [comment]
ei paista toimivat https://dop.hm.ee/material?materialId=7247

**Comment by KailiAll** [comment]
**Viga:**
.jpg ei avane embedituna samas aknas.

**Comment by KailiAll** [comment]
**Testimised tulemused Chromes**

.docx laetakse kasutaja arvutisse, kus ta peab selle eraldi avama.
.DOCX laetakse kasutaja arvutisse, kus ta peab selle eraldi avama.

.pdf avatakse eraldi browseris.
.PDF laetakse kasutaja arvutisse, kus ta peab selle eraldi avama.

.jpg avatakse eraldi browseris.
.JPG laetakse kasutaja arvutisse, kus ta peab selle eraldi avama.

.pptx laetakse kasutaja arvutisse, kus ta peab selle eraldi avama.
.PPTX laetakse kasutaja arvutisse, kus ta peab selle eraldi avama.

Youtube avaneb embbedituna.
Vimeo avaneb embbedituna.
Soundcloud avaneb embbedituna.
