### ISSUE TITLE
Folksonoomiliste võtmesõnade haldus

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#73]
**Arendussoov:**
- [ ] Võimaldada admin ja aineeksperdil saada ülevaade kasutuselolevatest võtmesõnadest.
- [ ] Sorteeritav tähestiku, kasutusarvu ja lisandumise aja järgi, klikkides peal või lingil käivitub Tag: otsing.
- [ ] Eristada peab saama raporteeritud ja blokeeritud võtmesõnu, samuti neid määrata ja maha võtta.
- [ ] Blokeerimise järel eemalduvad võtmesõnad olemasolevate materjalide juurest, edaspidi ei saa lisada.

**Lisainfo:**
- [ ] TAGIdega on võimalik raporteerida TAGi materjali juures (Materjal ja TAG ei lähe kokku). Materjali saab ära parandada ja saab materjali juurest mittesobiva TAGi ära kustutada.
- [ ] TAG on ebasobiv ja seda peaks igalt poolt ära blokeerima.

**Comment by KailiAll** [comment]
**Tulem:**
- [ ] Admin paneeli vaade kõikidest tagidest, kus on ka juures info, et kas nad on bannitud või on nad raporteeritud mingi materjali kontekstis;
- [ ] Eristada saab  raporteeritud ja blokeeritud võtmesõnu, samuti saab neid määrata ja maha võtta.
- [ ] Tagide tabel on sorteeritav ning klikkimisel käivitub antud tagi otsing;
- [ ] Blokeeritud võtmesõnu ei näe materjalides ning neid ei saa ka uuesti lisada;
- [ ] Blokeeritud võtmesõna loogika lisamine andmemudelisse;

**Comment by KailiAll** [comment]
Erkki kommentaar, mida peab samuti tulem kajastama: "Blokeerimise järel eemalduvad võtmesõnad olemasolevate materjalide juurest",

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
