### ISSUE TITLE
Kogumiku vaates vistutatud sisupakettide kuvamine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#74]
Kuvada kogumiku laiuses vistutatud sisu või fallbackina linki praeguste materialboxide asemel.
Kogumiku muutmise režiimis peab olema võimalik materjale eemaldada, ümberpaigutada.
Võimalik peab olema liikuda detailvaatesse, nt läbi väikese nupu.

**Comment by martlausNG** [comment]
Needs review.

**Comment by RannarA** [comment]
Review ok

**Comment by erkkijakobson** [comment]
- [ ] Vistutatud sisu ei oma linki ega päist, muutmisrežiimis võib päis olla, link tohib ainult fallback olla
- [ ] Vistutatud sisu ja sama (alam)peatüki vahele ei tohi tekkida vahehooni - lõhub peatüki kui terviku

**Comment by martlausNG** [comment]
Fallback peab alati olema, sest meie süsteem ei saa kindlaks teha kas embedditud sisu on selle host serveri poolt laetud või mitte
