### ISSUE TITLE
Uute kasutajate kutsumine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#78]
#20 sisselogimata kasutajale näidata samuti menüüpunkti 'Minu koolikott':
- kõigil selle punktidel (materjalid, kogumikud, lemmikud) klikk avab login dialoogi
- dialoogil dünaamiline pealkiri, nt et 'enda kogumike vaatamiseks on vajalik autentimine'
- autentimisjärgne redirect klikitud menüüpunkti, tühja lehe puhul teavitus, nt et kogumiku lisamiseks vajuta allserva (+) nupule

**Comment by RannarA** [comment]
Needs review

**Comment by erkkijakobson** [comment]
* uus inkognito aken (Chrome ja Firefox) -> Minu koolikott ei ole kohe avatud olekus
* nende 3 punkti sisumall hüpleb erinevatel kõrgustel, uuel kasutajal eriti hästi näha

**Comment by martlausNG** [comment]
Pealkiri hüppab

**Comment by erkkijakobson** [comment]
1. puudu lingil 'Minu kogumikud' klikkides dialoogakna päise tõlge:
![image](https://cloud.githubusercontent.com/assets/16906555/19674932/1372ac7a-9a94-11e6-9f54-f00e7444e1aa.png)

2. autentimisjärgne redirect ei toimi ühelgi lingil kolmest
