### ISSUE TITLE
Sotsiaalvõrgu kontoga autentimine

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#79]
**Arendusvajadus:**
- [ ] Vajalik olemasolevate autentimisvahendite käest saada ühekordselt IK.

**Tulem:**

Kui kasutaja on olemas.
- [ ] Üleval paremal nurgas on nupp "Seo Googliga" ja "Seo Facebookiga" ja klikid nupule.
- [ ] Alla paremale nurka tuleb teavitus, et oled sisse loginud.

Kui kasutajat ei ole olemas.
- [ ] Kasutaja logib sisse Google või Facebookiga (rakendub tulevikus EIDASELE).
- [ ] Teeme uue rolli, nt Demo user. 
- [ ] Demo user saab lisada lemmikuks, välja logida, sisse logida, näeb enda lemmikuid. Kui klikib materjalide või kogumike peal, siis talle kuvatakse sisselogimise kast. Nüüd näeb kastis ainult sisselogimise meetodeid, kust saab isikukoodi.
- [ ] Kui oled rolliga sisse loginud, siis näed teadet, et täisfunktsionaalsuse nägemiseks pead olema sisse logitud (ID kaardi, eKooli jne).

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
