### ISSUE TITLE
Materjali lisamisel taksonite täitmine vabateksti väljalt

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#80]
**Praegu:** 1 kuni 5 üksteisest sõltuvat rippmenüüd, ei saa kiirelt lisada märksõna, nt _takistit_
**Vajadus:** taksoni rea alguses (alternatiivina enne rippmenüüd) sugestiivne vabateksti väli 'Lisa märksõna', sisestades nt _takisti_ täitub rida koheselt 4 taksoniga

**Tulem:**
- [ ] Saab otsida taksonoomiaid.

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
