### ISSUE TITLE
Kustutamine ei toimi

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#81]
detailvaade -> menüü -> 'Kustuta materjal' -> 'Jah'
**oodatud tulemus:** materjal kustub
**praegune tulemus:** ei kustu
testitud materialID=1640

**Comment by KailiAll** [comment]
Mis keskkonnas viga tekib?

**Comment by erkkijakobson** [comment]
kõigis, dev keskkonna materialId=4574

**Comment by martlausNG** [comment]
Vana äriloogika ei lubanud kustutada välise repo materjale.

**Comment by erkkijakobson** [comment]
toimib, aga milleks redirect kusutatute lehele?
