### ISSUE TITLE
Pisikaardid koos parempoolse paigutusega (ilma täiendava loogikata)

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#84]
https://material.google.com/components/cards.html#cards-usage

**Comment by KailiAll** [comment]
Milliseid asju me seal näitame?
Kas on õige, et näitame pealkirja, pisipilti ja vanuserühma?

**Comment by aivo0** [comment]
**Tulem**
- [ ] Pisikaardil on pilt ja pealkiri. Pealkiri on lühendatav kolme punktiga, kui liiga pikk. 
- [ ] On lips peal, kui on kogumikus 
- [ ] Saab olla lemmik ja saab lemmikuks lisada (täht peal)
