### ISSUE TITLE
Numbrid sisukorda

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#86]
Õppekava sirvimisel kuvada Iga vasakmenüü taksoni juures numbrit talle vastava õppevara kohta, kui õppevara ei leidu, siis numbrit ei näita ja taksoni klikk otsingut ei teosta

**Comment by martlausNG** [comment]
Eesmärk on säilitada lehe kiirus tehes kalleid count päringuid kogu baasile.

**Comment by aivo0** [comment]
Kui mureks on päringu kiirus, siis seda peaks ju saama baasi poolel vajadusel optimeerida. Et oleksid count-id juba välja arvutatud vms.
