### ISSUE TITLE
Väikese kaardi muudatused

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#90]
**Arendusvajadus:**
- Ikoonide ja materjali tüüpide gruppide ülevaatamine.
- Kui materjalil ei ole pilti, siis kasutatakse cssiga kujundatud tausta.
- Kasutame pisipilti. Eelduseks #83

**Comment by aivo0** [comment]
**Tulem**
- [ ] Grupid on üle vaadatud.
- [ ] CSS-ga kujundatud taust igale materjali tüübile. 
- [ ] Kogumiku korral pole enam murtud nurk, vaid kasutame _bookmark_i ikooni.
- [ ] Elemendid kaardil ümber paigutatud (lukk ja lahtine lukk, lemmiku ikoon ja _overlay_, märkering, kogumiku lips).

**Comment by KailiAll** [comment]
Erkki kommentaar: #90 kõige väiksemal murdepunktil (kuni 599) ei kuvata soovituste pisikaarte, tavaliste materialboxide asemel kuvatakse materjale pisikaartide kujul (oluline neid flexida erkaani laiuseni)

**Comment by erkkijakobson** [comment]
hetkel oxygenis ei joondu pealkirja alused andmed vastavalt 15.12 13:26 kirjale - viited lillalt;
proportsioonid (50% pilt ja 50% muu) näikse samuti nihkes, pildil siniste suhteliste numbritena
![image](https://cloud.githubusercontent.com/assets/16906555/21420591/4332755a-c837-11e6-9a62-9663c8de5fd3.png)

**Comment by kokakoola** [comment]
tekstimahud võivad olla erinevad. eriti testkeskkonnas:
![screen shot 2016-12-22 at 11 32 21](https://cloud.githubusercontent.com/assets/672595/21421250/86376808-c83a-11e6-8220-859ccafa3374.png)

**Comment by erkkijakobson** [comment]
- kaardi 50% pilt 50% valgeosa suhe ei saanud korda - hetkel 47/53 või 50/56 märkimaks ülejäävat
- joondusest sai korda pool: autor joondub pealkirja alla, kuid ülejäänud meta ei joondu allaserva
- testkeskkonnas on tekkinud olukord kus kaardil on neli (4) õppeainet:

![image](https://cloud.githubusercontent.com/assets/16906555/21522226/4b1a52c2-cd0c-11e6-9997-a2ae5b5a8ae8.png)

**Comment by KailiAll** [comment]
@erkkijakobson 
Sinu kommentaar: testkeskkonnas on tekkinud olukord kus kaardil on neli (4) õppeainet:
Tegemist ei ole veaga, kuna pileti https://github.com/hariduspilv/koolikott/issues/123 raames sai tehtud muudatus, kus oli kirjas, et "Valida peab saama mitut vanuse kategooriat ja ainevaldkonda" ja seal on tekkinud ka kaardile see info.

**Comment by KailiAll** [comment]
@erkkijakobson 
Kuna meie hinnangul ei ole tegemist veaga, siis teen ettepaneku.
Kui kasutaja lisab kogumiku loomisel sama hariduse ja õppeained,
![image](https://cloud.githubusercontent.com/assets/19947450/21720838/06dc2738-d42e-11e6-90e9-18185b678996.png)
siis kui kasutaja on kogumiku detailvaates.
![image](https://cloud.githubusercontent.com/assets/19947450/21720859/27ee7700-d42e-11e6-9767-b8cb92e11250.png)
,kuvatakse ainult esimesena lisatud haridust ja õppeainet ning edasi tuleb kolm punkti.

**Comment by erkkijakobson** [comment]
antud pildimaterjali näites on tegu siiski ühe haridustaseme ja ühe õppeainega, mida peab näitama 1x

ettepanek võiks olla kahe või enama haridustaseme all oleva ühe õppeaine konsolideerimine visuaalis

**Comment by KailiAll** [comment]
vabandust. Eelnev jutt ei käi pisikaardi kohta ja lahendame selles piletis juba asju, mis ei ole selle pileti teemad.

**Comment by KailiAll** [comment]
**Vastavalt telefonivestlusele:**
- [ ] Kui kasutaja "Lisa kogumiku põhiandmed" vaates lisab:
- [ ] nt Muusika, siis väikesel kaardil kuvatakse 1 kord Muusika
- [ ] nt Muusika ja Bioloogia, siis väikesel kaardil kuvatakse 1 kord Muusika ja 1 kord Bioloogia
- [ ] nt Muusika, Bioloogia ja Matemaatika, siis väikesel kaardil kuvatakse 1 kord Muusika, 1 kord Bioloogia ja edasi on kolm täppi (...).
- [ ] nt Muusika ja Kunst, siis väikesel kaardil kuvatakse 1 kord kunstiained.

**Comment by KailiAll** [comment]
Sulgen selle pileti, kuna arendussoov on realiseeritud uue pileti all #165
