### ISSUE TITLE
Suure kaardi muudatused

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#91]
**Arendusvajadus:**
- [x] kuvada metaandmete olemasolul üldpädevusi, läbivaid teemasid, teemasid, alamteemasid kahel real ja kolm täppi tuleb lõppu kui asju on rohkem v.a IEs.
- [x] kavandada asukoht ka hiljem lisanduvatele metaväljadele: vorming 'EPUB', maht '384 KiB'; '3 MiB'
- [x] #57 -retsensiooni ette kuvada faili või lingi ikoon (retsensoon või retsensioonid; kui on link, siis on nii mitu lingi ikooni; tooltipis peab olema lingi aadress; kui on fail/ failid, siis on üks/ mitu ikooni.
- [x] HTMLide ühtlustamine

**Tulem:**
- [x] Süsteemis täna tekstinäiteid omavad metaväljad jaotatud üles ja paremale tulpa.

teemade näide [seos õppekavaga](https://koolielu.ee/waramu/view/1-0539921e-1458-424c-aa37-3cddce062d3c)

**Comment by KailiAll** [comment]
Mis on hiljem lisanduvad metaväljad?
Loetleda, millised metaväljad.

**Comment by aivo0** [comment]
**Tulem**
- [ ] HTML-d on ühtlustatud.
- [ ] Metaväljad paigutatud: olemasolevad ja uued (üldpädevused, läbivaid teemad, teemad, alamteemad, faili tüüp ja maht ja suurus)

**Comment by KailiAll** [comment]
@erkkijakobson 
Mis on hiljem lisanduvad metaväljad?
Loetleda, millised metaväljad.
Vaja näiteid tekstidest.

**Comment by KailiAll** [comment]
info lisatud arendusvajaduse juurde;

**Comment by kokakoola** [comment]
@erkkijakobson 
1. suurel kaardil on ka vajalik maha võtta korduvad metad (sama, mis väiksel), palun ära teha
2. muutsin nii et on 2 rida ja nii palju kui mahub metat. 
3. **ma tahaks ära võtta selle “teadmata” teksti igalt poolt. kui infot pole, siis ei kuvata seda tulpa üldse on ettepanek** - Nt tüüp Teadmata - ei kuvata. Või Tüüp: Blogi, Teadmata, Video - Teadmata ei kuvata.

**Comment by kokakoola** [comment]
@erkkijakobson 
Tõlge - kirjutaks "Litsentsi tüüp" asemel "Litsents" - palun. 
Muutus: Vaatamisi võiks olla nagu väiksel kaardil ikoon ja asuda pöialde juures.

**Comment by RannarA** [comment]
@erkkijakobson Kas suurel kaardil tuleb teha sarnast koondamist nagu väikesel kaardil:
muusika, kunst => kunstiained?

**Comment by KailiAll** [comment]
@RannarA 
Kui kogumiku loomisel on valitud:
![image](https://cloud.githubusercontent.com/assets/19947450/21891425/43ab5e02-d8db-11e6-9cb2-dfa058a3e3fc.png)
siis on vaja suurel kaardi detailvaates kuvada ainult Keel ja Kirjandus.
Praegu kuvatakse kirjandus, eesti keel, vene keel...

**Comment by kokakoola** [comment]
@erkkijakobson Kas materjal võib olla lõpmata pikk (nagu praegu, oxygenis /material?id=10669) või peaks suunama omaloomingu korral inimesi Kogumikku looma? Tundub mulle nii. Siin aitaks kui materjali korral oleks kirjelduse pikkus piiratud tähemärkide arvuga. Samas peaks vabatahlike andmetena olema võimalus täpsustada metaandmeid kogumiku korral võimalikult samas mahus kui Materjali korral - et inimestel, kes metaandmete võlusid tundma on õppinud ei tekiks kiusatust Materjali formaati kasutada ainult põhjusel, et sellele saab rohkem metat kaasa anda.

**Comment by KailiAll** [comment]
@kokakoola 
koodis pidi olema materjali pikkus piiratud.

**Comment by kokakoola** [comment]
Metad, mis kirjeldavad liigitust, paneme üles äärde: 
- Haridustase -> Ainevaldkond -> Teema -> Alamteema. Kuvatakse 2 real, kui tekst ületab seda mahtu, tekib lõppu 3 punkti. Kõiki liigtusi näeb klikkides meta pealkirjale või noolele - selle peale avanevad metad akordionina alla. Subtiilselt kirjeldab nool ka hierarhilist järjestust. Iga meta ise on link - hoveriga läheb siniseks ja kursor on pointer. **NB!** vajalik läbi mõelda otsitulemuste leht, miinimum on lisada otsitulemuste lehe päisesse mõistlik tulemusi kirjeldav tekst.

Metad, mis kirjeldavad otseselt materjali "füüsilisi" omadusi lähevad kaardi hoverile:
- Tüüp, Vorming, Maht.

Metad, mis oleks tiitellehel kui tegu oleks raamatuga on paremas tulbas, alguses üldised, siis eraldatult koolialased. Viimane on Litsents, mida kirjeldatakse võimalusel ikoonina, see vajab kirjeldavat tooltipi selgtiusega.

Metad, mis väiksel kaardil on all servas, on ka siin allservas. Meeldimised-vaatamised ikooniga paremal, iseloomustust kandvad (nii kommentaar kui retsensioon) vasakul. Retsensioonil on ikoon link või fail ja tooltip seletusega. Kommentaari ikoon käitub nagu vanasti - avaneb akordionina alla.

Õpiväljundite meta saab endale eraldi jaotuse, teinekord on ta pikk.

![card-lg](https://cloud.githubusercontent.com/assets/672595/21980990/10c52ff2-dbee-11e6-94c4-2762093a105b.png)
![card-lg-hover](https://cloud.githubusercontent.com/assets/672595/21980994/16d002e6-dbee-11e6-926e-accecffc5b02.png)
