### ISSUE TITLE
Kogumiku peatükkide sisu järjestus ja paigutus

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#93]
**Vajadus**
Praegu on peatükis järjestus ülalt alla: kõigepealt 1 tekstikast, mille järel võib olla 1 või mitu materjali
Võimaldada lisada täiendavaid tekstikaste ja vaheldumisi materjalidega (kõik omavahel pukseeritavad)
Võimaldada ka kõrvutipaigutust, nt tekst-materjal, materjal-materjal (kuvab toetatud murdepunktidel)

Eeldab tööriistariba: #121 
Eeldab disaini: #129 
Eeldab andmestruktuuri muudatust: #130
**Tulem**
- [ ] Kasutaja saab lisada ühe või mitu tekstikasti materjalide vahele. (Tähendab refaktoreerimist ja andmete migreerimist, sest praegu hoitakse andmeid teise struktuuriga).
- [ ] Kasutaja saab materjale ja tekste kõrvuti paigutada.
- [ ] Kasutaja saab materjali ja/või teksti järjekorda ja kõrvuti asetsemist muuta.
- [ ] Kõrvuti asetsevad materjalid kuvatakse väiksel ekraanil üksteise all (sõltuvalt murdepunktist).

**Comment by aivo0** [comment]
![image](https://cloud.githubusercontent.com/assets/8111493/20700568/b827d02c-b616-11e6-9151-fc1d1b382cdf.png)

**Comment by erkisisask** [comment]
Sulgen issue, sest käesoleva issuega seotud issued #121, #129 ja #130 on tehtud.
