### ISSUE TITLE
Töölauale viimati lisatud õppevara modereerimiseks

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#94]
**Arendusvajadus:**
- Aineekspert peab omama parameetrit kas [haridustaseme, erivajaduse, valdkonna või õppeaine kohta](http://www.haridustehnoloogid.ee/vorgustiku-liikmete-kontaktid/koolielu-portaali-aineeksperdid)
- Põhi- ja keskhariduse taksonid (nt mate) toimivad parameetriks olles mõlemas haridustasemes
- Töölaud (mitte selle alampunkt) teostab parameetri põhise otsingu, uusimad eespool
- Parameetrit saab määrata #49 vaates ja lehel Töölaud, seal kus muidu on sorteerimise nupp
- Admin kasutaja Töölaud on sama, mis aineeksperdil, nt saab endale määrata parameetriks Füüsika

**Comment by martlausNG** [comment]
menüü oleks:
Minu Kogumikud
Minu Materjalid
Minu Lemmikud
Töölaud                    <- Toimub otsing aineeksperdile seatud parameetri(te) järgi
- raporteeritud
- kustutatud
- jne Töölaua alampunkidena

**Comment by martlausNG** [comment]
Antud taski kontekstist jääb välja: 
* Parameetrit saab määrata #49 vaates ja lehel Töölaud, seal kus muidu on sorteerimise nupp
* Admin kasutaja Töölaud on sama, mis aineeksperdil, nt saab endale määrata parameetriks Füüsika

ehk sorteerimise nuppu ei tule, moderaatorile/adminile peab olema baasis määratud list taksonoomiatest.
