### ISSUE TITLE
Materjali sisestamise modaali kujundus

### ISSUE THREAD

**Issue by KailiAll** [hariduspilv/koolikott#95]
**Arendusvajadus:**
- [ ] UI korrastamine. (staatiline mock-up)
- [ ] Userflowde kirjeldamine.

**Tulem:**
- [ ] Materjali sisestamine on mugavam. Tulemuseks staatiline mock-up.
- [ ] Userflowd on kirjeldatud.

**Comment by martlausNG** [comment]
Tehakse #126 all
