### ISSUE TITLE
Staatiliste sisulehtede muudatus

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#98]
jääb vaid modaalaknas avanev about leht, muudetav admin kasutaja poolt textangularis
help käivitab #54 tuuri hetkelavatud vaate kohta

**Comment by erkisisask** [comment]
18.12.2018 projektijuhtide koosoleku otsusega otsustati seda tööd mitte realiseerida ja seetõttu läheb sulgemisele.
