### ISSUE TITLE
Autentimata kasutaja interaktsioonid

### ISSUE THREAD

**Issue by erkkijakobson** [hariduspilv/koolikott#99]
**Arendusvajadus:**
- [ ] Praegu kolme täpi menüüs vaid lingi kopeerimine, vaja lisaks raporteerimist.

**Tulem:**
- [ ] Kolme täpi menüüsse audentimata kasutajal lisandub kogumiku vaatesse "Teavita ebasobivast sisust" ja materjali vaatesse "Teavita ebasobivast sisust" ja "Teavita katkisest materjalis".  
- [ ] Kolme täpi menüüsse blokeeritud kasutajal lisandub kogumiku vaatesse "Teavita ebasobivast sisust" ja materjali vaatesse "Teavita ebasobivast sisust" ja "Teavita katkisest materjalis".

**Comment by aivo0** [comment]
@erkkijakobson Kas see viimane tulem on mõistlik üldse teha - Mare ja teiste hinnangul oleks halb mõte neid nuppe panna kuhugi mujale, kui kolme nupu taha. Seega see prototüüpimine oleks vähe kasulik ja pigem soovitaks tegeleda prioriteetsemate taskidega.

**Comment by aivo0** [comment]
Viimasest kommentaarist tulenevalt seda tulemit ei hinnanud:
- Lahendus on prototüübitud ja nupud on kohe nähe, mitte ei ole kolme täpi taga.

**Comment by KatarinaNeff** [comment]
kui raporteerijaks on autentimata kasutaja, siis admin näeb, et "Raporteeris" veerus -"Autentimata kasutaja"
